### ISSUE TITLE
哈尔滨地铁、重庆轨道交通线路图模板

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [railmapgen/rmp#105]
[templates.zip](https://github.com/railmapgen/rmp/files/9943168/templates.zip)

**Comment by thekingofcity** [comment]
Hi, thanks your contribution and effort.

However, we currently won’t merge any templates as rmp-gallery is not finished and templates selection is not already.

We’ll keep rmp updated and rmp-gallery ready in the next few months.

**Comment by thekingofcity** [comment]
Hi, you may now use RMP Gallery to submit your works!

https://railmapgen.github.io/?app=rmp-gallery
