### ISSUE TITLE
港铁模板

### ISSUE THREAD

**Issue by lty110** [railmapgen/rmp#109]
[mtr.zip](https://github.com/railmapgen/rmp/files/10147849/mtr.zip)

**Comment by thekingofcity** [comment]
Hi, thanks your contribution and effort.

However, we currently won’t merge any templates as:
1. MTR stations and lines are on the road map in the next few months.
2. rmp-gallery is not finished and templates selection is not already.

**Comment by Gzline4-24hc** [comment]
港铁的支线分叉是两个圆形车站组成的，不是一个

**Comment by thekingofcity** [comment]
Hi, thanks for your patience. You may now use RMP Gallery to submit your works!

https://railmapgen.github.io/?app=rmp-gallery
