### ISSUE TITLE
无法编辑车站

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmp#111]
在车站站名名称横、纵向偏移均设置为middle并关闭编辑页面后，站点圆圈被站名覆盖而无法编辑
<img width="62" alt="屏幕截图 2022-12-07 175519" src="https://user-images.githubusercontent.com/120014893/206147089-5a689f99-e21b-402a-be80-d33d4c43286b.png">

**Comment by aaronyz2007** [comment]
（附图为例子）

**Comment by thekingofcity** [comment]
你好，感谢汇报问题，现在已无法在选择一个为middle的时候选择另一项也为middle。

修复已上线，如果您还相对当前存档中的此站进行更改，欢迎上传存档到对话框中，我将单独进行修复后再上传回此处。

**Comment by Eleusia** [comment]
[RMP_1673146985162.zip](https://github.com/railmapgen/rmp/files/10368004/RMP_1673146985162.zip)
需要修复车站,谢谢作者大大!

**Comment by Eleusia** [comment]
![$~3AY7KPBCITE935UM62CY](https://user-images.githubusercontent.com/121091671/211187599-735d1d3a-8500-428c-9fab-c943bce1199d.png)
即这两座车站

**Comment by thekingofcity** [comment]
嗨 @Eleusia 这两座车站都已被修复，您可以解压并重新载入存档查看。

![image](https://user-images.githubusercontent.com/3353040/211271778-02852dad-3997-4c22-a753-f7dcdfe267ce.png)

[RMP_1673146985162.zip](https://github.com/railmapgen/rmp/files/10371742/RMP_1673146985162.zip)
