### ISSUE TITLE
Invisbility misc node / 不可见的线路节点

### ISSUE THREAD

**Issue by BadHunyun** [railmapgen/rmp#112]
有时，我们必须用线路节点来优化布线，但导出时的线路节点非常**恼人**，要么**一个像素一个像素**地抠掉 ，要么直接摆烂走一盘*印度布线*

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题。现已确认此问题是由于之前的一次更新中错误的操作，修复的代码已推送并上线。符合预期的是带有十字的圆圈节点在导出图片时被隐藏。
