### ISSUE TITLE
Fix line code overflow in gzmtr-basic

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmp#116]
![image](https://user-images.githubusercontent.com/108232422/207199247-7dd6e333-164f-42dd-9c1a-62696e31c89b.png)
当线路号输入超过3个字符的时候，就会发现最后一个字符与中间分隔线重合。

_Originally posted by @hackerfyl in https://github.com/railmapgen/rmp/issues/114_

**Comment by hackerfyl** [comment]
自动回复：已收到！

**Comment by wongchito** [comment]
Fixed by #492 

<img width="565" alt="image" src="https://github.com/railmapgen/rmp/assets/9390786/7d6f5aa8-0b84-4ee5-a5f4-27282f72b3c0">

**Comment by hackerfyl** [comment]
自动回复：已收到！
