### ISSUE TITLE
添加宁波地铁模板

### ISSUE THREAD

**Issue by feitongxiaok** [railmapgen/rmp#118]
[宁波.zip](https://github.com/railmapgen/rmp/files/10298044/default.zip)
望收录

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution and effort.

However, we currently won’t merge any templates as rmp-gallery is not finished and templates selection is not ready.

We’ll keep rmp updated and rmp-gallery ready in the next few months.

**Comment by thekingofcity** [comment]
Hi, thanks for your patience. You may now use RMP Gallery to submit your works!

https://railmapgen.github.io/?app=rmp-gallery
