### ISSUE TITLE
Safari 字体显示故障

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp#120]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/59787082/209513967-80045d29-93aa-4fb4-93b9-65b1984eecc0.png">

- System: macOS Ventura 13.1 (arm 64 M2)
- Browser: Safari

原来（上个月）是可以正常显示的，现在 `0.1.47` 版本似乎有些问题。

**Comment by langonginc** [comment]
另附iPhone Safari同样也有问题

![99D28348-86E0-4EA2-829C-7E7D387713C4](https://user-images.githubusercontent.com/59787082/209514447-ec450a11-da09-4e04-80a1-2e3319cbd266.jpeg)

**Comment by thekingofcity** [comment]
嗨，在Chrome和Firefox上也是如此吗？这应该是由于 #103 更新引入的错误，我将尽快进行检查并修复，谢谢汇报。

**Comment by langonginc** [comment]
iPhone 上的 Edge 存在这样的错误，但是我刚才装的 macOS Chrome 108.0.5359.124 并没有这样的错误。

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/59787082/209543557-44bf2f64-d271-422b-90c1-c3a4060cfe16.png">

**Comment by langonginc** [comment]
附上文所述 iPhone Edge 浏览器截图

![4F449343-156B-47B9-BC98-4544B884F1B9](https://user-images.githubusercontent.com/59787082/209544323-f691822a-c138-4e53-b048-9196b260366e.png)

**Comment by 52PD** [comment]
> iPhone 上的 Edge 存在这样的错误，但是我刚才装的 macOS Chrome 108.0.5359.124 并没有这样的错误。

iOS/iPadOS/tvOS上所有浏览器（包括Chrome，Edge和Firefox）统一按Safari算（因为系统限制原因所有iOS系统家族的第三方浏览器都是只能用Safari的WebKit内核的）

而macOS上因为没这个浏览器内核限制所以是可以像Windows一样正常用第三方内核的（比如Chrome和Mac端的Edge用的都是Chromium内核）

**Comment by thekingofcity** [comment]
嗨，我已修复此问题，欢迎刷新页面后确认版本为0.1.48后再确认。

**Comment by langonginc** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59787082/209959820-4981bf77-91ec-47ff-9c2c-73fac62cc573.png">

@thekingofcity 这个问题似乎并没有被解决（？

**Comment by thekingofcity** [comment]
我推送了一个新的修复，如果问题已被解决欢迎直接close issue，如果没有的话麻烦继续截图展示，谢谢。

**Comment by langonginc** [comment]
Thanks!

**Comment by 52PD** [comment]
重开了，广州风的线路名字体还是歪的🌝（浏览器为Safari Version 16.1 (18614.2.9.1.12)）
![Screenshot 2023-01-07 at 6 04 24 PM](https://user-images.githubusercontent.com/98044618/211173445-32571d97-21e3-4f51-9fd1-06dc4caeb0ca.png)

**Comment by thekingofcity** [comment]
@52PD 我推送了一个新的修复，有空看看是否解决了此问题？

**Comment by langonginc** [comment]
我这边这个新问题好像解决了
