### ISSUE TITLE
允许virtual类型线条设置起点和终点偏移

### ISSUE THREAD

**Issue by harry-xi** [railmapgen/rmp#135]

**Comment by thekingofcity** [comment]
嗨，感谢建议，想确认一下virtual类型线条指的是上海虚拟换乘或者广州的APM换乘吗？如果是的话因为这些线条是单纯(x1,y1)到(x2,y2)的模式，与现有其他线段的起点终点偏移无关，无法实现。具体一点说，现有其他线段的起点终点偏移是通过计算线段斜率后计算出对应在垂直线上的距离的dx和dy再apply，而纯两点之间的连线目前还无此计算方式。可以截图或者文字说明一下需要的情况吗？我可能会考虑对于virtual类型线条添加起点终点的dxdy输入。

**Comment by harry-xi** [comment]
> 嗨，感谢建议，想确认一下virtual类型线条指的是上海虚拟换乘或者广州的APM换乘吗？如果是的话因为这些线条是单纯(x1,y1)到(x2,y2)的模式，与现有其他线段的起点终点偏移无关，无法实现。具体一点说，现有其他线段的起点终点偏移是通过计算线段斜率后计算出对应在垂直线上的距离的dx和dy再apply，而纯两点之间的连线目前还无此计算方式。可以截图或者文字说明一下需要的情况吗？我可能会考虑对于virtual类型线条添加起点终点的dxdy输入。

如果实现起来有麻烦或者这部分和您的整体设计的话其实不必麻烦，我是在期待一个可通过x，y两个方向上分别设置偏移来进行的偏移设置，，这可以带来一些便利。另外大部分情况下，使用virtual类型的点进行连线是可以在输出效果上解决问题的。

很感谢您对此的关注。

**Comment by thekingofcity** [comment]
实现上不存在什么问题，但除了确认建议内容和实现方式外，实现这个功能的优先级也要被考虑到。在现实地铁图中，虚拟换乘一般不会跨越长距离，即只会链接两个相邻车站，很难想象这种情况下为何需要设置偏移。所以如果有一些截图或者文字说明什么情况下会用到这种功能会提升实现的必要性。

**Comment by harry-xi** [comment]
> 实现上不存在什么问题，但除了确认建议内容和实现方式外，实现这个功能的优先级也要被考虑到。在现实地铁图中，虚拟换乘一般不会跨越长距离，即只会链接两个相邻车站，很难想象这种情况下为何需要设置偏移。所以如果有一些截图或者文字说明什么情况下会用到这种功能会提升实现的必要性。

我的回复其实换句话说其实就是我也觉得必要性不怎么大，这个功能可以往后放放甚至不做。

**Comment by thekingofcity** [comment]
嗨，您提到的这个功能在RMP 2中已被实现，欢迎尝试 :)
