### ISSUE TITLE
广州地铁换乘站无法被点击编辑

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/rmp#136]
![image](https://user-images.githubusercontent.com/108232422/211234017-ecbe332c-706d-497e-804b-b08586ccd3c8.png)
### **广州地铁风格的换乘站无法点击编辑。**

**Comment by thekingofcity** [comment]
嗨，感谢您反馈问题，此问题已被修复。

**Comment by hackerfyl** [comment]
自动回复：已收到！
