### ISSUE TITLE
The newest Beijing Subway 最新北京地铁线路图

### ISSUE THREAD

**Issue by YeeHOMO** [railmapgen/rmp#138]
[RMP_1673234752138.zip](https://github.com/railmapgen/rmp/files/10370197/RMP_1673234752138.zip)
2022年底最新更新：增加16号线南段、昌平线南延
The latest update at the end of 2022: add the southern section of Line 16 and the southern extension of Changping Line

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与贡献。不过据我所知昌平线南延还尚未开通，更多关于北京地铁线路图的更新讨论欢迎查看 #126 
Hi, thanks for the contribution. But from my understanding, the southern extension of Changping Line is not opened yet. And for more discussion about the Beijing Subway template, see #126 for more information.

**Comment by 52PD** [comment]
> 嗨，感谢您对项目的支持与贡献。不过据我所知昌平线南延还尚未开通，更多关于北京地铁线路图的更新讨论欢迎查看 #126

其实这次昌平线南延画上去我觉得没问题（毕竟官方都画上去了），只要把所有南延车站全写上“（暂缓开通）”就没什么问题了。

但如果这个更新里面只是增加了16号线南段和昌平线南延部分而没有把所有车站英文名更改为2023年的“新”命名规则的话我是肯定不会给批准的

**Comment by thekingofcity** [comment]
Should be fixed in #144. Thank you all for this latest rail map!
