### ISSUE TITLE
换乘站的回车显示有误

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp#139]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/59787082/211239902-b7499777-3695-459e-8ae4-89d0958e17d0.png">

- rmp 1.0.4
- Chrome / Safari 都发现了问题

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，北京换乘站的多行文字功能确实没有实现，之前更新时忘记了，之后会进行修复。

**Comment by langonginc** [comment]
另外 `middle` 这个能不能也一起加上呢

<img width="775" alt="image" src="https://user-images.githubusercontent.com/59787082/211267310-297db727-9913-43e3-b697-cbfb769c142a.png">

**Comment by thekingofcity** [comment]
嗨，您所提到的问题都已修复，感谢您对项目的支持与建议！
