### ISSUE TITLE
Keep drawing lines after mouse up

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmp#141]
### **添加保持连接选项**
如果要一直不断连线，则每次连完一个站以后又要重新点连线选项去连线。可以添加一个“是否保持连线状态”的选项，开启后，点击连线选项后每次都默认连线，不会拖动站，直到再次点击连线选项取消连线。可能会有更好的名称

_Originally posted by @Dingdong2334 in https://github.com/railmapgen/rmp/issues/79_

**Comment by rainydew** [comment]
目前实际体验上还有一个小问题：目标站点感应区太小，导致在地图视野稍大(例如站距较长时)，站点的显示十分小，拖动到目标站点非常不容易。希望像不少做图软件类似，可以像磁铁一样自动吸附。同样，在拖动站点位置时，也希望可以吸附周边的站点的坐标，使之恰好成水平线或垂直线

**Comment by thekingofcity** [comment]
> 目前实际体验上还有一个小问题：目标站点感应区太小，导致在地图视野稍大(例如站距较长时)，站点的显示十分小，拖动到目标站点非常不容易。希望像不少做图软件类似，可以像磁铁一样自动吸附。同样，在拖动站点位置时，也希望可以吸附周边的站点的坐标，使之恰好成水平线或垂直线

@rainydew 嗨感谢对项目的支持与建议。

关于第一点 _希望像不少做图软件类似，可以像磁铁一样自动吸附_，我不是很能理解是要怎么样的一种形式，如果可以有视频之类的加以说明就好了。第二点的话我之前有思考过这个功能，但自动对齐这个功能实现起来比较复杂，很难说在目前有对齐在10的倍数上这个功能后还有很强的急迫性。

由于这两个建议与本issue关系不大，欢迎准备另开新issue讨论，谢谢。

**Comment by rainydew** [comment]
> > 目前实际体验上还有一个小问题：目标站点感应区太小，导致在地图视野稍大(例如站距较长时)，站点的显示十分小，拖动到目标站点非常不容易。希望像不少做图软件类似，可以像磁铁一样自动吸附。同样，在拖动站点位置时，也希望可以吸附周边的站点的坐标，使之恰好成水平线或垂直线
> 
> @rainydew 嗨感谢对项目的支持与建议。
> 
> 关于第一点 _希望像不少做图软件类似，可以像磁铁一样自动吸附_，我不是很能理解是要怎么样的一种形式，如果可以有视频之类的加以说明就好了。第二点的话我之前有思考过这个功能，但自动对齐这个功能实现起来比较复杂，很难说在目前有对齐在10的倍数上这个功能后还有很强的急迫性。
> 
> 由于这两个建议与本issue关系不大，欢迎另开新issue讨论，谢谢。

谢谢

上面的可以理解为类似flash的自动贴齐功能，AI也有类似的实现
作线段时，如果遇到附近的端点(站点)，鼠标拖到比较近的地方可以自动吸附上去

拖动一个站点时，如果周围有其他的点，那么会自动吸附到和该点有同样横/纵坐标的水平线上，这样方便对齐网格(目前基本上只能靠记住坐标，并手动输入坐标)

**Comment by thekingofcity** [comment]
嗨，此功能已经上线。您也可以在使用完任意工具后按下键盘f键重新使用。

![image](https://user-images.githubusercontent.com/3353040/222739911-ff936aba-2d7d-4747-aab1-28ecc005cb64.png)

关于自动吸附和对齐，欢迎另开issue讨论与追踪 :)

**Comment by rainydew** [comment]
谢谢～看到了
