### ISSUE TITLE
关于 “保存的项目” 的建议

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp#145]
建议将 RMG 的保存的项目搬运过来，挺实用的。

<img width="609" alt="image" src="https://user-images.githubusercontent.com/59787082/211944955-4cd74bd9-626a-45bc-afc6-5ea796306d5c.png">

> RMG 的“保存的项目”

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。

如果您说的是源于 [railmapgen/rmg#31](https://github.com/railmapgen/rmg/issues/31) 第9的点建议，那目前rmp暂未有这个计划。首先，rmp不会涉及到在编辑一个城市多条线路是来回切换存档的情况，即用户可以在当前的项目中从头到尾地完成所有操作。其次，rmp提供的导入导出json存档也能满足基本的备份恢复需求，我认为依赖操作系统的存档管理相比在rmp中实现更有优势。

欢迎回复实现此功能可能带来的操作上的简便 :)

**Comment by langonginc** [comment]
嗯，可能用处不大。

我前几天画北京图的时候想着切换到旧的那个图上看看一些地方是怎么画的，我怕污染 cookie，只好又开了一个电脑，接到旁边的显示器上，略有点麻烦。

**Comment by thekingofcity** [comment]
> 我前几天画北京图的时候想着切换到旧的那个图上看看一些地方是怎么画的，我怕污染 cookie，只好又开了一个电脑，接到旁边的显示器上，略有点麻烦。

针对这种情况，您可以打开当前浏览器的隐身模式/窗口访问rmp或者打开另一浏览器来访问rmp，这两种方式都不会造成存档的互相影响。

**Comment by langonginc** [comment]
ok, thanks
