### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#152]
1. 北京地铁换乘站有点向上偏移
2. 建议加一个北京地铁线路标识
3. 建议北京地铁模版使用北京地铁基本车站，而不是上海地铁基本车站。
4. 上海地铁模版：浦江线闵瑞路和浦航路顺序错了，建议改一下
5. 上海地铁模版：15号线北边终点站应该是顾村公园，而不是祁华路，并在顾村公园站前有锦秋路站。
6. 模版：
![E7A6A589-3EB4-4334-9F7B-79F63B817759](https://user-images.githubusercontent.com/123239445/213868740-1ce0d28d-ba18-4d93-807f-961f26488978.jpeg)
实际：
![F697621E-3F52-4F51-9CC5-FC34A227D43A](https://user-images.githubusercontent.com/123239445/213868743-676f6d6b-f98f-44c4-bb7b-0321d9465f13.jpeg)
7. 模版：
![1D62BC0A-32CD-4812-A568-34366A84BC75](https://user-images.githubusercontent.com/123239445/213897628-c3d0ffe1-1c5d-4a9f-bc18-56c0f0dccedb.jpeg)
实际：
![C88F67D6-544A-4E61-A25F-C392D15D2582](https://user-images.githubusercontent.com/123239445/213897630-7c8d750d-83f1-4b05-b92b-026208b3020f.jpeg)
希望原作者可以采纳！

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与建议，有关您提到的建议现回复如下：

1. 北京地铁换乘站有点向上偏移 -> 已在 #154 中修复。
2. 建议加一个北京地铁线路标识 -> 见 #148 ，预计在下个月更新。
3. 建议北京地铁模版使用北京地铁基本车站，而不是上海地铁基本车站。 -> 期待贡献者提交新的北京线路图模板，此模板上周刚进行过更新，而北京地铁普通车站晚于模板合入时间更新。
4. 上海地铁模版：浦江线闵瑞路和浦航路顺序错了，建议改一下 -> 已在 #156 中修复。
5. 上海地铁模版：15号线北边终点站应该是顾村公园，而不是祁华路，并在顾村公园站前有锦秋路站。 -> 已在 #156 中修复。
6. 上海地铁模版与现实不一致部分 -> 算是另一个平行世界的小彩蛋吧，是预期之中的事情。

如有任何未尽事宜，欢迎reopen issue并comment。
