### ISSUE TITLE
导入项目后广州地铁换乘站出了问题

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#155]
我导入了我以前做的广州地铁的文件，换乘站变成了这样：
![51079C0B-D137-4C46-A634-FD5D993D1E73](https://user-images.githubusercontent.com/123239445/213909313-c71b5c32-62ff-4af2-938c-7daaa57c3d86.png)
点广州地铁换乘站之后会这样：
![4E841547-814B-4907-B392-C92F1EAA053C](https://user-images.githubusercontent.com/123239445/213909333-4dc2b026-3362-4594-b07d-0dca7a62c5fc.png)
广州地铁模版也发生了同样的事情：
![1A911CA2-539B-484F-ABF7-9CC7C1CA44AB](https://user-images.githubusercontent.com/123239445/213909357-1aab1c36-c89b-4126-bace-154b86031321.png)
广州地铁换乘站出问题了，谁快来修一下！
（现在新加的换乘站似乎没问题，但我不想重做！😢）

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，此问题已被修复 #153，很抱歉前几天推送的更新造成了这样的问题，您可以稍后重新在1.1.12版本中导入您的项目，谢谢
