### ISSUE TITLE
UAT测试

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#161]
刚刚我试了一下RMP2，总体还是蛮不错的，以下有几个建议：
- 左侧菜单栏没有了上海以及广州地铁的出站换乘的线路类型，建议把它们放回去，更方便一些。
- 建议加一个磁浮线的线路类型（如果可以的话，把磁浮线的标志换成彩色的）

一些问题：
下载图片后，出站换乘和铁路线路莫名消失了：
![image](https://user-images.githubusercontent.com/123239445/215075374-35d1d6b8-a76d-4ce4-8ecd-40cedac948eb.jpeg)
![image](https://user-images.githubusercontent.com/123239445/215075400-91307c83-30d1-4c9e-b6ba-a6b58bdd28dc.jpeg)
![image](https://user-images.githubusercontent.com/123239445/215075416-61e7f981-c4ed-4ce1-aa1a-c99579ff8545.jpeg)
![image](https://user-images.githubusercontent.com/123239445/215075689-0faa7870-6f86-4c3e-8b17-406380673ee9.jpeg)
北京地铁有轨电车线路莫名变成了普通线路：
（制作时）
![image](https://user-images.githubusercontent.com/123239445/215075813-521020a5-e661-4426-8b53-731b1c148464.png)
（导出后）
![image](https://user-images.githubusercontent.com/123239445/215075925-9f334a2b-dbc6-431e-8f57-91cfde212556.png)

**Comment by BadHunyun** [comment]
同样的，我遇到了第二个问题，如图：
![QQ图片20230127201632](https://user-images.githubusercontent.com/83549585/215085274-91ec2f53-8d80-4182-90bc-cfa5c6c46eff.png)

**Comment by thekingofcity** [comment]
嗨，感谢您的支持与建议，关于提到的问题回复如下：

> 左侧菜单栏没有了上海以及广州地铁的出站换乘的线路类型，建议把它们放回去，更方便一些。

新版本中只在左侧工具栏中提供不同线路路径的工具，线路样式的选择只会在右侧详情栏中：
![image](https://user-images.githubusercontent.com/3353040/215121289-229be95b-47c4-4550-a44a-866b2fd5f98f.png)
这是由于新版本使用两种类型确定一种线段，如果展示所有的路径和样式类型的组合又过于臃肿，所以默认了所有线段都是纯色样式，这也是一张线路图中理论上用到最多的样式，如果需要其他样式则需要二次选择。

> 建议加一个磁浮线的线路类型（如果可以的话，把磁浮线的标志换成彩色的）

这个在新版本的计划中，不过由于一些技术问题延期了，不出意外最近会上线的。

> 下载图片后，出站换乘和铁路线路莫名消失了

问题已复现并确认，将会在之后修复。

**Comment by thekingofcity** [comment]
嗨，下载图片时线段消失的问题已修复并上线在UAT环境中，欢迎继续测试。与磁悬浮有关的讨论和进度可以参见 #163。
