### ISSUE TITLE
车站站名与图标间空隙过大

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmp#162]
北京地铁/上海地铁普通车站出现了车站站名与图标之间空隙过大的问题（仅当站名在车站上方时），下图为例
<img width="41" alt="image" src="https://user-images.githubusercontent.com/120014893/215084883-a37e77bd-d68c-4897-88e3-65fdbeca0f35.png">
北京8号线平西府站
<img width="145" alt="image" src="https://user-images.githubusercontent.com/120014893/215084915-26bd2f5a-56f7-4667-81df-52289a18635b.png">
编辑器绘制的地铁图截图

**Comment by thekingofcity** [comment]
嗨，感谢您的支持与建议，此问题之前已被发现不过尚未开issue，最近会着手解决。

**Comment by aaronyz2007** [comment]
顺带提一句，这个问题也出现在了RMP 2中，并且英文站名行数越多，站名与车站之间的空白越大

**Comment by aaronyz2007** [comment]
又发现一个问题，希望可以一起处理
<img width="187" alt="image" src="https://user-images.githubusercontent.com/120014893/215654639-6e321bdf-a363-4580-9bc4-8e894f8f0def.png">
如图，当车站名位于车站下方时，如果中文站名有换行，车站图标会被遮盖，当中文站名≥3行，车站会被完全覆盖

**Comment by aaronyz2007** [comment]
<img width="160" alt="image" src="https://user-images.githubusercontent.com/120014893/215654864-296d9a5b-3167-4f66-a588-4e72e02c9957.png">
举个栗子↑

**Comment by thekingofcity** [comment]
嗨，此问题已被修复并上线，欢迎在`2.0.10`及之后版本体验。

![image](https://user-images.githubusercontent.com/3353040/217283359-4e061c29-f0ef-4f81-9253-2921ab5a46f5.png)
