### ISSUE TITLE
北京地铁有轨电车线路的问题

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#164]
![image](https://user-images.githubusercontent.com/123239445/215310516-6a8f78c2-6a3e-4c8c-9d64-1442d56b0554.jpeg)
![image](https://user-images.githubusercontent.com/123239445/215310519-c8b6373c-5fef-47ff-aeae-369bc650f2a5.jpeg)

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/215327622-0d0c0b72-bfe7-41bd-b712-8410d3dd1f90.png)

嗨，感谢汇报问题，它已被修复并上线。
