### ISSUE TITLE
北京模板内的一些差错

### ISSUE THREAD

**Issue by NNTR** [railmapgen/rmp#169]
嗨，又是我，刚才在看北京模板时又发现了几个问题，比如：
[
![image](https://user-images.githubusercontent.com/123074394/215915776-c8767b87-ff58-4ef9-bb29-e58ea4cfa4df.png)
](url)
1.暂缓开通标识设在右上角时，离得是比较远的。（其实这还比较好，西土城让人第一眼看像学院桥的名称）
2.清河小营桥在两个90度垂直线段间有一点点小误差，没有完全在俩线段中间

![lwt](https://user-images.githubusercontent.com/123074394/215917201-f3df0dbb-111e-4973-9205-0d3c377d3dcf.png)
北铁应该再改版了，昌平南段开通了
以上就是我全部的内容，望整改，谢谢！

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与建议。

1. 暂缓开通标识设在右上角时，离得是比较远的。 -> 见 #162，这是一个已知问题。
2. 清河小营桥在两个90度垂直线段间有一点点小误差，没有完全在俩线段中间。 -> 这也是个已知问题，关于在圆弧上车站包括mtr机场站，目前没有好的解决办法，让用户定义复杂曲线也不合适，可能近期都会是这样一个不完美的状态。
3. 北铁应该再改版了，昌平南段开通了。 -> 欢迎修改模板后开issue提交，也欢迎将所有非换乘车站改为北京地铁基本车站。
