### ISSUE TITLE
北京地铁站名的问题

### ISSUE THREAD

**Issue by NNTR** [railmapgen/rmp#171]
北铁站名网上讨论比较猛，昨天我去看了一下，参考了一些资料，结合了一下
[新建 DOCX 文档.docx](https://github.com/railmapgen/rmp/files/10564029/DOCX.docx)
不知开发者们不知有没有讨论过这些？希望能赏脸看一下文档

**Comment by thekingofcity** [comment]
嗨，如果大部分内容不是原创的话，最好带上原作者的信息以及原帖地址哦，因为我好像在知乎上看到过基本一样的内容。另，这些内容对于rmp开发无任何建设性帮助，只是提出了问题并没有标注应该实现的标准，更不要说北京地铁可能自身都没有统一，在这种情况下我只会选择一种存在过的情况实现而忽略其他的。cc @52PD

**Comment by wongchito** [comment]
我想提一下我個人就範本（包括RMP及RMG範本）的想法。

RMG（及RMP）的開發初衷，是提供一個自由創作路線圖（線網圖）的平台。我們儘可能地開發官方圖的所有元素，你可用其來復刻官方圖，亦可用來製作任何你所設計的路線。

而範本的設立，是為了向用家展示我們已支援哪些功能，同時亦為各位的創作**提供一個起始點**。這些範本不一定要與官方圖同步更新，它**可以停留在歷史上某一個時間點**，以展示某些官方不再使用、但我們仍然提供的功能。例如於RMG範本中，廣州地鐵3號線的範本保留了北延線直通運轉的提示，港鐵東鐵綫的範本繼續在終點站牌中使用「東鐵綫往xx」的寫法。當然，我們不會容許不正確，或從未在現實中存在過的內容。

回到閣下所提出的站名拼寫問題，RMP在開發中已提供自訂英文名的功能並支援任何字元（顯而易見的），而當前的範本亦在平台提供的功能範圍下，儘可能地接近官方圖。就地鐵方不停變更站名拼寫的情況，我們作為開發者沒有過多精力去跟從及作出變更 - 當然我們歡迎各位用家提供最新的範本😄。

最後，亦感謝閣下在RMG及RMP範本所作出的貢獻。我們亦歡迎各位對於上述內容提出建設性的意見。🙏🏻

**Comment by NNTR** [comment]
大部分来源于https://weibo.com/u/2994833630,往下翻翻。 @thekingofcity

**Comment by 52PD** [comment]
这个我好像在微博上读过来着😂

**Comment by NNTR** [comment]
《也可以说是全部》

**Comment by NNTR** [comment]
《也可以说照抄原文》😂
