### ISSUE TITLE
修正北京线路图模板

### ISSUE THREAD

**Issue by NNTR** [railmapgen/rmp#182]
这是最新版的北铁模板，主要修复：
1.西郊、亦庄T1线的线路样式
2.暂缓开通的虚线形式
[新建 WinRAR ZIP 压缩文件.zip](https://github.com/railmapgen/rmp/files/10720669/WinRAR.ZIP.zip)

**Comment by NNTR** [comment]
对不起，发错了，这是新版的：
[Uploading 新建 WinRAR ZIP 压缩文件.zip…]()

**Comment by NNTR** [comment]
还有两个问题：
![image](https://user-images.githubusercontent.com/123074394/218422120-9fbea00e-869f-457a-8142-6906d83b1e69.png)
9号线底色为黑
![image](https://user-images.githubusercontent.com/123074394/218422433-67488ce3-f259-422d-96d6-fb6e6a5b0b2e.png)
![image](https://user-images.githubusercontent.com/123074394/218422568-0c744600-af8f-4559-acd5-37d99e7e4ce3.png)
原版与原图的名称位置并不相符
望我的建议对RMP有帮助！

**Comment by thekingofcity** [comment]
嗨，感谢你对项目的支持与贡献 :)

> 对不起，发错了，这是新版的：
> [Uploading 新建 WinRAR ZIP 压缩文件.zip…]()

这个文件没有正确的上传。你需要等文件名没有Uploading时再点击comment。

> 9号线底色为黑

有关颜色的问题欢迎参考 railmapgen/rmg-palette 的内容更新。


> 原版与原图的名称位置并不相符

我认为模板不是1:1完美复刻的，这些细节对于用户了解北京地铁和使用项目没有额外帮助或困扰，所以不会特意，当然仍然欢迎你提交优化后的模板。

**Comment by NNTR** [comment]
[新建 WinRAR ZIP 压缩文件.zip](https://github.com/railmapgen/rmp/files/10741558/WinRAR.ZIP.zip)

**Comment by NNTR** [comment]
这是最新的

**Comment by thekingofcity** [comment]
嗨，模板已更新并上线，再次感谢您的贡献。
