### ISSUE TITLE
关于对羊角风的一点建议

### ISSUE THREAD

**Issue by 5WLAN** [railmapgen/rmp#189]
![1676732036645](https://user-images.githubusercontent.com/122973028/219872430-622c2589-2965-4140-b5b0-a216e02adbdf.png)
第一点：增加三站以上换乘，未来城市中会有五站换乘的局面
![1676732337718](https://user-images.githubusercontent.com/122973028/219872691-541e8e71-5711-477a-b139-6b7758d272b5.png)
第二点：更新机场、城轨、火车站、港口等交通枢纽的样式，现在的5个不够统一化
![1676733610448](https://user-images.githubusercontent.com/122973028/219873803-d0993566-23a5-44e5-94a9-9922d0bba209.png)
第三点：调整字体大小设置，上下居中

此发言仅代表个人意见与提出的建议

**Comment by 5WLAN** [comment]
增加：
第四点：增加换乘车站文字的方位布局，目前只有左上、左下、右上、右下（东北、东南、西北、西南）四个方向，增加上、下、左、右（东、南、西、北）四个方位。增加每个方位的偏差，以免出现文字互相遮挡、站台遮挡文字，文字遮挡线路的情况
第五点：换乘站会遮挡文字，文字应该位于图层上方
第六点：站台大小缩放，便于自动驾驶系统与有轨电车的布局

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议，以下是回复：

1. **增加三站以上换乘，未来城市中会有五站换乘的局面**
  关于广州地铁换乘车站的讨论见 #92。目前由于三线换乘的图标优化和算法生成的四五线冲突，暂时没有进一步更新的计划。欢迎在那里提出有建设性意见的讨论 :)
2. **更新机场、城轨、火车站、港口等交通枢纽的样式**
  这些图标是拷贝自rmg项目中的，rmp目前没有新增额外图标的计划，目前的开发重心是在功能和更多城市风格的实现上。图标由于可以轻松的在svg编辑器中制作，也欢迎感兴趣的用户自行制作并开issue授予rmp使用的一切权力，我会尽一切努力合入静态的图标资源。
3. **调整字体大小设置，上下居中**
  近期会有针对此的修复，见 #194。
4. **增加换乘车站文字的方位布局**
  近期会有针对此的修复，见 #195。
5. **换乘站会遮挡文字，文字应该位于图层上方**
  换乘站文字已在图层上方，方便附图进一步说明吗？
6. **站台大小缩放，便于自动驾驶系统与有轨电车的布局**
  近期会有针对此的更新，见 #142。

以上

**Comment by 5WLAN** [comment]
![1677346134710](https://user-images.githubusercontent.com/122973028/221371015-9b48f40d-be04-4d30-bd77-ec3281682bcf.png)
回复：这个是问题五的，文字会被换乘站覆盖

**Comment by 5WLAN** [comment]
增加：
第七点：增加负数偏移
![1677426397734](https://user-images.githubusercontent.com/122973028/221420915-1e7601da-8c29-4609-93a5-adbea37b7613.png)

**Comment by thekingofcity** [comment]
5. **换乘站会遮挡文字，文字应该位于图层上方**
  这个是预期之中的情况，这样的密度和设计并不在考虑之中。
7. **增加负数偏移**
  负数时支持的，欢迎在数字前增加`-`以体验。

如有任何未尽事宜，欢迎reopen此issue并附上更多信息。

**Comment by 5WLAN** [comment]
增加：
第八点：添加字体颜色

**Comment by 5WLAN** [comment]
添加：
第九点：换乘站文字在上面或下面的时候间隙过大
第十点：当重新打开后车站文字在文字超过3个的时候会缩小
