### ISSUE TITLE
金山铁路最后两站顺序错误

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#193]
上海地铁模版中，金山铁路的 “金山园区” 和 “金山卫” 顺序错了。
<img width="1280" alt="Screenshot 2023-02-20 at 08 01 57" src="https://user-images.githubusercontent.com/123239445/219983565-c95633af-ddaf-4c88-b4a9-e01e9494ff66.png">

**Comment by thekingofcity** [comment]
嗨，感谢你对项目的支持与贡献，模板已更新并上线。
