### ISSUE TITLE
北京地铁图标更新

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmp#197]
最近发现上次我做的北京地铁换乘站（哪个Issue懒得找了）的圆框因为代码问题变成了多边形😂，再加上最近发现在考虑到RMG的线条宽度下的车站图标对于北京地铁来说有一点太大了。

再加上今年16号线南延后北京地铁也有了自己的出站换乘标。

所以我就干脆全部重做了一遍🌝

以下是更新内容：
- 普通车站（比起上海地铁的圆圈（旧版）图标更小，且边框更细）：
![Beijing Subway Standard](https://user-images.githubusercontent.com/98044618/220962356-2a626540-dd05-4c58-ac17-831a932b51f4.svg)
- 普通换乘站（修正了多边形边框问题）：
![Beijing Subway Within-Station Interchange](https://user-images.githubusercontent.com/98044618/220962361-1a30221e-1c93-4e6d-b696-0b9e99a470fa.svg)
- 出站换乘站（中间的换乘标识比普通换乘的颜色更浅）
![Beijing Subway Out-Of-Station Interchange](https://user-images.githubusercontent.com/98044618/220962352-71d08b40-de78-44bf-a6e6-5b24f385aac6.svg)

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与贡献。图标资源已合入项目中并上线 🎉

![image](https://user-images.githubusercontent.com/3353040/221192997-ef67416c-b722-435c-a9e8-caa0f6b9792c.png)
