### ISSUE TITLE
广州地铁线路图标文字向上偏移

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#198]
<img width="1280" alt="Screenshot 2023-02-24 at 07 44 33" src="https://user-images.githubusercontent.com/123239445/221057197-f9cce2a9-cca6-4380-8ccb-40107b40657b.png">

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。此问题已被修复并上线 :)

**Comment by 28yfang** [comment]
依然有问题😬![image](https://user-images.githubusercontent.com/123239445/221339933-403562fd-88ab-4f2c-959c-408624fb048a.jpeg)

**Comment by thekingofcity** [comment]
嗨，这是一个safari上特定的bug，已修复并上线，欢迎在确认问题解决后close此issue :)
