### ISSUE TITLE
广州换乘站车站名称距离车站太远

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#199]
<img width="1280" alt="Screenshot 2023-02-24 at 12 13 06" src="https://user-images.githubusercontent.com/123239445/221090218-70cfa0d8-95aa-4294-9573-d524850eb287.png">
<img width="1280" alt="Screenshot 2023-02-24 at 12 13 09" src="https://user-images.githubusercontent.com/123239445/221090229-b64808cf-d246-4fea-bfb6-1a27090f59fe.png">
<img width="1280" alt="Screenshot 2023-02-24 at 12 13 16" src="https://user-images.githubusercontent.com/123239445/221090231-70d85430-0978-4bfc-9976-5debd1f13175.png">
<img width="1280" alt="Screenshot 2023-02-24 at 12 13 18" src="https://user-images.githubusercontent.com/123239445/221090235-24269c73-c291-428f-946a-83f6485e04ce.png">

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。

这是预期之中的现象，如果与官方实现有显著区别，欢迎提供带有数据标注的间隔，以及与现有的差别。如有任何未尽事宜，欢迎reopen此issue。
