### ISSUE TITLE
北京地铁线路图标大小问题

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#200]
北京地铁线路图标过大。建议缩小至广州地铁图标大小。
<img width="134" alt="Screenshot 2023-02-24 at 13 42 24" src="https://user-images.githubusercontent.com/123239445/221101310-9c7afdbd-8c2a-427c-8b9f-a9ea04821c0c.png">

**Comment by 28yfang** [comment]
似乎还是很大😂![image](https://user-images.githubusercontent.com/123239445/221218339-d2a236dc-71a2-4045-84be-0d04bd065aee.jpeg)

**Comment by thekingofcity** [comment]
`2.1.7` 应该已经上线了，欢迎确认版本后再体验 :)
