### ISSUE TITLE
上海地铁模板颜色还没更新

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp#202]
调色板中上海地铁颜色已更新，但是rmp（rmg也有此问题）模板没有 要手动点击线条选择新颜色来更新
红色圈里线段为新颜色，绿色圈里线段是旧颜色
![image](https://user-images.githubusercontent.com/106796352/221334198-3b57f589-0800-4880-b169-e187f0102864.png)

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。新颜色已经更新在`2.1.8`版本中，重新加载模板即可看到更新后的模板 :)
