### ISSUE TITLE
左侧工具栏不能适配屏幕

### ISSUE THREAD

**Issue by rainydew** [railmapgen/rmp#208]
![image](https://user-images.githubusercontent.com/40389473/222201005-32790cfa-0f78-4aa9-b680-5376289db5c3.png)
发现升级以后，色版没了。F12看了下，色版元素还在，但是超过了我屏幕的最大高度
我1920*1080的分辨率，并不算少= =

**Comment by rainydew** [comment]
考虑下，这种情况应该分成两列

**Comment by rainydew** [comment]
暂时在F12下删掉了两个元素以后，色版浮上来了……

**Comment by thekingofcity** [comment]
嗨，通过鼠标滚轮应该是可以滚动左侧工具栏的。您也可以访问 [UAT](https://uat-railmapgen.github.io/rmp/) 来测试最新的带有伸缩功能的工具栏 :)

**Comment by rainydew** [comment]
感谢，现在这个版本好了

我的鼠标滚轮的作用是缩放图片，不知道是不是设置的缘故
