### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by BinguoCity** [railmapgen/rmp#217]
1.请问能不能加入站距水平均分/垂直均分的功能，这样未来遇到线路中间设新站的情况才比较好及时调整
2.请问能不能加入广州地铁的四线或以上的换乘站
3.请问能不能将保存的图片也可以为深色模式

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议，现回复如下：

1. 请问能不能加入站距水平均分/垂直均分的功能，这样未来遇到线路中间设新站的情况才比较好及时调整
  这个高级功能不会在近期实现。这主要是由于当前图的边是有向的，而用户制作时不会保证从A到B的顺序，这导致了在遍历获取车站时会有问题。另一个是当车站有多条线路时且有环时，无法计算出正确的结果，如果仅适用于单线车站间的话范围又过窄了。我认为这个需求更适合在拖动时由辅助线来帮助更好，然而这个功能是一个远期规划，需要您的耐心等待。
2. 请问能不能加入广州地铁的四线或以上的换乘站
  见 #92，下一步打算更新程序生成的四线及以上换乘站
3. 请问能不能将保存的图片也可以为深色模式
  见 #218，更新即将上线。

以上
