### ISSUE TITLE
在修改了Text的白色描边后，上海模版中的Text变小了

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#219]
<img width="1280" alt="Screenshot 2023-03-06 at 11 44 33" src="https://user-images.githubusercontent.com/123239445/223015136-25df88fd-246d-4a8d-95b4-f856fb5da5e5.png">
<img width="1280" alt="Screenshot 2023-03-06 at 11 44 41" src="https://user-images.githubusercontent.com/123239445/223015143-0af3914f-71ad-4ba8-9107-be243654d615.png">

**Comment by thekingofcity** [comment]
嗨，这是预期之中的现象，需要您手动增大text字号才能与原来相同 :)
