### ISSUE TITLE
导出图片问题

### ISSUE THREAD

**Issue by ple-kid** [railmapgen/rmp#220]
DIY些线路，导出json文件没有问题，但是导出图片就有问题了，选择导出png，点击下载就没反应了（下载了新浏览器后，也只能导出png一次，第二次后也是点击下载没反应了）

**Comment by thekingofcity** [comment]
嗨，感谢反馈的问题，方便将您的json文件和浏览器操作系统版本分享一下吗？我需要本地复现一下是否有同样的问题以修复。

**Comment by 28yfang** [comment]
其实这是所有iPhone/iPad都有的问题，是文件过大导致的

**Comment by ple-kid** [comment]
感谢，我的问题已经解决，粘贴文字过程中遇到了不可显示字符
![image](https://user-images.githubusercontent.com/58095879/223435925-ad0b544d-2f40-415f-a54a-cc7b26efc06b.png)

![image](https://user-images.githubusercontent.com/58095879/223436356-deceed2c-5662-4990-a3f7-c2ce769f9bf4.png)
