### ISSUE TITLE
北京新模板

### ISSUE THREAD

**Issue by NNTR** [railmapgen/rmp#221]
修正：1.二里桥暂缓出站换乘 2.线路标志样式
[新建 WinRAR ZIP 压缩文件.zip](https://github.com/railmapgen/rmp/files/10908197/WinRAR.ZIP.zip)

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与贡献。在检查内容的正确性后我们将合入此更新。

cc @52PD

**Comment by NNTR** [comment]
啊，好像漏了9号线
[WinRAR.ZIP.zip](https://github.com/railmapgen/rmp/files/10918765/WinRAR.ZIP.zip)

**Comment by 52PD** [comment]
[bjsubway_fixed.json.zip](https://github.com/railmapgen/rmp/files/10926811/bjsubway_fixed.json.zip)

我稍微调整了一下，有些两线平行时的换乘站没接到对应车站图标上的问题（事实上你没必要在换乘站图标下面藏别的节点，像两线平行的换乘站你可以直接给线条（只有转角线条能改）设起始点/结束点偏移）我都解决掉了，还有就是普通车站图标仍然用的是上海地铁的问题我也修复了。

至于车站站名堆叠到别的元素的这个问题我就暂时没弄了，因为如果要改这个的话那已经相当于整个模版的50%要推倒重做了。

**Comment by thekingofcity** [comment]
感谢 @52PD 的检查与修正，新版本已经上线，欢迎重新加载模板体验。
