### ISSUE TITLE
Fix removing all classes in download

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#228]
我在写APM线车站名是用的Text
编辑时：
<img width="1280" alt="Screenshot 2023-03-11 at 14 31 00" src="https://user-images.githubusercontent.com/123239445/224469150-1ee4cd84-5472-4339-9505-473e2753dcec.png">
下载后：
<img width="1280" alt="Screenshot 2023-03-11 at 14 28 08" src="https://user-images.githubusercontent.com/123239445/224469176-de9b8ddc-57f4-4147-84c6-b394198ee121.png">

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题。此问题已确认且修复已上线 :)
