### ISSUE TITLE
关于目前北京地铁车站点和线路名与RMP现有元素的一些不协调问题

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmp#238]
@thekingofcity 如标题所说，目前由于RMG的大部分元素都是基于上海地铁设计的，因此在使用北京地铁素材的时候难免会出现一些各元素不协调的问题：
第一点：北京地铁的数字线路名标识的圆角矩形背景长度是统一长度的，同时该长度也是文字名线路标识的圆角矩形最小长度与数字名线路标识的相同
![beijing_subway_line_badge_compare](https://user-images.githubusercontent.com/98044618/226072333-bdff2cfa-c728-499e-b90f-bb0f2b83f750.jpg)
如上图（上图每个对照标识中第一个为北京地铁官方线路图中的线路名标识，第二个为RMG生成的北京地铁线路名标识），这里我量了一下（已按比例缩放），北京地铁的线路的标识背景中，数字线路名无论是一位数还是二位数应均为32.84375x16（长32.84375像素，宽16像素）的圆角矩形，此外文字线路名的标识背景最小长度也应为32.84375像素（之所以是最小长度是因为要考虑到首都机场线和大兴机场线这两个标识背景加长的）

此外，我在浏览器的开发模式里面试了一下，发现如果在不改变英语字间距的情况下照上面这种改会出现另一个问题：两位数线路的文字无论如何都会超出矩形背景范围，所以对于北京地铁的话英语字间距也得缩小才行（查了一下，css是有调整字间距的变量的）

第二点，关于当前线条粗细的问题。
![beijing_subway_line_compare](https://user-images.githubusercontent.com/98044618/226074300-a222d381-8713-413f-8f3c-74f5196e0291.jpg)
之前发了个issue（#197 ）调整了北京地铁各车站图标的大小，结果等正式发布后才发现这么一调整文字大小又过大了。所以我就重新量了一下北京地铁的线路线条宽度（已按比例缩放），也就是说在考虑不改变当前车站名文字大小的情况下，北京地铁的线路线条宽度应该为9像素而不是RMG中针对上海地铁风格的6像素。

如上图，车站名左侧的部分为RMG现有的线路线条，右侧则为北京地铁官方线路图的线路线条。

然后考虑到针对北京地铁的线路线条加粗后现有的北京地铁车站图标肯定就变小了，所以我这里就全部更新了一遍（顺带调整了换乘站的箭头图标使其更符合北京地铁官方线路图上的风格）:
- 普通车站：
![beijing_subway_standard_station](https://user-images.githubusercontent.com/98044618/226076069-f22900e4-b886-42fc-aa4f-c9e52d2ba252.svg)
- 未开通车站：
![beijing_subway_unopened_station](https://user-images.githubusercontent.com/98044618/226076074-9f30b502-b9f6-4b01-ae7d-ca73afb16b52.svg)
- 站内换乘车站：
![beijing_subway_enterchange_station](https://user-images.githubusercontent.com/98044618/226076080-b5904679-1788-446b-b1b3-d323f928ec7c.svg)
- 出站换乘车站：
![beijing_subway_out_of_station_interchange_station](https://user-images.githubusercontent.com/98044618/226076076-b2d4dde5-0c4d-4817-8b0b-3a28fb20c164.svg)

========
额外补充：与上海地铁的线路线条不同，北京地铁的线路线条是有白色描边的：
![beijing_subway_line_stroke_example](https://user-images.githubusercontent.com/98044618/226076142-ddc1f340-6672-4022-abae-001dec097ace.jpg)

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。第一点会进行相应的更改，只是细节的微调可能需要一些时间，涉及到字号在不同情况下的变更。不过对于第二点来说，RMP目前希望锚定线条的宽度为5，而其他的元素根据此值进行缩放。除非有无法适应的情况，我应该不会改变线条的宽度（河流等非铁路线条除外）。

**Comment by 52PD** [comment]
哦哦，不过刚刚检查一下，北京地铁的元素在等比缩放到线条宽度为5后确实会有一点不适应状况了（这里我用RMG做示例的两站间距与北京地铁官方线路图的相同）：
![beijing_subway_station_name_compare](https://user-images.githubusercontent.com/98044618/226113804-e1a56c8a-7f21-4c11-be5a-766d0d1f28a8.jpg)
如上图（左图为官方线路图，右图为RMG生成的），在线条宽度车站图标半径与北京地铁的相同的状况下，RMG生成的图的文字就全挤到一起了

**Comment by thekingofcity** [comment]
嗯嗯，关于车站文字的区别，方便在开发者工具里简单调试一下字号然后提供一个比较符合比例的数值吗？方便我直接替换现有数字 :)

**Comment by 52PD** [comment]
> 嗯嗯，关于车站文字的区别，方便在开发者工具里简单调试一下字号然后提供一个比较符合比例的数值吗？方便我直接替换现有数字 :)

算出来了，以下为所有要调整的元素信息：
- 车站中文名：16像素 -> 10像素
- 车站英文名：10像素 -> 6.2像素
- 线路名牌缩放：1.5倍 -> 1.0625倍
- 线路名牌中文名/“号线”两字：8像素 -> 7像素

然后算了一下数字线路名中数字编号的字间距应为：```letter-spacing: -1px```

至于线路牌的长宽，由于我之前没注意到RMG里面是有1.5倍缩放的，所以之前算的不太准确。这次重新算了一下，数字线路名牌子的长度和文字线路名牌子的最小长度统一成当前的32像素就行（高度不变）

**Comment by thekingofcity** [comment]
> 至于线路牌的长宽，由于我之前没注意到RMG里面是有1.5倍缩放的，所以之前算的不太准确。这次重新算了一下，数字线路名牌子的长度和文字线路名牌子的最小长度统一成当前的32像素就行（高度不变）

长宽的1.5倍缩放我会去掉的，这不利于以后的维护。

**Comment by thekingofcity** [comment]
![image](https://github.com/railmapgen/rmp/assets/3353040/e7cf6b19-f5a6-44fb-97fe-55e135303320)

![image](https://github.com/railmapgen/rmp/assets/3353040/16a5d2a5-0318-427c-ada3-35313923bc60)

我将在 #321 close 后在UAT上上线此版本，敬请期待 :)
