### ISSUE TITLE
对手机版不太友好

### ISSUE THREAD

**Issue by SMGDHHYF** [railmapgen/rmp#239]
我经常用手机，最近绘制器发布后我第一时间去用了，但是对手机版不太友好，如图

**Comment by SMGDHHYF** [comment]
![Uploading 41441B5C-465B-43E6-8675-0C359E78BE61.png…]()

**Comment by thekingofcity** [comment]
嗨，图片并未上传成功，需要您等待上传完成即Uploading字样消失后再点击comment回复 :)

**Comment by thekingofcity** [comment]
由于长时间没有回复而关闭。
