### ISSUE TITLE
Polygon node

### ISSUE THREAD

**Issue by 662926** [railmapgen/rmp#240]
1.希望增加全国著名湖泊（如西湖）和湖泊通用模型
2.优化河流画法，不需要连接两点绘制或隐藏连接点

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与建议，以下是回复：

对于您的第一个建议，增加全国著名湖泊（如西湖）和湖泊通用模型，我们非常理解您的需求。然而，这个功能相对复杂，涉及到大量的数据收集和处理工作。目前我们的项目资源和开发时间有限，可能无法立即实现这一功能。我们会将您的建议记录下来，并在将来的版本中逐步进行考虑和实现。

关于您的第二个建议，优化河流画法，不需要连接两点绘制或隐藏连接点，我们需要您提供更详细的说明。请您详细描述您希望实现的效果和具体需求，以便我们更好地理解您的意图并作出相应的优化。您可以在此issue中提供进一步的信息，或者通过其他方式与我们联系。

以上。

**Comment by 662926** [comment]
![2](https://user-images.githubusercontent.com/128211210/226109761-5b295da5-243e-47cb-88b1-0b13ce17bb13.png)
河流的两端有点，不够美观，希望可以隐藏，效果如下图

**Comment by 662926** [comment]
![3](https://user-images.githubusercontent.com/128211210/226109853-235f14cc-f94d-47d6-b8f4-4a85f5c969b0.png)

**Comment by thekingofcity** [comment]
嗨，河流两端的控制端点在导出图片时会默认隐藏，在其他时候显示是必要的为了方便控制线条走向。

**Comment by 662926** [comment]
好的，感谢

**Comment by rainydew** [comment]
是不是理解为，湖泊 = 任意底色的封闭多边形工具，可能支持圆角这样

**Comment by aaronyz2007** [comment]
希望可以加入湖泊/海洋的模型，很多沿海城市的地铁图都有标注海洋（如上海、香港、青岛、澳门、厦门等）
对于海洋，可以增设蓝色背景，用封闭多边形工具绘制陆地部分
对于湖泊就像rainydew所说的那样就可以

**Comment by thekingofcity** [comment]
Let's do this after the support from #580

**Comment by thekingofcity** [comment]
This feature can now be fully supported with master nodes introduced in 5. See railmapgen/rmp-designer#1 for issue tracking.
