### ISSUE TITLE
90° rotate perpendicular path

### ISSUE THREAD

**Issue by 662926** [railmapgen/rmp#241]

**Comment by thekingofcity** [comment]
嗨，需要您提供详细的文字或图片说明我才能理解此issue的内容，否则我将关闭此issue。

**Comment by 662926** [comment]
![1](https://user-images.githubusercontent.com/128211210/226109571-dfcc58f4-764c-42bf-a03d-c5888a1090b2.png)

**Comment by 662926** [comment]
类似90度线，但有倾斜角度

**Comment by thekingofcity** [comment]
您的意思我了解了，由于此功能之前未考虑过但确有增加的必要，我会在接下来的时间中思考实现方式并更新，感谢您对项目的支持与建议 :)

**Comment by LittleLing03** [comment]
+1

**Comment by Furness804** [comment]
#322 - Unsure if this is an example of what I meant with 45- and 180-degree turns.

**Comment by Furness804** [comment]
> > #322 - Unsure if this is an example of what I meant with 45- and 180-degree turns.
> 
> Do you mean something like:
> 
> * 45 sharp angle
>   ```
>   ---
>     ╱
>    ╱
>   ```
> * 180 turn round
>   ```
>   ---┐
>   ---┘
>   ```
> 
> Is it possible to provide a draft image if I'm understanding it wrong?

Yes, that is what I mean.
