### ISSUE TITLE
希望文本能旋转

### ISSUE THREAD

**Issue by 662926** [railmapgen/rmp#244]

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。想确认一下旋转指的是rotate还是vertical orientation。

**Comment by 662926** [comment]
rotate

**Comment by thekingofcity** [comment]
有什么现实存在的城市使用了rotate的文字吗？我想根据这一情况判断此功能的优先级。

**Comment by 662926** [comment]
![Uploading IMG_20230320_144407.jpg…]()

**Comment by thekingofcity** [comment]
嗨，图片没有上传成功。可以等Uploading字样消失后再点击comment。

**Comment by 662926** [comment]
![IMG_20230320_144407](https://user-images.githubusercontent.com/128211210/226285117-3d665fe7-9fa6-4632-8d79-cc06a06eeb8e.jpg)

**Comment by thekingofcity** [comment]
嗨，我理解下来要实现此功能需要文字倾斜，颜色和旋转。然而由于此内容非地铁线路图核心（指车站和线段），此功能的优先级较低，预期要稍等一些时间才会有更新，感谢理解 :)

**Comment by 28yfang** [comment]
是的，这个功能柏林官方中需要。
![image](https://github.com/railmapgen/rmp/assets/123239445/5f149993-ea22-42f0-a8aa-47ee5e3ca573)

**Comment by thekingofcity** [comment]
嗨，感谢各位的等待。此功能即将上线，敬请期待 :)

![image](https://github.com/railmapgen/rmp/assets/3353040/e4431e9d-4575-4225-be1a-2cd058dfcd92)
