### ISSUE TITLE
关于北京地铁模版的问题

### ISSUE THREAD

**Issue by Gzline4-24hc** [railmapgen/rmp#245]
你好！在这里讲一下北京地铁模版的问题！
首先就是二里沟开通的问题（我不知道怎么上传照片）
在上周二里沟已经开通了，请你务必改一下
还有，大部份车站怎么名字都偏移了，看起来好怪，望京东都超出线路了。希望你们能改一下。

**Comment by langonginc** [comment]
我来看看。

**Comment by langonginc** [comment]
这大概是因为强行转为北京样式导致的

**Comment by langonginc** [comment]
我会在几天之内修复的

**Comment by Gzline4-24hc** [comment]
![121D43A0-36FC-4083-B66C-D75E1DCD5D30](https://user-images.githubusercontent.com/128379352/226513457-b7523395-f383-444e-bb43-b58eacc1e2f4.jpeg)
![D71261C3-D4CE-4C71-8A54-A8B6EE81B3D3](https://user-images.githubusercontent.com/128379352/226513465-618d3506-cf37-46db-b46b-ce97f14c668a.jpeg)
![6D94B456-F405-42A7-A2CC-387F148091B2](https://user-images.githubusercontent.com/128379352/226513469-a2498ef3-317e-4efb-aa42-0dd588dc94c1.jpeg)
![D33CE349-8F3D-4F2B-832D-79AE58C310D6](https://user-images.githubusercontent.com/128379352/226513471-d9988d3e-ba1c-463e-83e9-face68b2334b.jpeg)

**Comment by Gzline4-24hc** [comment]
还有，二里沟怎么没有开通啊
![3275B106-D5E1-4D76-9CCD-BC251BE34C22](https://user-images.githubusercontent.com/128379352/226513546-52873833-b088-4019-9237-e40c4236a65e.jpeg)

**Comment by Gzline4-24hc** [comment]
黑底的线路在北京地铁显示后的颜色是蓝色而并非黑色
![Uploading ADE84D59-2000-43E2-9360-F0C0EA52A571.jpeg…]()

**Comment by langonginc** [comment]
二里沟同时也会修复

但是您蓝色而非黑色的截图并不能看到，请您重新上传
