### ISSUE TITLE
导出不了图片

### ISSUE THREAD

**Issue by pengshan114514** [railmapgen/rmp#249]
导出图片时，点击下载，没反应

**Comment by thekingofcity** [comment]
嗨，方便分享一下存档让我在本地复现一下错误吗？仅凭您所提供的信息很难找到无法导出图片的原因 :)

**Comment by Gzline4-24hc** [comment]
我没有参与这个issue你们发邮件给我干嘛
________________________________
发件人: thekingofcity ***@***.***>
发送时间: 2023年3月22日 13:53
收件人: railmapgen/rmp ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [railmapgen/rmp] 导出不了图片 (Issue #249)


嗨，方便分享一下存档让我在本地复现一下错误吗？仅凭您所提供的信息很难找到无法导出图片的原因 :)

―

**Comment by thekingofcity** [comment]
> 我没有参与这个issue你们发邮件给我干嘛

watch此项目会接收到此项目所有新动态的提醒。

**Comment by YumuFalcon** [comment]
emmm我也导不出图片，就是点导出图片后，点下载长时间无反应，下载列表也没有下载任务

**Comment by thekingofcity** [comment]
嗨，已修复一个可能导致导出图片失败的问题。确认版本为2.5.5后重试导出操作已确认问题是否解决，如果没有的话欢迎reopen此issue :)
