### ISSUE TITLE
港铁的站点

### ISSUE THREAD

**Issue by Gzline4-24hc** [railmapgen/rmp#250]
这是港铁的支线站点和竖直的换乘站
![DF0C10E0-FD4E-4205-896E-1551977278E1](https://user-images.githubusercontent.com/128379352/226899823-2534a782-60e5-4301-92da-8a15a85cc011.jpeg)
这是横着的换乘站
![4E1A7FB3-ECA8-4E55-B1B8-EF285F49529E](https://user-images.githubusercontent.com/128379352/226899978-cd3023f2-7fee-4244-bd08-600703198c4b.jpeg)
三线换乘站和付费区内长通道换乘
![22B9D1A1-B90D-45F1-8F47-E6C8162542AB](https://user-images.githubusercontent.com/128379352/226900054-b2f7e087-61fd-431e-9183-d9cf58496544.jpeg)
四线换乘站（有点模糊请见谅）
![78167FFD-EAB7-43ED-963C-2E75B2B1742D](https://user-images.githubusercontent.com/128379352/226900175-d41ad3ea-5802-4e76-b600-f430c8e6bd51.jpeg)
尖东站出站指示牌
![CC7E479F-0031-4D37-83F0-5E08FA1B944F](https://user-images.githubusercontent.com/128379352/226900263-1d7f6fca-5861-4207-afca-37326115313e.jpeg)
斜线换乘站
![7CCD2D9C-11AF-4F95-BBEC-677CF9FA5536](https://user-images.githubusercontent.com/128379352/226900386-e8e1db3a-0dbe-45ca-8109-8c5817ab31b4.jpeg)

**Comment by thekingofcity** [comment]
See #224
