### ISSUE TITLE
平板无法打开地铁线路图绘制器

### ISSUE THREAD

**Issue by ADUO715** [railmapgen/rmp#261]
平板无法打开地铁线路图绘制器，一直出现问题
![1514C939-6591-44C4-A49F-6FD6C279BA0F](https://user-images.githubusercontent.com/128993432/227790945-a5f01b5b-158c-49b0-aca9-b1107ceb6810.png)

**Comment by wongchito** [comment]
Hi @ADUO715 ,

麻煩閣下展開「详细信息」欄位並複製內容至本 issue，以便我們找出原因。多謝。

**Comment by ADUO715** [comment]
![13ED29D4-1CD4-4D9A-8DE7-9B765822A36B](https://user-images.githubusercontent.com/128993432/227964766-c157ad52-8033-4b1a-9c88-c91f4835bd4b.png)
错误代码如图
