### ISSUE TITLE
两个北京设施图标

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmp#262]
![bjsubway_tian'anmen](https://user-images.githubusercontent.com/98044618/227814150-d73d0902-3d34-4c74-8cde-3748d5ea689a.svg)
⬆️天安门图标

![bjsubway_airport](https://user-images.githubusercontent.com/98044618/228594340-8970daad-cb06-482a-b8e8-35cd00de8322.svg)
⬆️北京机场图标（03/29更新：我稍微缩小了机场图标的大小，之前的忘记按RMG的线路粗细缩小了）

@thekingofcity 这样一来北京地铁线路图所有元素就全齐了

**Comment by langonginc** [comment]
我前两天还想着天安门呢……

**Comment by Windows-Taskmgr** [comment]
我做京铁时就想怎么没有天安门图标

**Comment by DQB061204** [comment]
感谢提供！

**Comment by thekingofcity** [comment]
嗨，感谢贡献，此图标已被合入项目中并上线 :)
