### ISSUE TITLE
地铁线路图绘制器无法打开

### ISSUE THREAD

**Issue by 577lyh** [railmapgen/rmp#264]
更新浏览器并且重启也无法重新开启，不知为何，感谢指教！

**Comment by thekingofcity** [comment]
嗨，您提供的信息太少难以解决。至少需要知道操作系统，浏览器型号及版本，无法打开的截图等信息。

**Comment by 577lyh** [comment]
非常感谢您的回复，我已经自行解决。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "railmapgen/rmp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 凌晨1:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [railmapgen/rmp] 地铁线路图绘制器无法打开 (Issue #264)





 
嗨，您提供的信息太少难以解决。至少需要知道操作系统，浏览器型号及版本，无法打开的截图等信息。
