### ISSUE TITLE
导出图片只有黑色背景咋回事呢

### ISSUE THREAD

**Issue by YIYO1** [railmapgen/rmp#269]
透明背景无用，保存到手机点击会自动变色

**Comment by wongchito** [comment]
Hi @YIYO1 ,

導出的圖片使用支援透明背景的PNG格式，惟因手機/電腦作業系統各異，透明背景可能隨系統主題顏色而變化（於深色模式下顯示黑色，於淺色模式下顯示白色，於Adobe Photoshop等軟件下顯示為灰竹階磚）。

**Comment by YIYO1** [comment]
> 嗨@YIYO1，
> 
> 導出的圖片使用支援透明背景的PNG格式，惟因手機/電腦作業系統各異，透明背景可能隨系統主題顏色而變化（於深色模式下顯示黑色，於淺色模式下顯示白色，於Adobe Photoshop等軟件下顯示為灰白階磚）。

你好，但是好像我切换系统主题颜色并没有发生变化，依旧是黑底呢

**Comment by wongchito** [comment]
![image](https://user-images.githubusercontent.com/9390786/229730936-4eafc5a8-17c7-4a4b-a787-0c274359f7a4.png)

**Comment by thekingofcity** [comment]
Closed due to no reply :(
