### ISSUE TITLE
增加苏州轨道交通模板

### ISSUE THREAD

**Issue by beiguangrailtransit** [railmapgen/rmp#271]
![image](https://user-images.githubusercontent.com/3353040/229977303-fb6b7f20-a4b8-4e9b-b1a9-1771e0b34c7a.png)

建议增加苏州轨道交通模板
此图片为地铁列车上的图片，但官网找不到此图片。。。

**Comment by 52PD** [comment]
> 建议增加苏州轨道交通模板

这个不用你建议😓，我们是很欢迎你们制作轨交地图模版然后投稿的。

只不过就像@thekingofcity 在#105 中所说的，因为现在一个新的用于展示所有线路图的新功能rmp-gallery还没制作完，除目前现有模版外其他模版可能要等到该功能制作完成才会开始汇入到项目中。
