### ISSUE TITLE
Add icon width and height to text dx and dy

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#278]
1. 站名位于上、左、右侧时距离车站太近，位于下侧时距离太远![image](https://user-images.githubusercontent.com/123239445/230878292-cd2e3240-814c-411f-adc4-738f49e3dfa5.jpeg)
2. 中文与英文字间隔稍大，建议缩小
3. 英文字太粗

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。issue中提到的1和3都已修复并上线。2的话会在shmetro tuning后再修改，敬请期待 :)

**Comment by thekingofcity** [comment]
嗨，第二点已于 #296 中被修复，感谢等待 :)

**Comment by 28yfang** [comment]
现在问题已经不存在了。
