### ISSUE TITLE
上海地铁换乘车站站名距离车站太远

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#280]
<img width="1280" alt="Screenshot 2023-04-14 at 09 59 16" src="https://user-images.githubusercontent.com/123239445/231922772-7e520f5d-e67e-4e9a-83dd-42e1ffaee582.png">
<img width="1280" alt="Screenshot 2023-04-14 at 09 58 29" src="https://user-images.githubusercontent.com/123239445/231922797-90245961-34af-47e1-b2c6-6c4848490f62.png">

**Comment by 203IhzElttil** [comment]
我建议 加入一个可以调换乘站站名离换乘站距离的数值 默认为原来的数值（

**Comment by thekingofcity** [comment]
嗨，此问题会在shmetro tuning中一并修复，感谢您对项目的支持与建议 :)

**Comment by 203IhzElttil** [comment]
这玩意修好了
