### ISSUE TITLE
北京地图模板的问题

### ISSUE THREAD

**Issue by ClareDuan** [railmapgen/rmp#281]
1.西郊线标识错误的使用了广州风格
2.10号线巴沟站线段错误的直接连接了海淀黄庄站，导致在修改这段线段时苏州街站可能会“脱离”线网。正确连接法应该是:巴沟-苏州街-海淀黄庄站。(好像不止这里有问题，好多涉及到转角上的站点都有这问题)

**Comment by thekingofcity** [comment]
嗨，欢迎提交修改后正确的模板 cc @langonginc

**Comment by ClareDuan** [comment]
[RMP_1681501156061.zip](https://github.com/railmapgen/rmp/files/11236520/RMP_1681501156061.zip)

**Comment by langonginc** [comment]
确实有这样的问题，感谢指正，其实之前还有“和平门”站忘记调整站名位置了。

<img width="304" alt="image" src="https://user-images.githubusercontent.com/59787082/232173748-022fca1d-284c-4d38-8ced-4a9b6f1fb6de.png">

**Comment by ClareDuan** [comment]
[RMP_1681837792123.zip](https://github.com/railmapgen/rmp/files/11264494/RMP_1681837792123.zip)
已调整

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与贡献。此更新后的模板已合入项目中 :)
