### ISSUE TITLE
地铁站名与车站之间距离太远

### ISSUE THREAD

**Issue by D134679** [railmapgen/rmp#284]
地铁线路图绘制时，会出现地铁站名与车站之间距离太远，如图所示，该情况出现在使用上海地铁模板的斜上/下方站点名称标注中。

**Comment by D134679** [comment]
![1](https://user-images.githubusercontent.com/130880483/232263048-d84f4729-e9d9-4e5f-8f85-2c92c4f9b59b.png)

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与建议。此问题已在 #280 中被讨论，会在shmetro tuning中被修复。如您想暂时使用之前的无此问题的版本，欢迎前往 [release](https://github.com/railmapgen/rmp/releases) 页面下载适合您操作系统的上一个版本的离线包使用，谢谢 :)
