### ISSUE TITLE
设施的小问题

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp#286]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/59787082/232297708-d948dea4-8c4f-444a-ae79-6f4163af73c5.png">

1. 这个右侧的提示信息好像有点问题
2. railway 的图标好像有点偏

**Comment by thekingofcity** [comment]
问题1已确认，问题2应不存在因资源来自wiki common

**Comment by langonginc** [comment]
嗯……好吧

**Comment by thekingofcity** [comment]
Fixed in #287 :)
