### ISSUE TITLE
港铁风格车站站名问题

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmp#293]
对于港铁风格车站，当站名出现在下方时（无论左下、正下还是右下方），站名与车站图标有点大
（当车站被旋转为竖直方向时更明显一点）
<img width="465" alt="image" src="https://user-images.githubusercontent.com/120014893/235284855-68861938-c764-4135-a6e1-f5142ca3bce7.png">

**Comment by aaronyz2007** [comment]
大概量了一下，站名在右上和右下时，和车站的距离的比值约1：2，希望可以调整一下

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。您是想说港铁站名与车站大小在不同站名与车站图标位置时不一样是吗？方便截取官方图中比较明显的两个车站展示一下吗？

**Comment by aaronyz2007** [comment]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/120014893/235288104-3566d609-1bba-4534-adb3-74d47627e2c8.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/120014893/235288120-60fdecdc-2182-4357-94f9-bf1e7eaa71be.png">
如图，官方图中车站图标和站名的距离应该是一样的

**Comment by aaronyz2007** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/120014893/235288257-e8fd5229-cc79-401e-8d0c-023b7d2892b3.png">
RMP里当站名位于车站图标下方的时候，站名和车站图标距离太大了

**Comment by aaronyz2007** [comment]
（拿直尺对着电脑屏幕量过了）

**Comment by aaronyz2007** [comment]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/120014893/235288378-71f01be5-cf5d-4cf8-b9ec-763f7c45e452.png">
站名位于正上方与正下方的时候差距也挺大的

**Comment by thekingofcity** [comment]
嗨，感谢详细的解释，此问题已被修复于2.5.5版本 :)
