### ISSUE TITLE
Fix dy and offset for names in MTR station

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#294]
![image](https://user-images.githubusercontent.com/123239445/235329143-bbc73b58-3ec7-4f5a-baa4-5b3d18723a04.jpeg)

**Comment by thekingofcity** [comment]
嗨，此问题貌似只在mac上会出现，由于我手头尚未有可以调试的设备，此问题的修复被无限期搁置 :(

**Comment by linchen1965** [comment]
我这不是mac的也出现了……
![image](https://user-images.githubusercontent.com/92020676/236668168-86249578-3cb3-45ef-8f1f-8bd115c852cf.png)

**Comment by 28yfang** [comment]
@thekingofcity 我的ipad也有问题🤔️

**Comment by 28yfang** [comment]
@thekingofcity 
![image](https://user-images.githubusercontent.com/123239445/236668938-621889fe-057f-4b43-8218-51a53ea3425d.png)

**Comment by thekingofcity** [comment]
Hi, thanks for reporting the problem. It was fixed in 3.0.4 :)
