### ISSUE TITLE
Incorrect safe area padding in iOS landscape mode

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmp#300]
Safe area padding on the left hand side is wider than it should be in iOS Safari landscape mode (see below screenshot).

_Originally reported by @langonginc in Slack channel_

RMP - iOS Safari 
![image](https://user-images.githubusercontent.com/9390786/235488562-84d2bdca-9230-4c6d-af01-f01270299502.jpeg)

RMG - iOS Safari
![image](https://user-images.githubusercontent.com/9390786/235488436-d8d9b569-3c84-4f3b-adc4-435721d57bf6.png)

RMP - macOS Safari
![image](https://user-images.githubusercontent.com/9390786/235488504-933ef693-f48f-4f94-8419-2dad28123b00.png)

**Comment by thekingofcity** [comment]
Thanks for the reference from railmapgen/rmg#536 :)

**Comment by wongchito** [comment]
Refer to railmapgen/railmapgen.github.io#36 if RMP is expected to be run in standalone mode.
