### ISSUE TITLE
上海地铁普通车站名称据中上、中下位置时覆盖站点

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp#303]
![image](https://user-images.githubusercontent.com/123074394/235687627-ceca95a3-b1fe-4cb4-be69-de3412f99d58.png)

**Comment by 203IhzElttil** [comment]
开隐身模式就没问题了 正常浏览器是这样（当然我不知道原因）

**Comment by thekingofcity** [comment]
见 #305 :)
