### ISSUE TITLE
rmp无法正常导出图片

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp#304]
导出上海和北京的模板（无改动，就是预设模板）的svg后 浏览器打开svg都无法正常显示；Ai也打不开 显示无效的svg文件
png文件甚至无法导出（就是点了保存图片后无反应）
其他自制项目也是如此 只能显示线条和部分站名
![image](https://user-images.githubusercontent.com/106796352/235815500-be62574a-b66c-4131-b81c-2fc36b73c88d.png)
![image](https://user-images.githubusercontent.com/106796352/235815589-5b20d5f0-ca34-4d7f-9cf6-eb532a26eb13.png)
![image](https://user-images.githubusercontent.com/106796352/235815516-f8824eb6-a0a5-43ff-9e1a-1b38d61fc7c2.png)

**Comment by 28yfang** [comment]
好家伙

**Comment by wongchito** [comment]
上海地鐵車站的英文站名前加入了一個空格字元「&nbsp;」，本為符合上海風格設計，但該字元非合法的svg字元，應用普通空格或其他轉義字元替代。

**Comment by 203IhzElttil** [comment]
> 上海地鐵車站的英文站名前加入了一個空格字元「 」，本為符合上海風格設計，但該字元非合法的svg字元，應使用~普通空格~或其他轉義字元或偏移量替代。

那为何北京的也无法导出 北京的左对齐车站应该没那个空格吧

**Comment by ame017** [comment]
> 上海地鐵車站的英文站名前加入了一個空格字元「 」，本為符合上海風格設計，但該字元非合法的svg字元，應使用~普通空格~或其他轉義字元或偏移量替代。

我这边测试了一下，只要带上海换乘站，保存的SVG就会保存，保存PNG会没有反应。换成其他的车站就可以正常保存。

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。此问题已在2.5.13中被修复，special thanks to @wongchito debug.
