### ISSUE TITLE
又找到几个上海地铁车站的问题

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#305]
普通车站名称居上/下时覆盖站点（隐身模式也一样）
普通车站和换乘车站名称居右/左时离站点过远
![image](https://user-images.githubusercontent.com/123239445/235889333-decb72f1-21ea-41a2-8200-1bc16aafe78c.png)

**Comment by 203IhzElttil** [comment]
![image](https://user-images.githubusercontent.com/106796352/235894025-9156b74e-9329-4ebf-9f7d-f52e20afe9e9.png)
当时没想到
希望有人能理解上图的意思（就是一切以换乘车站为标准设置出站换乘车站和转乘车站）

**Comment by thekingofcity** [comment]
嗨感谢汇报问题，此问题在 #304 中一并被修复，如果在2.5.13中被解决，欢迎close此issue :)
