### ISSUE TITLE
只要图里带有“上海地铁换乘车站”就无法保存PNG，保存SVG也会报错。

### ISSUE THREAD

**Issue by ame017** [railmapgen/rmp#307]
删掉上海地铁的换乘站全部换成普通站，或者换成其他城市的换乘站风格就可以正常保存。
SVG报错内容：
error on line 1 at column 57371: Entity 'nbsp' not defined
Below is a rendering of the page up to the first error.
看一下是不是这个nbsp属性的问题呀？

**Comment by 203IhzElttil** [comment]
左对齐的上海地铁车站站名都有此问题 会修复的

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，已在 #304 中被修复 :)
