### ISSUE TITLE
文字白边有问题

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp#316]
比如v的底下会出现一个尖角
似乎是svg的文字白边通病（
如果能修复那最好
![image](https://github.com/railmapgen/rmp/assets/106796352/c8023efc-9640-4225-84a7-ae5442e6d4c2)

**Comment by DQB061204** [comment]
您也许可以试试白色背景 加上字后尽量不要有纯色线段 这样子就可以暂时性的解决该问题
但是该问题也是亟待解决的

**Comment by 203IhzElttil** [comment]
我找到解决方案了
![image](https://github.com/railmapgen/rmp/assets/106796352/7300466b-53c9-4544-b645-62f9b973a74f)
![image](https://github.com/railmapgen/rmp/assets/106796352/a6b0bc82-a170-44e1-bd61-165d37c7dd28)
（我在rmp里学svg）

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题并提出修复建议。车站名称的默认样式已添加 `stroke-linejoin: round;` 属性 :)

![image](https://github.com/railmapgen/rmp/assets/3353040/78ecefa4-8c16-4233-b75d-7902f4caa551)
