### ISSUE TITLE
Display rmp-gallery on gallery modal

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmp#321]

**Comment by wongchito** [comment]
Using chakra's `Modal` component, the content of it will be rerendered every time when opened. Hence the `iframe` will be reloaded every time, which causes unnecessary requests and loses all states. 

I've implemented a similar component named `RmgAppClip` where modal content is persisted when modal is closed. Checked out the RMG param import app clip for more details.

**Comment by thekingofcity** [comment]
> Using chakra's `Modal` component, the content of it will be rerendered every time when opened. Hence the `iframe` will be reloaded every time, which causes unnecessary requests and loses all states.
> 
> I've implemented a similar component named `RmgAppClip` where modal content is persisted when modal is closed. Checked out the RMG param import app clip for more details.

Great work. One quick question, how can I full-screen `RmgAppClip`?

**Comment by wongchito** [comment]
> Great work. One quick question, how can I full-screen `RmgAppClip`?
> 
> 

Not supported now. The customised styling needs to be expanded for other sizes. 

https://github.com/railmapgen/rmg-components/blob/master/src/theme/components/rmg-app-clip.ts#L36

**Comment by thekingofcity** [comment]
> > Great work. One quick question, how can I full-screen `RmgAppClip`?
> 
> Not supported now. The customised styling needs to be expanded for other sizes.

Oh, do we have any timetable for this feature? Oh how can I override sm?

**Comment by thekingofcity** [comment]
Thanks for the update in `7.1.6` of `@railmapgen/rmg-components`. Gallery is used with `<RmgAppClip />` :)
