### ISSUE TITLE
折线无法转换至直线

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#331]
<img width="1280" alt="Screenshot 2023-05-22 at 08 04 07" src="https://github.com/railmapgen/rmp/assets/123239445/efbe419a-1303-4fdf-b309-a04e1706acb6">
<img width="1280" alt="Screenshot 2023-05-22 at 08 04 19" src="https://github.com/railmapgen/rmp/assets/123239445/3f92fe83-fdd8-44e7-9da5-30dbd94c1599">

**Comment by thekingofcity** [comment]
嗨，这是个预期之中的现象，见 #328
