### ISSUE TITLE
Enhance Multiple Selection Detail

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp#338]
如题，如图。

![image](https://github.com/railmapgen/rmp/assets/59787082/153ee16c-bb78-4c0e-b0d5-cbefeb0d29d2)

**Comment by thekingofcity** [comment]
Hi, thanks for your suggestion. What's the meaning behind underlining 中文名 and English?

**Comment by langonginc** [comment]
> Hi, thanks for your suggestion. What's the meaning behind underlining 中文名 and English?
> 
> 

嗯就是搞一个表格，用站名显示都选中了那些站，比id直观。

**Comment by langonginc** [comment]
嗯就是搞一个表格，用站名显示都选中了那些站，比id直观。
