### ISSUE TITLE
Generate rmg saves

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmp#340]

**Comment by langonginc** [comment]
**样例测试/Sample Tests**

|Type|RMP Saves|RMP Graph| RMG Saves| RMG Graph|
|:-----------|:--------|:-------|:----------|:---------|
|**Line** (Shanghai and Beijing Style) | Beijing Line 1 `#C23A30` https://github.com/railmapgen/rmp-gallery/issues/54 | <img width="535" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/1b045df7-4552-4ffd-bf78-608044408a0d">| [RMG_-66.txt](https://github.com/railmapgen/rmp/files/11714432/RMG_-66.txt)| <img width="1404" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/ff90d1ec-ea0d-4d07-abf5-a4479d40b7c9"> |
|**Line** (Guangzhou Style) | Guangzhou Line 2 `#00629B` https://github.com/railmapgen/rmp-gallery/issues/224 | <img width="239" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/a275035f-e8e6-4ca3-85e7-77e3d5772aab"> | [RMG_-71.json.txt](https://github.com/railmapgen/rmp/files/11714479/RMG_-71.json.txt) | <img width="1342" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/4ae3f50b-12b3-439c-b7fd-68473bed1acd"> |
|**Line** (MTR Style) | MTR Tsuen Wan Line `#E2231A` https://github.com/railmapgen/rmp-gallery/issues/45 | <img width="262" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/69f98df6-bfd7-41bf-8eff-66bfd245f129">| [RMG_-72.json.txt](https://github.com/railmapgen/rmp/files/11714484/RMG_-72.json.txt) | <img width="1363" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/75498f63-b123-4e4d-ba51-305421a0bd4f"> |
|**Line** (start with virtual node)| Shanghai Line 9 `#87CAED` https://github.com/railmapgen/rmp-gallery/issues/173 | <img width="475" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/59f509ee-d632-4710-8ab2-f31c48da0b87">| [RMG_-69.json.txt](https://github.com/railmapgen/rmp/files/11714454/RMG_-69.json.txt) | <img width="1400" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/68786d07-191f-46c9-8c9b-79cd38a2dd73">|
|**Loop** | Beijing Line 2 `#006098` https://github.com/railmapgen/rmp-gallery/issues/54 | <img width="538" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/d3d7261b-8a6f-466e-bdeb-c90fadb3d110"> | [RMG_-68.json.txt](https://github.com/railmapgen/rmp/files/11714443/RMG_-68.json.txt)| <img width="1435" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/a6577f94-6a16-4086-8af9-4eda431e0841">| 
|**Branch Line** | Shanghai Line 10 `#C6AFD4` https://github.com/railmapgen/rmp-gallery/issues/173 | <img width="343" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/70070a69-ca80-4272-823b-b648d80378f8"> | [RMG_-70.json.txt](https://github.com/railmapgen/rmp/files/11714469/RMG_-70.json.txt)| <img width="1420" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/7a130cd5-cc12-4835-9df6-595e2edc40c1"> |
|**Branch Line** (Racecourse Station) | MTR East Rail Line `#61B4E4` https://github.com/railmapgen/rmp-gallery/issues/45 (Edited by @langonginc [1.]) | <img width="348" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/8b864fa4-56c6-4124-9725-31290d3f0b39"> | [RMG_-73.json.txt](https://github.com/railmapgen/rmp/files/11714522/RMG_-73.json.txt)| <img width="1433" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/f9479e5b-4586-4c9f-80de-17f00718be1b"> |


- [1.] I do NOT support the branch which start (end) with virtual nodes, so I added two line (between `University` and upper node, and between `Sha Tin` and lower node).

**Comment by thekingofcity** [comment]
各位好，

我非常高兴地向 @langonginc 表示衷心的感谢，他已成为地铁线路图绘制器的核心贡献者。

在过去的几个月里，Jiayi Wu展现出了非凡的才华和积极性，为地铁线路图绘制器和地铁线路图工具包中的其他相关项目做出了积极贡献。今天，导出RMG项目的合并请求正式完成，我们欢迎他成为核心贡献者之一。

在地铁线路图工具包，我们一直都会认可并珍视那些以独特方式支持我们的人的努力。无论是通过编码还是审核，每一份贡献都增添了地铁线路图工具包的价值，增强了其实用性和吸引力。

共同塑造一个充满活力和有用的平台，正是因为像Jiayi Wu和你们所有人这样贡献者的奉献，我们才能不断前进。

感谢你们成为这个旅程中必不可少的一部分。

诚挚问候，
thekingofcity



Dear all,

I am delighted to extend my heartfelt appreciation to @langonginc for becoming a core contributor to Rail Map Painter.

Throughout the past few months, Jiayi has showcased remarkable talent and initiative while actively contributing to Rail Map Painter and other related projects within the Rail Map Toolkit. Today, with the official merging of the "rmp to rmg" pull request, we welcome Jiayi as one of our esteemed core contributors.

At Rail Map Toolkit, we always acknowledge and value the efforts of those who support us in their unique ways. Whether it be through coding or auditing, every contribution adds value and enhances the utility and appeal of Rail Map Toolkit.

Together, we are shaping a dynamic and useful platform, and it is through the dedication of contributors like Jiayi and all of you that we continue to progress.

Thank you for being an essential part of this journey.

Warm regards,
thekingofcity
