### ISSUE TITLE
Increase Number of Interchanges for MTR Station

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmp#346]
如图，当前RMP内MTR车站仅支持5条换乘线路，为方便绘制共线，希望提高MTR车站的换乘上限。

![image](https://github.com/railmapgen/rmp/assets/134931870/312a78d8-ee43-4538-8a23-8c19de7a0bf0)

**Comment by thekingofcity** [comment]
嗨，感谢对项目提出的建议，此增强已上线 3.1.4，欢迎体验 :)
