### ISSUE TITLE
上海地铁转乘车站的新样式

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp#352]
上海城市规划展示馆的2023上海基础设施品质提升设计成果展中出现了一张上海地铁未来规划图（图源贵道蕉通b站动态）
![5bba1a0f1700d46c7e035012d3abdd0d1028685261](https://github.com/railmapgen/rmp/assets/106796352/4d338989-ca83-42db-b639-5266b192664f)
其中转乘车站肉眼可见变了样
自己修复了一下，大概长这样（就是出站换乘车站中加了一个圆）
![上海地铁转乘车站](https://github.com/railmapgen/rmp/assets/106796352/c85dcb39-c71e-46cd-8067-38251a6ba2c6)
可以考虑在未来加入rmp中

**Comment by 203IhzElttil** [comment]
加一句：上海地铁的换乘，出站换乘，转乘车站颜色都是rgb（62，58，57），hex：#3e3a39而不是纯黑（

**Comment by 203IhzElttil** [comment]
更正：出站换乘颜色是纯黑#000000；其他的换乘，出站换乘是#393332（CMYK：0，0，0，92）
改正后的新出站换乘svg，下面这个更准
![shdtzccz](https://github.com/railmapgen/rmp/assets/106796352/8094dc74-22c8-43a5-a9c5-b888cdc85c9b)

**Comment by thekingofcity** [comment]
嗨，感谢提供的数据。此功能即将上线，敬请期待 :)

![image](https://github.com/railmapgen/rmp/assets/3353040/ba621ec2-4829-44c6-8979-72253bf97895)
