### ISSUE TITLE
广州样式字母线路标识显示偏移

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#353]
如图，APM线标识的“APM”（字母部分）向上偏移
输入其他字母也会出现同样情况
![APM](https://github.com/railmapgen/rmp/assets/137034903/1882d2dd-2ed7-4e99-bb6d-41c20596061c)

**Comment by langonginc** [comment]
您好，感谢您对项目的支持，您可以再具体说明一下如何操作出现的，我这边目前无法复现这个问题，或者您也可以上传 json 文件。

**Comment by Minwtraft** [comment]
> 您好，感谢您对项目的支持，您可以再具体说明一下如何操作出现的，我这边目前无法复现这个问题，或者您也可以上传 json 文件。

即：选择“广州地铁线路标识”，放置在画布上，中文线路名称改为例如“A线”，英文改为例如“A Line”，此时线路标识中的字母向上偏移
导入带广州样式字母线路的文件也如此

视频：

https://github.com/railmapgen/rmp/assets/137034903/8871940c-850b-4676-837c-89e0fed4f8a5


https://github.com/railmapgen/rmp/assets/137034903/2988d411-a719-4b0b-9cac-45335b31fd51

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题。此问题已被证实并被修复，欢迎使用3.2版本 :)
