### ISSUE TITLE
RMG2RMP

### ISSUE THREAD

**Issue by JERRYZ1972** [railmapgen/rmp#359]
在rmp中“Import From RMG Format”的时候不能显示选择RMG文件呢？调用的RMG 和本机DEV 和UAT 版本有什么区别么？

**Comment by thekingofcity** [comment]
嗨，需要您在网页版版的rmg中有至少一个存档可供选择时，rmp的rmp存档选择界面才会有数据。目前直接从本地文件系统中上传rmg存档的功能已经不存在了。

如果您是使用 https://railmapgen.github.io/ 或 https://railmapgen.gitlab.io/ 访问rmp的话，那么应该不存在显示任何DEV或UAT的可能。如果您通过其他各种方式访问到UAT或DEV的话，那么这些数据与上述两个网站间的数据不共通，谢谢。

**Comment by thekingofcity** [comment]
由于长时间没有进一步的回复而关闭 :)
