### ISSUE TITLE
求柏林地铁线路标识

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#372]
柏林地铁的线路标识分为U-Bahn标识和S-Bahn线标识：
U-Bahn标识为矩形，如图：
![image](https://github.com/railmapgen/rmp/assets/123239445/8aefdb99-d472-4470-9761-e3d8aa563192)

S-Bahn标识为类似上海地铁换乘车站的形状，并分为单位数（大交路）和双位数（支线/小交路）。需注意的是，前者图形比后者稍段一些，如图：
![image](https://github.com/railmapgen/rmp/assets/123239445/e7703570-f7a5-469e-b54a-b949b4b01fce)

另外一点：字母U/S与数字之间有一个很小的空隙。

**Comment by thekingofcity** [comment]
当U-Bahn数字为两位数时是什么样子呢？有没有标识与线段车站的比例关系呢？

**Comment by 28yfang** [comment]
U-Bahn没有两位数的标识。

**Comment by 28yfang** [comment]
简单地比对了一下，U-Bahn标识的长度约为4条线段的宽（一条线段为5pt，如果我没记错的话，那U-Bahn标识约长20pt），S-Bahn一位数的长度约为4.5条（22.5pt），两位数的长度约为5条（25pt）。标识的宽度均约为3条线段的宽（15pt）。
