### ISSUE TITLE
部分线段的颜色问题

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp#374]
rmp中河流的颜色和磁浮线的颜色不同
通过取上海官方线网图颜色，河流颜色为#B9E3F9
![image](https://github.com/railmapgen/rmp/assets/106796352/620495a2-6cad-43b1-a2f6-ece7fc487106)
磁浮线双色根据上海地铁官方发布的文章：https://mp.weixin.qq.com/s/rB4x9smT5bt-5Pva95-8yg
中的
![image](https://github.com/railmapgen/rmp/assets/106796352/bd288f37-3fb5-4829-998d-9eae8077c3f6)
自取色：
![image](https://github.com/railmapgen/rmp/assets/106796352/78bb0c5d-85a0-4941-9f38-890743890d95)

（因为这玩意调色板上没有所以发在rmp里面）

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与建议。磁浮颜色与河流颜色已更新并即将上线。但请注意河流颜色需要考虑到各个城市的不同，所以不好一概而论。之后也希望有更好的解决方法处理不同城市间水域色差的问题。
