### ISSUE TITLE
Unexpectedly large right padding in canvas

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmp#380]
OS: iPadOS 17.0 Beta 3
Browser: Safari

![image](https://github.com/railmapgen/rmp/assets/9390786/b45fc7fc-0e46-463d-b70d-3fee04c6cac4)

**Comment by thekingofcity** [comment]
Hi, thanks for reporting. iPad OS 15.4 works as expected. And I don't have enough methods to test an environment that is hard to debug.

**Comment by wongchito** [comment]
Issue no longer exists in iPadOS 17 beta 4.
