### ISSUE TITLE
上海磁悬浮线路可否改为官方网络图上的双色线路？

### ISSUE THREAD

**Issue by Egneriess** [railmapgen/rmp#381]
http://service.shmetro.com/awltcz/index.htm
![image](https://github.com/railmapgen/rmp/assets/108216173/f81b3531-db66-4bf3-a4b7-f5d2475788a9)

**Comment by thekingofcity** [comment]
嗨，上海磁悬浮线路已经是双色线路，不知您说的更改具体指的是哪一部分？

**Comment by Egneriess** [comment]
![image](https://github.com/railmapgen/rmp/assets/108216173/8c13a851-e334-4c34-956f-92d6a9363906)

**Comment by 203IhzElttil** [comment]
调色板里的磁浮线颜色是给rmg用的 rmp用上海磁悬浮样式

**Comment by langonginc** [comment]
Hi, 磁浮线的双色线属于特殊线条，修改方法如下：

选中一个纯色线条

<img width="699" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/26b7eb6a-8a04-4542-8f0e-15f0da4db87f">

更改线路样式类型为上海磁浮线。

<img width="683" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/630264f9-f4dd-44cd-af17-474cdaec6165">

您再试试看，感谢您对本项目的支持。

**Comment by Egneriess** [comment]
好的
