### ISSUE TITLE
金山铁路可否改为白黑间隔？

### ISSUE THREAD

**Issue by Egneriess** [railmapgen/rmp#382]
http://service.shmetro.com/awltcz/index.htm
![image](https://github.com/railmapgen/rmp/assets/108216173/1d7d7b45-c7b8-466e-9934-006bb0801368)

**Comment by thekingofcity** [comment]
嗨，中国铁路样式为黑白间隔，您可使用此样式 :)

**Comment by Egneriess** [comment]
好的
