### ISSUE TITLE
如何制作图例与标题

### ISSUE THREAD

**Issue by Egneriess** [railmapgen/rmp#389]

**Comment by thekingofcity** [comment]
嗨，欢迎选择适合您需求和能力的方式帮助绘制器：

- 对于静态图标，您可参考 #262 与 #302 制作svg后上传到议题中。
- 对于动态图标，您可参考 [Node Guide: Creating a miscellaneous node for Rail Map Painter](https://github.com/railmapgen/rmp/blob/main/docs/nodes.md)

期待您的贡献 :)

**Comment by Egneriess** [comment]
是否可以添加自动图例功能？
