### ISSUE TITLE
Disable scale options based on browsers limitations

### ISSUE THREAD

**Issue by 114513** [railmapgen/rmp#393]
前几天导出时选了500%缩放，等了好几分钟也没见下载任务开始，用edge/谷歌/360浏览器都不行，最后选400%缩放导出了个6.94MB的图片
今天又换了个更大的json文件实验，500%和400%缩放都导出不了，选300%才导出一个6.91MB的图片，但svg可以正常导出
![RMP_1691064722633](https://github.com/railmapgen/rmp/assets/90558799/f6fe41b8-331b-4400-b0d9-9da729b132b4)
![RMP_1691064911221](https://github.com/railmapgen/rmp/assets/90558799/8faeee7e-f1f1-4a71-b313-86fcdf5d3fe4)
上图:300%缩放的png图片 下图:svg图片
横坐标在-3000到2650左右，纵坐标在-700到2500左右

**Comment by thekingofcity** [comment]
嗨，这是由于浏览器的最大画布限制所导致的。具体原因和解决方案可以在 #301 种了解更多，谢谢 :)

**Comment by wongchito** [comment]
Hey @thekingofcity ,

Is it possible that we disable the large scale options which exceed the browser's limit, based on the current canvas size?

**Comment by thekingofcity** [comment]
Hi @wongchito ,

Yes, it is possible and should be implemented. Also, [yisibl/resvg-js](https://github.com/yisibl/resvg-js) should also be used as the only solution to generate the image in both the app and gallery.

**Comment by thekingofcity** [comment]
![image](https://github.com/railmapgen/rmp/assets/3353040/8d7d1bfe-9b66-4e0a-ac3e-a7a39eb4147a)
