### ISSUE TITLE
转折弯角因子为0或负数的线段显示bug

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#394]
135°折线线段转折弯角因子为0（或负数）时，如果两端点的车站按对角线排列，则线段不显示（也无法点击）
90°垂直线段转折弯角因子为0（或负数）时，如果两端点的车站按竖直方向排列，则线段不显示（也无法点击）
视频和图片多次上传失败，故在此一并上传至网盘
https://wwyp.lanzoul.com/ia4AP14ws62j

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，此问题已被确认并修复上线 :)
