### ISSUE TITLE
Default line color of Suzhou Rail Transit transfer stations

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp#399]
管理员您好，感谢您抽空更新RMP。

苏州地铁换乘站样式预设的2号线底色为黑色，与官方不符，望管理员可以尽快修改。

感谢。

**Comment by 203IhzElttil** [comment]
这是调色板的问题吧

**Comment by thekingofcity** [comment]
嗨，如同楼上所说，这是由于调色板中的数据不正确导致的，欢迎通过 https://railmapgen.github.io/?app=rmg-palette-upload 更新并上传正确的数据，并等待我们的审核，之后，我将更新苏州轨道交通换乘车站的默认颜色，谢谢 :)

**Comment by thekingofcity** [comment]
嗨，调色板中2号线的底色为白色，见此行

https://github.com/railmapgen/rmg-palette/blob/b38bb0745201398460573cb69f44f4e0d542d934/public/resources/palettes/suzhou.json#L15

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，虽然它不会影响使用，但此问题已被修复并上线 :)
