### ISSUE TITLE
90° rotation in Suzhou Rail Transit station name

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp#402]
管理员您好：

苏州地铁11号线部分车站于官方线路图被显示为竖写（如图），望管理员能增加此功能。：）

参考图片: https://weibo.com/6378085595/N4WtiEAdr

**Comment by thekingofcity** [comment]
嗨，竖写暂不被支持，近期也没有实现的计划，未来有可能会予以实现，感谢理解并敬请期待 :)

**Comment by 203IhzElttil** [comment]
![image](https://github.com/railmapgen/rmp/assets/106796352/d6df1b20-51f6-4d90-921f-6c9ed3c552e9)
其实用text可以做到（

**Comment by thekingofcity** [comment]
This is now possible with `src/components/svgs/common/multiline-text-vertical.tsx` :)

**Comment by thekingofcity** [comment]
嗨，此功能已在 3.4.21 中实现，欢迎体验 :)
