### ISSUE TITLE
折线转角因子无法设置为0

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp#405]
135˚折线：
https://github.com/railmapgen/rmp/assets/123239445/8ce10442-5a87-4529-b084-1380b86d55a5

90˚折线：
https://github.com/railmapgen/rmp/assets/123239445/1a8c2c8a-2b06-4af7-ade2-98ad6ac2377a

**Comment by 203IhzElttil** [comment]
设成无限接近于0的数就好 比如1e-300
极限是5e-324，网上查的（

**Comment by thekingofcity** [comment]
嗨，这是修复 #394 导致的问题，暂时您可使用楼上的方法临时解决，之后我们将通过优化对角线和同横纵坐标时的情况来避免在 #394 中的问题 :)

**Comment by thekingofcity** [comment]
嗨，此问题已被修复并上线。 #394 中提到的问题亦被 #409 修复 :)
