### ISSUE TITLE
Dotted lines and big brackets in Beijing Subway

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp#412]
北京地铁苹果园－古城段采用了空心虚线显示，望管理员能增加。
另外，木樨地虚拟换乘下方设有大括号【站内换乘暂缓开通】，此图示可植入“站外换乘”选项。
感谢。

（备注：可与其他北京设施图标【#262】同步更新）

参考来源：https://www.bjsubway.com/subway/images/lwt.png

**Comment by thekingofcity** [comment]
嗨，感谢建议，方便的话请截图参考来源中涉及到的部分 :)
