### ISSUE TITLE
RMP的严重漏洞

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmp#413]
RMP有一个严重漏洞：无法更改站名（无论是中文站名和英文站名），刷新也无效，这导致我的作品无法正常制作。但是UAT没有这个问题，我想知道为什么会这样

**Comment by 28yfang** [comment]
另：有时取色无效，刷新页面后恢复正常，见录屏
https://github.com/railmapgen/rmp/assets/123239445/ef58b101-aca3-4a4b-84b2-4f8295d254f5

**Comment by Windows-Taskmgr** [comment]
此问题已不再复现

**Comment by wongchito** [comment]
@thekingofcity 我懷疑是FocusTrap的問題導致輸入框無法被選中，`rmg-components@7.1.11`沒有FocusTrap可以試試。

但顏色無法變更的問題，我暫時無法重現。

**Comment by wongchito** [comment]
`rmg-components@7.1.13`已修復FocusTrap問題，當AppClip關閉時停用FocusTrap.

**Comment by thekingofcity** [comment]
嗨，问题应该已被修复，感谢报告 :)
