### ISSUE TITLE
Prevent text selection in SVG

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmp#414]
We should prevent text selection in any SVG nodes containing text by adding CSS style `user-select: none;`, as RMP is implemented with dragging feature. 

![image](https://github.com/railmapgen/rmp/assets/9390786/ee29d86f-9412-4b97-add7-b4086d2fd10d)

**Comment by thekingofcity** [comment]
Though `user-select: none;` can only be applied to touch devices via https://stackoverflow.com/a/63666289, it may be better to have it applied to all devices as even interacting with the mouse, users could still not select the text.
