### ISSUE TITLE
文字白边建议

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp#415]
很多线路图站名文字都尽量避开了线段，设施等元素（如北京、广州等），不可确定白边粗细
也有很多城市线路图文字根本没有白边（如南京、苏州等）
能看出明显文字白边的线路图只有上海和深圳等少数城市（深圳也尽量避开了很多重叠，但有些没有避开）
各城市白边粗细也不同；

实际比例线网图中：
上海（线段宽度15px）站名白边3px
换算至rmp中应为1px
![截图20230821170524](https://github.com/railmapgen/rmp/assets/106796352/df7ea266-6eeb-4557-bcdd-829b17e3c317)

深圳（线段宽度22px）站名白边2px
换算至rmp中应为0.45px
![截图20230821170640](https://github.com/railmapgen/rmp/assets/106796352/98f77d9e-2329-48f8-b4c2-0d972dd13732)

但目前rmp中所有文字白边宽度都是一个固定的值（0.67px） 
希望以后给text出一个可调节或关闭文字白边的功能并修正上海车站白边宽度 功能类似下图（仅供参考，上海车站此项可选择禁用
![截图20230821161339](https://github.com/railmapgen/rmp/assets/106796352/b8218e72-676c-4810-91b4-f961d4f827c4)
1.67我瞎打的

**Comment by thekingofcity** [comment]
嗨，感谢建议。按照项目设计原则，这一类与某一车站类型强绑定的样式都应该不可更改地与车站一起提供给用户，所以最终实现情况应该不包含一个可以调整的参数，而是简单的上海车站文字就会有一个固定的白色描边，数值与深圳不同，北京车站则没有。

对于当前议题的细节，我还想确认下目前项目所提供的车站中，是只有上海的线路图中车站文字才有白色描边且换算到项目中为1px吗？如果没问题的话我会将白色描边样式抽出仅提供给上海的车站 :)

**Comment by 203IhzElttil** [comment]
> 嗨，感谢建议。按照项目设计原则，这一类与某一车站类型强绑定的样式都应该不可更改地与车站一起提供给用户，所以最终实现情况应该不包含一个可以调整的参数，而是简单的上海车站文字就会有一个固定的白色描边，数值与深圳不同，北京车站则没有。
> 
> 对于当前议题的细节，我还想确认下目前项目所提供的车站中，是只有上海的线路图中车站文字才有白色描边且换算到项目中为1px吗？如果没问题的话我会将白色描边样式抽出仅提供给上海的车站 :)

北京 广州无法确定。但可以跟上海白边粗细一样，为了某些用非上海风格幻想线路图的美观（当然也是可以设为0）

忘了说 港铁（线段宽度16.3px）车站也有白边，为0.61px

**Comment by thekingofcity** [comment]
![image](https://github.com/railmapgen/rmp/assets/3353040/caa4b12a-1e14-4f33-8391-425953799854)

即将上线，敬请期待 :)

**Comment by thekingofcity** [comment]
因为之前值比1大，现在调整到1所以变细了

**Comment by 203IhzElttil** [comment]
想知道这个白边的原理 到底是怎么加粗的

**Comment by 203IhzElttil** [comment]
> 因为之前值比1大，现在调整到1所以变细了

想知道这个白边的原理 到底是怎么加白边宽度的
知道原理后我应该能给出准确的数值

**Comment by 203IhzElttil** [comment]
> 因为之前值比1大，现在调整到1所以变细了

按我自己思路在ai里试了下
给上海改成2，港铁改成0.92试试

**Comment by 203IhzElttil** [comment]
> 嗨，你可以直接在浏览器中通过开发者工具修改网页上车站文字的stroke-width数值，调整到合适的值后发到这里，谢谢 :)
> 
> ![image](https://user-images.githubusercontent.com/3353040/262585907-20bb04f8-4f0f-4360-9f33-b8cf4335b1c3.png)

才知道这也可以改（
上海2.5px
港铁1.25px
