### ISSUE TITLE
Palette only be used once

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp#416]
After updating the palette feature, the palette does not work after using it once.
@thekingofcity This needs to be updated asap as users need to refresh every time to use the palette:)

**Comment by thekingofcity** [comment]
嗨，我修改一个苏州轨道交通车站的颜色后，再次尝试修改另一个苏州轨道交通车站的颜色，是可行的。如果无法提供进一步的复现步骤，请勿继续回复 :)
