### ISSUE TITLE
下载线路不完整

### ISSUE THREAD

**Issue by XiaoLiangrui** [railmapgen/rmp#423]
下载线路图片时只有全部线路的一小部分，不能完整下载，希望能得到回答谢谢啦😊

**Comment by langonginc** [comment]
您好，您可以上传一下出问题的存档 json 文件吗，以便分析问题，感谢您对项目的支持。

**Comment by XiaoLiangrui** [comment]
我该怎么上传这个文件呢？这里不支持用这个格式

**Comment by XiaoLiangrui** [comment]
现在可以下载了，谢谢您，应该是这个不太稳定吧

**Comment by XiaoLiangrui** [comment]
就是时好用时不好用

**Comment by thekingofcity** [comment]
嗨，如果能找到怎样的操作顺序可以导致导出的图片不完整，欢迎回复，否则将无法进行问题的排查和修复，谢谢

**Comment by XiaoLiangrui** [comment]
您好，我该如何获得3.2.20版本的新网站呢，我这还是3.2.18版本的

**Comment by thekingofcity** [comment]
> 您好，我该如何获得3.2.20版本的新网站呢，我这还是3.2.18版本的

嗨，你可以打开隐身模式或者更换浏览器重新访问。如果想要使用原来的作品验证问题的话，请下载保存后重新导入 :)
