### ISSUE TITLE
Fix calculate canvas size with getBoundingClientRect

### ISSUE THREAD

**Issue by MOLAaaaaaaa** [railmapgen/rmp#425]
作者大大，这个工具包非常好，我用它绘制了出很多我很满意的地铁图。但是最近我在绘制新的项目的时候出现了导出的图片和SVG都显示不全的情况，如图所示，请问这是什么原因？

![RMP_1693130003732](https://github.com/railmapgen/rmp/assets/90079494/39903a15-6c6a-4578-8854-a2206fba4073)

望回复，感谢！

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题。想了解一下您使用的操作系统和浏览器版本，我们现在怀疑是一些特定浏览器的实现原因导致的问题 :)

**Comment by XiaoLiangrui** [comment]
我的也是这个情况，而且在平板上和电脑上都有这个问题，我的操作系统是HarmonyOS 2.0.0 和Windows7,浏览器分别是华为浏览器14.0.1和Edge浏览器

**Comment by thekingofcity** [comment]
嗨，我们换用了另一种方法计算画布大小，欢迎在 3.2.20 版本上验证问题是否被修复 :)

**Comment by XiaoLiangrui** [comment]
作者您好，我这里的网站还是3.2.18版本的，我该如何获得3.2.20版本的呢？
