### ISSUE TITLE
Unable to access the 3.2.20 version of the website

### ISSUE THREAD

**Issue by XiaoLiangrui** [railmapgen/rmp#427]
作者您好，我尝试隐身访问和更换浏览器访问，均不是3.2.20版本的网站，都是3.2.18版本的，我这到底是有什么问题呢？我用浏览器分别是华为浏览器14.0.1.302版本和Edge浏览器115.0.1901.183版本。望回复，感谢！！！

**Comment by thekingofcity** [comment]
嗨，很抱歉我们无法帮助您本地的问题。临时的解决方法包括前往[这里](https://github.com/railmapgen/railmapgen.github.io/releases)下载离线版本，包含3.2.20版本的新离线包将在大后天9.1上线，敬请期待 :)
