### ISSUE TITLE
Donation: New features request for [city name]

### ISSUE THREAD

**Issue by Nefelibata-HF7** [railmapgen/rmp#442]
Hi, I'd like to have new features, and here is my support.

希望可以增加渐变色线段

**Comment by thekingofcity** [comment]
Hi, thanks for considering supporting Rail Map Painter.

我想了解您所提到的渐变色线段的大致摸样，以方便我预估一个合适的捐赠金额给到您 :)

**Comment by thekingofcity** [comment]
Closed due to no comment ):
