### ISSUE TITLE
上海车站站名行距较小

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp#444]
部分车站可能出现一行文字的白边盖掉另一行文字一小部分的情况
![1](https://github.com/railmapgen/rmp/assets/106796352/bfc1f2d1-9272-4096-b96f-76d01095307f)
将dy值更改后近似为官方图上的正确值 也解决了白边挡上行文字问题
（我忘了这玩意怎么算的来着，好像是offset8中文±12.67英文±6.67 总之我把数值放在这然后再看看）
![截图20230923171521](https://github.com/railmapgen/rmp/assets/106796352/18e8a49e-dd7b-4d31-8adf-ad38c894976b)

**Comment by thekingofcity** [comment]
Updated in #831
