### ISSUE TITLE
RMP2RMG forgotten line style type

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmp#446]
在使用北京地铁纯色样式时，无法使用RMP转RMG的工具，望修复👍🏻

**Comment by langonginc** [comment]
感谢您的反馈，我已经注意到了相关问题，将尽快修复。 👍 

https://github.com/railmapgen/rmp/blob/d4d792b9763de24cc89909112dcd435f83b15fba/src/util/to-rmg.ts#L169
