### ISSUE TITLE
缩放限制的解决方法

### ISSUE THREAD

**Issue by Egneriess** [railmapgen/rmp#457]
由于浏览器的画布限制，部分缩放选项被禁用。
可能的解决方法包括使用此命令行工具从SVG生成图像：[RazrFalcon/resvg](https://github.com/RazrFalcon/resvg) 
这种情况如何解决，详细教程有吗？

**Comment by Egneriess** [comment]
@thekingofcity 在吗

**Comment by Egneriess** [comment]
@thekingofcity 在吗

**Comment by Egneriess** [comment]
@thekingofcity 在吗

**Comment by thekingofcity** [comment]
嗨，您可以导出svg文件后使用 [RazrFalcon/resvg](https://github.com/RazrFalcon/resvg) 生成图片。 您可以下载resvg的最新二进制可执行文件后不带任何参数运行它，并通过打印出的帮助找到正确的命令参数 :)

**Comment by Egneriess** [comment]
但无法导出svg怎么办

**Comment by Egneriess** [comment]
![image](https://github.com/railmapgen/rmp/assets/108216173/9a9f361d-4027-406a-9354-25090ed0baae)

**Comment by Egneriess** [comment]
@thekingofcity 在吗

**Comment by Egneriess** [comment]
@thekingofcity 在吗

**Comment by Egneriess** [comment]
@thekingofcity 在吗

**Comment by Egneriess** [comment]
可以了，谢谢

**Comment by Egneriess** [comment]
有个问题，咋让它字更精细？

**Comment by thekingofcity** [comment]
> 有个问题，咋让它字更精细？

什么叫更精细？直接放大缩放倍率不行吗？

**Comment by Egneriess** [comment]
但有缩放限制啊

**Comment by Egneriess** [comment]
就算svg也必须用75%的缩放限制

**Comment by Egneriess** [comment]
可不可以把它切分在拼接来解决这个问题

**Comment by thekingofcity** [comment]
嗨，svg不存在缩放一说，因为它是Scalable Vector Graphics可升级矢量图形。如果您是有的绘制器在导出svg时有缩放选项，那您一定是使用了第三方的版本，我们无法提供任何帮助 :)

**Comment by Egneriess** [comment]
好的
