### ISSUE TITLE
Shenzhen Metro branch line badge

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#458]
对于深圳地铁线路标识，虽然多数可以使用“北京地铁线路标识”，但是6号线支线无法表示。因此，希望能增添一个形如深圳地铁6号线支线标识的模版（如图）
![1696160007509](https://github.com/railmapgen/rmg-palette/assets/146333201/ddb5bcc8-7431-4a28-8294-713191c29e21)
该模版可以基于原有的“北京地铁线路标识”修改得到。

**Comment by langonginc** [comment]
感觉不大一样，深圳的 “号线” 上下居中，而北京则是中文偏上。

**Comment by CatAlan1028** [comment]
是有一些区别。但是能勉强用用。最关键是先加上支线模版。毕竟使用这种结构来标示线路的城市很多，不可能每一个都调一下位置作为一个模版

**Comment by CatAlan1028** [comment]
模仿北京的样子加也可以的，没关系

**Comment by CatAlan1028** [comment]
目前我只能这样做
![屏幕截图 2023-10-31 213114](https://github.com/railmapgen/rmp/assets/146333201/5c7c70f0-6f8e-4049-a556-9e6439f4a5e4)
但是我还是希望你们能够做一个正式的支线模版。毕竟这样拼起来会长一截。
