### ISSUE TITLE
A New Kind of LINE STYLE:Chinese High-speed Railway新的线段绘制：高铁

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#460]
线段绘制中建议添加【中国高铁样式】，供绘制全国铁路或局部铁路使用。
具体为：将【中国铁路样式】中的黑色部分改为红色或淡红色即可得到【中国高铁样式】
或可以更强一点，将【中国铁路样式】中的黑色部分颜色改为可以自定义，效果更佳。

**Comment by thekingofcity** [comment]
嗨，感谢您的建议。想了解下是否有哪张官方图例中有此样式可以参考呢？方便以图片或链接的方式回复吗？

**Comment by CatAlan1028** [comment]
暂时没找到特别官方的...不过这种将高铁标为红色是非常常见的。初中的时候，我们的地理课的彩色地图册就将高铁印成红色（稍偏粉色）。你可以看一看百度地图、腾讯地图、高德地图等一些国内主要地图软件，大多数都将高铁印成红色的铁路线，只是色彩对于不同的地图软件来说略有差异。
或者**干脆直接允许将原来的黑色部分自定义颜色，这样也可以区分不同线路的铁路**（如对比修建时间、主要铁路或用于部分城际铁路）。我认为，**这种设计能够更好地拓展这个软件的功能。为什么其它种类线条可以选颜色，而铁路不可以呢？**

**Comment by CatAlan1028** [comment]
顺便请问一下，你们若采纳一条建议，大概多久能够整合到软件里？
或者换个问法，一般你们更新版本的间隔时间是多久？

**Comment by thekingofcity** [comment]
嗨，如果您无法找到任何地铁或铁路公司的官方图册中有关于(高速)铁路的具体画法参考，那么我们将不会立马进行更新。这是由于地铁线路图绘制器的设计之初就将目标设置为复刻现实中存在的样式，而非任意样式。但我们也不会拒绝此功能请求，会将其搁置并等待后续时间中，是否有足够的精力与兴趣来实现此功能。

关于更新间隔，由于此项目完全开源且核心贡献者为爱发电，所以没有任何更新间隔的保证与承诺。换句话说，这是个完全由核心贡献者依据其个人偏好而维护的项目。

欢迎您对项目进行一定修改后打开和并请求尝试，我们会尝试审核它们并考虑是否合入项目中。如果您不想受制于人，也欢迎分叉此项目并自行修改分发，这在本项目的授权协议下都是完全可以的 :)

如果您尚未有此能力但又无论如何想要看到此更改的快速上线，您也可以考虑通过捐赠的方式支持并提高此功能的实现优先级，这将允许我们将更多精力分配在此功能上。

**Comment by CatAlan1028** [comment]
中国铁路12306官方网站-信息查询-交通查询，虽然是高德地图的，但是是官方铁路网站，不知道这个算不算。
![屏幕截图 2023-10-31 221909](https://github.com/railmapgen/rmp/assets/146333201/0aa7bbe0-65a0-4cc3-8a8e-6a2f54712fbb)
如图，在图正中高铁被标为橙红色。

**Comment by CatAlan1028** [comment]
放在官网说明它是官方认可的。

**Comment by CatAlan1028** [comment]
由于它是高德地图（地图左下角标识），如果你们要收集样式可以直接上高德地图官网。

**Comment by thekingofcity** [comment]
嗨，此图示并非符合地铁线路图绘制器所针对的线路图类型，所以并不会被认为是合适的参考来源。

**Comment by CatAlan1028** [comment]
但是请您注意，显然中国高铁与中国普通铁路的标识只会差一个颜色，其他部分完全一样。你们只需要采用这个颜色并染到中国铁路标识的黑色部分即可。我认为这个应该只是新增一种颜色的问题，不太能算样式问题。

**Comment by CatAlan1028** [comment]
但是请您注意，显然中国高铁与中国普通铁路的标识只会差一个颜色，其他部分完全一样。你们只需要采用这个颜色并染到中国铁路标识的黑色部分即可。我认为这个应该只是新增一种颜色的问题，不太能算样式问题。

**Comment by 52PD** [comment]
> 但是请您注意，显然中国高铁与中国普通铁路的标识只会差一个颜色，其他部分完全一样。你们只需要采用这个颜色并染到中国铁路标识的黑色部分即可。我认为这个应该只是新增一种颜色的问题，不太能算样式问题。

我个人认为有以下几点这张地图不会被接受：

首先12306并未像其他国家的铁路地图一样单独绘制，而是嵌入了高德地图自行制作的铁路线路图，理应不算是官方线路图。

此外，目前RMP支持的绘图样式只有无论地铁还是其他国家铁路公司常用的变形地图，而12306上因是照搬的高德地图，所以也不存在使用变形地图，也正是因此原因在RMP上绘制CRH地图基本是行不通的。

所以综上所述，上面的图不仅算是样式问题，而且该图并不是官方地图所以应当不会被接受。

**Comment by CatAlan1028** [comment]
那么可不可以将高铁的黑色部分也做成能够自定义颜色（设定默认为黑色）

**Comment by CatAlan1028** [comment]
这样的话你们也不用担心样式标不标准的问题，而铁路线段的样式也能更加灵活

**Comment by thekingofcity** [comment]
嗨，我们仍然坚持仅会实现官方绘制的符合本项目所认为合理的线路图。感谢您的建议不过看起来官方无此类型线路图实现，欢迎在有新变化的情况下开启新议题讨论，谢谢 :)

**Comment by CatAlan1028** [comment]
找到证据了。政府部门网站http://bzdt.ch.mnr.gov.cn/中的地图有高铁的图例，不过很可惜没有矢量图

**Comment by CatAlan1028** [comment]
比如我选择了粤港澳大湾区的地图http://bzdt.ch.mnr.gov.cn/browse.html?picId=%224o28b0625501ad13015501ad2bfc0418%22

**Comment by CatAlan1028** [comment]
![image](https://github.com/railmapgen/rmp/assets/146333201/95a1b8c6-5b7d-4d1a-a61b-4e0a187de0bc)
在图片右下角，你们唯一需要做的就是取色器取色然后复制到“中国铁路样式”中来创建“中国高铁样式”。

**Comment by CatAlan1028** [comment]
这个虽然不是变形图，但是他有专门的图例，应该可以吧？

**Comment by thekingofcity** [comment]
嗨，此图并非使用了贝克的经典设计制作，故不能认为是可以被参考的资料 :)

**Comment by CatAlan1028** [comment]
我想问一下只是采集颜色来制作行不行，另外，你们是在哪个网站上找到的中国普通铁路样式（换句话说，你们认可来自哪些网站的样式呢？
