### ISSUE TITLE
BUG：苏州轨道交通换乘站名字位移偏差

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#465]
![屏幕截图 2023-10-10 113744](https://github.com/railmapgen/rmp/assets/146333201/c055399f-05b5-4f22-9721-95e8c77c600d)
![屏幕截图 2023-10-10 114125](https://github.com/railmapgen/rmp/assets/146333201/156bf89a-4011-4160-8589-6e30a3af6ab1)
如图，图一红色圈出的、图二的所有车站标签均为45度车站和left+middle型名字标签，但是很明显名字标签的位置偏下了，换乘线路越多越明显。
注意，其他的位置组合只要含有45度、135度等斜的度数和middle位置都有可能有相同情况。请检查。

**Comment by thekingofcity** [comment]
嗨，名字标签的位置偏下为预期的情况，不过不应随换乘线路数量变多而变化 :)

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，此问题已在 3.3.26 中被修复 :)

![image](https://github.com/railmapgen/rmp/assets/3353040/4fa4dfc4-2259-4763-92d5-59ff433addc7)
