### ISSUE TITLE
建议增加同站换乘站台

### ISSUE THREAD

**Issue by 5WLAN** [railmapgen/rmp#469]
目前同站换乘站台最多只有3个，目前已有大于三线换乘的枢纽开通了

**Comment by Minwtraft** [comment]
补充：是广州样式换乘站点（其它含线路信息的换乘站均可以添加3个以上换乘站）

**Comment by thekingofcity** [comment]
嗨，目前广州地铁尚未由四线换乘的车站，所以无法参考实际样式实现，在有四线换乘站后，我们将尽快实施 :)

**Comment by wongchito** [comment]
Closed by #564
