### ISSUE TITLE
画廊页面出现404

### ISSUE THREAD

**Issue by rainydew** [railmapgen/rmp#470]
![微信截图_20231016004014](https://github.com/railmapgen/rmp/assets/40389473/c138b6db-ffff-43e9-b539-cd0d48bce58f)

在RMP内，打开捐赠页面，点击幻想作品在画廊中的链接，就会进入上图404的页面

**Comment by rainydew** [comment]
gitlab也会出现拒绝连接

**Comment by thekingofcity** [comment]
嗨，我无法复现这个问题，方便再次验证后报告操作系统浏览器的版本吗？

**Comment by thekingofcity** [comment]
Closed as no response :(
