### ISSUE TITLE
New facility icon 'MTR Airport Express'

### ISSUE THREAD

**Issue by xiao-slm** [railmapgen/rmp#499]
<h1>Suggest adding an icon for the 'MTR Airport Express', like this ↓</h1>

![image](https://github.com/railmapgen/rmp/assets/146796722/3a53e0de-964f-4131-b64c-706911b11a95)

**Comment by 28yfang** [comment]
This is an old version of the MTR map. Is adding this icon still necessary?

**Comment by xiao-slm** [comment]
I think it's okay not to add it.
