### ISSUE TITLE
Fix the text color and bold for MTR stations

### ISSUE THREAD

**Issue by xiao-slm** [railmapgen/rmp#509]
1. The current "MTR station" font has a background, may be different from the official image ( [reference link](https://www.mtr.com.hk/archive/ch/services/routemap.pdf) ）There is an error.|当前的“MTR station”字体有背景，可能与官方图像（[参考链接](https://www.mtr.com.hk/archive/ch/services/routemap.pdf)）存在误差。
#

2.  The font color is slightly different, may be different from the official image ( [reference link](https://www.mtr.com.hk/archive/ch/services/routemap.pdf) ）There is an error.|字体颜色略有不同，可能与官方图像（[参考链接](https://www.mtr.com.hk/archive/ch/services/routemap.pdf)）存在误差。

#

3. English has bold font, may be different from the official image ( [reference link](https://www.mtr.com.hk/archive/ch/services/routemap.pdf) ）There is an error.| 英文有粗体，可能与官方图像（[参考链接](https://www.mtr.com.hk/archive/ch/services/routemap.pdf)）存在误差。
#
Provide photos|提供照片
![image](https://github.com/railmapgen/rmp/assets/146796722/81550365-546f-4e49-b219-85b468ddf728)

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题，除第一点外都已修复并上线，唯第一点由于尖东站名有文字轮廓，所以我们为MTR车站添加了文字轮廓 :)
