### ISSUE TITLE
Fix mtr fonts color

### ISSUE THREAD

**Issue by xiao-slm** [railmapgen/rmp#511]
Unable to change colors for "MTR Chinese" and "MTR English" types
>无法更改“MTR Chinese”和“MTR English”类型颜色

![image](https://github.com/railmapgen/rmp/assets/146796722/60879f28-9b09-47fb-aacc-0cf064cf5f06)

**Comment by thekingofcity** [comment]
Hi, this feature is by design if you use MTR fonts. All the texts in MTR system maps use the same color so I believe there is no need for any changes here :)

**Comment by xiao-slm** [comment]
![image](https://github.com/railmapgen/rmp/assets/146796722/8cea9093-a5c8-4068-9ab1-4096f200d4f3)

**Comment by thekingofcity** [comment]
Hi, thanks for reporting the problem. We do fix them as users should be able to change the color of the text node even if they use the mtr fonts :)
