### ISSUE TITLE
广州样式字体失效

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#513]
![字体-rmp](https://github.com/railmapgen/rmp/assets/137034903/43d3bee5-0073-45f8-9cf9-c9e1cb5a1c2a)
![字体2-rmp](https://github.com/railmapgen/rmp/assets/137034903/f7c0c415-4b91-4191-8294-e40133b7f63a)
如图，以前广州样式站点与线路标识显示的字体为Arial+黑体，现在均显示为微软雅黑

**Comment by thekingofcity** [comment]
嗨，你所指的字体问题是 1. 车站名称中文 2. 车站名称英文 3. 线路编号 4. 车站编号 5. 线路标识数字 6. 线路标识中文 7. 线路标识英文 中的哪一种或哪几种呢？

**Comment by 203IhzElttil** [comment]
> 嗨，你所指的字体问题是 1. 车站名称中文 2. 车站名称英文 3. 线路编号 4. 车站编号 5. 线路标识数字 6. 线路标识中文 7. 线路标识英文 中的哪一种或哪几种呢？

仔细看是3 4 5 6 7

**Comment by thekingofcity** [comment]
嗨，这些位置字体的变化是在预期之中的，这是由于我们统一了与 railmapgen/rmg#580 的实现，现在您在两边看的广州地铁线路编号，车站编号，线路标识应该是一致的 :)
