### ISSUE TITLE
A supplement for Shenzhen Metro Num Line Badge: When two numbers actually represents different parts of the same line.对于深圳地铁数字线路标识的补充：共线时标志。

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#532]
#458 #482 
深圳地铁的2号线与8号线是贯通运营的，也就是说，它们是同一条线的不同部分。
![屏幕截图 2023-12-04 211831](https://github.com/railmapgen/rmp/assets/146333201/a3d78158-8345-4f2c-87a6-f7a7cb36a2b5)
Gangxia North Station style岗厦北车站样式

![屏幕截图 2023-12-04 211854](https://github.com/railmapgen/rmp/assets/146333201/3cbc0e80-eafc-4fc8-91f0-beea322038cb)
Window of the World style世界之窗车站样式

![image](https://github.com/railmapgen/rmp/assets/146333201/3a0bb82e-478a-4e7b-8e37-678778c9165a)
A possible design in RMP   RMP一种可能的设计

**Comment by CatAlan1028** [comment]
你可以看一下B站上这一个UP主实地拍摄的视频。

**Comment by CatAlan1028** [comment]
https://www.bilibili.com/video/BV13X4y1x76P/?spm_id_from=333.337.search-card.all.click&vd_source=b54160bfae8af05f94ead98b7e302753

**Comment by thekingofcity** [comment]
您提交的图片仅证明了其在地铁车站内的导视样式，而非地铁线路图中存在的样式，所以没有理由加入本项目中 :)
