### ISSUE TITLE
Text bold issue in MTR fonts

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp#533]
Refer to #509 @xiao-slm @thekingofcity 
根据港铁线路图，英文站名是使用"Myriad Pro Semibold"，而不是Myriad Pro Bold
可以把字体转成Myriad Pro Light再调校成粗体就可以了，感谢

**Comment by thekingofcity** [comment]
* Use Vegur-Bold to replace Vegur
* Use MyriadPro-Semibold to replace MyriadPro
