### ISSUE TITLE
关于广州地铁风格标识的一些建议 2023.12

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/rmp#544]
**随着广州地铁线路图的更新（已张贴在部分车站，电子版稍后更新），广州地铁风格的标识做出了一些改变，以下是改变内容（以及早已存在的而在绘制器中未实现的部分内容），希望线路图绘制器能修改。**
1.广州地铁数字线路标识：大数字+双行中英文，具体样式如图。
2.广州地铁文字线路标识：该样式早已存在于广州地铁线路图中，为双行中英文，文字大小不改变，标识色块大小随文字长度改变，由于该标识多为有轨电车，所以添加时需要一并增加有轨电车样式（缩放大小），具体样式如图。
3.广州有轨电车换乘站标识：广州（黄埔）有轨电车第一座换乘站诞生，样式与广州地铁普通换乘站形状无区别，只需在已有广州地铁换乘站标识中添加有轨电车样式（缩放大小）功能即可实现，具体样式如图。
4.广州地铁线路出现非45度、90度线，建议重新添加普通直线，具体样式如图。
5.广州地铁未开通站点站名颜色：由红色改为黑色，具体样式如图。
6.广州地铁出站换乘线颜色：是灰色（86,86,86）而非黑色。
7.海珠有轨1号线站点标识：实心椭圆，具体样式如图。
![香雪](https://github.com/railmapgen/rmp/assets/108232422/ca6b936e-001b-46fa-8a17-ac4f40e75125)
![水西](https://github.com/railmapgen/rmp/assets/108232422/11cf25f2-842f-4dd6-b515-a511c75d92e9)
![洪圣沙](https://github.com/railmapgen/rmp/assets/108232422/2cdd0505-b77e-477f-b32b-bf9e0baf2874)

**Comment by hackerfyl** [comment]
虽然画的比较难看，但是这就是广州地铁官方的最新线网图了。（上面的图片拍摄于广州地铁江南西站，A出口江南西街区图旁）

**Comment by thekingofcity** [comment]
嗨，我们的确注意到了广州地铁线路图的一些更新，感谢您进行整理，现逐一回复如下：

1. 由于此线路标识并非在本项目中实现，故无法立马更新，需等待 的进展。
2. 同上，需等待 更新后才能在本项目中缩放。
3. 仅需要缩放，会稍后添加。
4. 非45度、90度线是由于作图存在问题，而非全盘否定，故不认可为本项目所需添加的功能。特别地，对于广州地铁出站换乘样式，无需任何修改即可使用简单线段类型，故问题不存在。
5. 仅需要修改颜色，会稍后更改。
6. 仅需要修改颜色，会稍后更改。
7. 仅需要添加一新类型，会稍后更改。

以上

**Comment by hackerfyl** [comment]
自动回复：已收到！

**Comment by thekingofcity** [comment]
嗨，感谢等待，除了第四点以外已经全部新增或修复，欢迎使用3.4.9版本体验 :)
