### ISSUE TITLE
Where is my file?使用macOS离线客户端导出的文件在哪

### ISSUE THREAD

**Issue by Xia05hen** [railmapgen/rmp#547]
我使用macOS客户端上的rmp，但是点导出图片或导出项目都没有用，也找不到文件在哪，谁能提供一下解决方法

**Comment by thekingofcity** [comment]
嗨，这是一个已知的问题，请见 railmapgen/railmapgen.github.io#40，我们由于一些原因尚未修复，您可以尝试直接使用浏览器亦或者更换您的操作系统 :)
