### ISSUE TITLE
Big BUG: Wrong OFFSET Display for line drawing重要错误：线段偏移出错

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#574]
如图，下面是1月1日版本的显示。
![屏幕截图 2024-01-01 152720](https://github.com/railmapgen/rmp/assets/146333201/0f7a2eb9-ceb5-4558-8591-f26b766fc607)
![屏幕截图 2024-01-01 152709](https://github.com/railmapgen/rmp/assets/146333201/8bf8f228-7b9d-427c-a035-48d9fc45953c)

下面是正常（过去的）版本
![屏幕截图 2024-01-01 152815](https://github.com/railmapgen/rmp/assets/146333201/7286a4cb-1f55-4938-b0bf-11626985f6c7)
![屏幕截图 2024-01-01 152823](https://github.com/railmapgen/rmp/assets/146333201/fe62a2cd-e9b5-448e-b8e4-2be04f3fe788)

**Comment by CatAlan1028** [comment]
第一张线段直接消失，检查后发现叠在浅橙色线下方；第二张则偏移错误。

**Comment by CatAlan1028** [comment]
![image](https://github.com/railmapgen/rmp/assets/146333201/a8bef858-41e3-4faf-9a1a-e7a2bec36256)
![image](https://github.com/railmapgen/rmp/assets/146333201/8af1f920-0913-4b94-9de1-2b443c45db9a)

**Comment by CatAlan1028** [comment]
总结起来就是这个bug几乎毁掉了整个地图

**Comment by 28yfang** [comment]
这是最近新出的高级自动基本线段引出的问题，把受影响的车站稍微移动一下就行了

**Comment by thekingofcity** [comment]
嗨，高级自动基本线段会尝试车站为圆心以偏移数值为半径的点是否构成一个合适的基本线段。如果可以，便会自动使用基本线段，正如如上所回复的，您可以稍微移动一下受影响的车站 :)

**Comment by CatAlan1028** [comment]
后来检查了一下，将偏移多设置0.01就行了
