### ISSUE TITLE
Enhancement 关于引入更多字体的建议

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#575]
深圳地铁的RMG字体种类极多，从隶书到行书都有
同时为了选择多样化，建议在RMG、RMP的一些与文字有关的地方可以考虑引入更多字体。
比如可以考虑在电脑版引入“使用系统字体”功能

**Comment by thekingofcity** [comment]
嗨，是否使用系统字体为浏览器实现的功能，项目无权干涉。最多仅能建议浏览器使用何种字体，具体使用的字体由浏览器决定。另外，不同字体有不同的授权形式，并可能需要额外费用。在指出某一风格文字具体使用哪一个字体及其授权形式之前，我们不会考虑任何一种额外字体。
