### ISSUE TITLE
请求开放画直线的能力

### ISSUE THREAD

**Issue by 5WLAN** [railmapgen/rmp#596]
因为在某些地方确实需要用到直线连接，比如在站台经度与纬度差别不大的情况下，或者是在设计图上站台与站台间是用直线连接的；在这些情况下没必要用其他线段连接，这样会感觉更加冗杂且不够美观。请求开放画直线的能力

**Comment by thekingofcity** [comment]
嗨，方便用图片说明

> 站台经度与纬度差别不大的情况下

和

> 站台与站台间是用直线连接的

这两种情况现在的截图吗？

**Comment by CatAlan1028** [comment]
我觉得这个问题可能指的是说两个站台处于接近45度（或135度）的相对位置，但是并不是严格的45度或135度，而这个时候直接使用简单路径会方便得多。实际上，深圳地铁车厢内部的线网图由于大小原因，比如说3号线的布吉-大运、大运-双龙两组车站区段在绘制时均使用了简单直线，虽然车站的线网图画的是45度，但是车厢内部不是，而且在大运站能够看出明显的转角

**Comment by thekingofcity** [comment]
> 我觉得这个问题可能指的是说两个站台处于接近45度（或135度）的相对位置，但是并不是严格的45度或135度，而这个时候直接使用简单路径会方便得多。实际上，深圳地铁车厢内部的线网图由于大小原因，比如说3号线的布吉-大运、大运-双龙两组车站区段在绘制时均使用了简单直线，虽然车站的线网图画的是45度，但是车厢内部不是，而且在大运站能够看出明显的转角

嗨，这被认为是官方没有能力遵守一些约定俗成案例不成熟的表现，希望您能理解
