### ISSUE TITLE
Firefox浏览器在点击任意一个车站时会崩溃

### ISSUE THREAD

**Issue by GitLxsr** [railmapgen/rmp#598]
复现流程：
重新安装火狐浏览器，打开网页：
![image](https://github.com/railmapgen/rmp/assets/155955768/1869573c-9451-454d-a856-317912b97260)
此时页面一片空白，往地图上随机添加一个车站或点击已有专案任意一个车站后：
![image](https://github.com/railmapgen/rmp/assets/155955768/b6a2a547-2354-44b9-b726-0351e339f3e3)

以下是详细资讯：
SyntaxError: \ at end of pattern

zn@https://railmapgen.github.io/rmp/assets/stations-lr-Xfcv0.js:1:29513
Ne@https://railmapgen.github.io/rmp/assets/details-hPf_KPZm.js:1:8403
div
tp/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:6180
Ns/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:133458
div
Ap@https://railmapgen.github.io/rmp/assets/index-umCha4IO.js:1:159421
div
tp/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:6180
Ns/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:133458
aD<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:309418
section
tp/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:6180
Ns/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:133458
aD<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:309418
Ep@https://railmapgen.github.io/rmp/assets/index-umCha4IO.js:1:158847
Oe@https://railmapgen.github.io/rmp/assets/details-hPf_KPZm.js:1:9838
div
tp/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:6180
Ns/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:133458
aD<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:309418
e@https://railmapgen.github.io/rmp/assets/index-umCha4IO.js:1:149344
Suspense
div
tp/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:6180
Ns/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:133458
aD<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:309418
Fl@https://railmapgen.github.io/rmp/assets/index-umCha4IO.js:1:156890
gu@https://railmapgen.github.io/rmp/assets/index-umCha4IO.js:1:168049
Lp@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:134836
ip@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:17671
d0@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:6400
J_@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:134151
rT@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:135401
L2/<@https://railmapgen.github.io/rmp/assets/chakra-eFP61t3-.js:16:248508
pu@https://railmapgen.github.io/rmp/assets/index-umCha4IO.js:1:167954
Fd@https://railmapgen.github.io/rmp/assets/index-umCha4IO.js:1:246505
Vm@https://railmapgen.github.io/rmp/assets/react-82wqd3vf.js:25:142576
Hh@https://railmapgen.github.io/rmp/assets/react-82wqd3vf.js:33:2772

**Comment by thekingofcity** [comment]
嗨，重装后打开网页后应该会有上海地铁的作品，我看到截图中并没有，是做过别的操作了吗？请复述完整的复现步骤 :)

**Comment by GitLxsr** [comment]
您好，详细的复现流程在下：
使用访客模式打开rmp页面：
![image](https://github.com/railmapgen/rmp/assets/155955768/6f3cfd23-7ea2-476e-9daf-c16060cd7460)
点击任意一个站点便会崩溃：
![image](https://github.com/railmapgen/rmp/assets/155955768/8f87ec2b-cc0c-46ec-9387-31a298060e28)
经过本人测试，新建站点也会导致崩溃。

**Comment by thekingofcity** [comment]
嗨，在windows的115.6.0esr版本上我无法复现此问题，很抱歉无法提供任何解决方案 :(

**Comment by GitLxsr** [comment]
您好，我将浏览器更新至121.0.1：
![image](https://github.com/railmapgen/rmp/assets/155955768/f19cfbb1-2837-4acf-8a71-9e0c80c2de93)
仍然会出现以下错误。
电脑系统是Windows 11。

**Comment by wongchito** [comment]
Hi @GitLxsr ,

閣下是否有嘗試重設應用程式？

**Comment by thekingofcity** [comment]
嗨，我已经Firefox更新至 121.0.1 仍然无法复现 :)

![image](https://github.com/railmapgen/rmp/assets/3353040/57dbdb40-84ec-4815-9c4e-045060daa8d8)

**Comment by thekingofcity** [comment]
> Hi @GitLxsr ,
> 
> 閣下是否有嘗試重設應用程式？

@wongchito 我理解访客模式即为没有任何历史数据的环境？

**Comment by wongchito** [comment]
> > Hi @GitLxsr ,
> 
> > 
> 
> > 閣下是否有嘗試重設應用程式？
> 
> 
> 
> @wongchito 我理解访客模式即为没有任何历史数据的环境？
> 

忽略了這點
