### ISSUE TITLE
Edge浏览器显示侧边栏会少一截

### ISSUE THREAD

**Issue by GitLxsr** [railmapgen/rmp#599]
![image](https://github.com/railmapgen/rmp/assets/155955768/d327e042-350e-4e9e-9951-efdb0b89621e)
明显可以看到，侧边栏的图案并没有完全显示，右侧少了一部分没有显示。
使用Edge浏览器120.0.2210.121版本，最新版。

**Comment by langonginc** [comment]
我这边 `121.0.2277.4` 没问题，您那边是什么系统？

**Comment by thekingofcity** [comment]
嗨，您可以尝试以访客方式使用edge后再报告问题是否存在 :)

**Comment by GitLxsr** [comment]
系统为Windows11系统，Edge版本如下：
![image](https://github.com/railmapgen/rmp/assets/155955768/fccef1d2-8bf5-4ac4-960a-999ff57e6ee2)
使用访客模式打开也会产生错误：
![image](https://github.com/railmapgen/rmp/assets/155955768/1bb7c9da-741a-449d-8915-1ce2adcd6766)

**Comment by thekingofcity** [comment]
嗨，即使使用与您一样的版本，我仍然无法复现此问题。猜测是圆角页面造成的代码坐标与实际坐标造成的微小偏移。如果可以的话建议使用现代浏览器如Chrome或Firefox :)
