### ISSUE TITLE
使用Edge浏览器导出图片及编辑时，广州地铁站点编号字体发生改变

### ISSUE THREAD

**Issue by GitLxsr** [railmapgen/rmp#600]
这张是使用Edge浏览器导出的图片：
![image](https://github.com/railmapgen/rmp/assets/155955768/b9d3f3f1-2880-40b3-8463-2ae524ea4800)
这是预览图：
![image](https://github.com/railmapgen/rmp/assets/155955768/3432f7da-2e89-47ab-9f16-c759a4b553db)
可以看到，无论是预览图还是导出的图片，都没有正确显示广州地铁所使用的字体。
使用FireFox浏览器导出的图片，可以显示正确字体：
![image](https://github.com/railmapgen/rmp/assets/155955768/eb09c1af-5637-4b63-8a32-b84a6db3ae58)

**Comment by thekingofcity** [comment]
嗨，对于广州地铁车站，并未提供任何额外字体，全部使用的是您操作系统中的字体。firefox显示正常已表明您操作系统中存在正确的字体，那么请您检查有问题浏览器的字体设置。这并非是核心贡献者可以解决的问题 :)
