### ISSUE TITLE
希望可以提供使用广州地铁旧版线路标识的选项

### ISSUE THREAD

**Issue by GitLxsr** [railmapgen/rmp#602]
如题，旧版的线路标识使用较长时间，希望可以仿照上海的方案，在线路标题上上线广州地铁线路标识(2022)的选项，供有需要的人使用。

**Comment by thekingofcity** [comment]
嗨，广州地铁线路标识引用了来自 railmapgen/svg-assets 的资源，我们需要其的更新才能考虑是否在本项目中实现，请参考 railmapgen/svg-assets#2

**Comment by thekingofcity** [comment]
嗨，railmapgen/svg-assets 允许使用老版本的广州地铁线路标识，那么便无任何依赖阻止我们实现。我们将在之后提供此支持 :)

**Comment by langonginc** [comment]
Hi，感谢您的建议，您提到的这个功能已经上线，欢迎体验 😄

**Comment by wongchito** [comment]
@GitLxsr 此為官方設計

![image](https://github.com/railmapgen/rmp/assets/9390786/cd60759a-5f78-443c-b32e-6e9d49cd05a0)

**Comment by thekingofcity** [comment]
@GitLxsr 

> 但官方设计貌似是居中处理？
> 实际到线路板就是各种都有，有数字放大/不放大的，有英文居左居中居右的……

这种情况下我们会实现至少一种情况，再视精力与重要程度支持更多。目前看来这里并不需要各种细微对其区别的实现 :)

**Comment by GitLxsr** [comment]
> @GitLxsr
> 
> > 但官方设计貌似是居中处理？
> > 实际到线路板就是各种都有，有数字放大/不放大的，有英文居左居中居右的……
> 
> 这种情况下我们会实现至少一种情况，再视精力与重要程度支持更多。目前看来这里并不需要各种细微对其区别的实现 :)

感谢回复。我并不是想要这么多的自定义样式，相反，我的意思是广州地铁在线下物料方面做不到统一的标准。而以官方线路图为标准的话，“号线”两个字会在数字的纵向的中央而不是偏上的位置，拿线下物料的实拍图来佐证“号线”二字偏上，我觉得理由不太充分而已。

**Comment by wongchito** [comment]
Hi @GitLxsr ,

自RMG設計之初，我們以復刻車站內張貼的路線圖為目標，因該版設計最為大眾所認識及接受，故所有對齊或其他設計均以線下為準。

而RMP由於工作量龐大的原因，重覆使用了RMG的素材，以便統一設計標準及減少開發工作量。同時，我亦相信 @thekingofcity 在製作廣州風格時，充分地走訪了廣佛各車站收集素材，因而設計亦以線下為準。（如有錯誤請更正 @thekingofcity ）

再者，廣州地鐵已更換設計，因此，除非有更加合理的理由，我們不會再對舊版本風格作出任何變更。


感謝閣下的查詢！
