### ISSUE TITLE
丰富JR东日本车站样式选项

### ISSUE THREAD

**Issue by harry-xi** [railmapgen/rmp#604]
![image](https://github.com/railmapgen/rmp/assets/79187160/7815599d-6620-4f29-b871-82e0ffd17968)
首先，这里有一个我遇到的问题，如图，这四个方位选项均无法避免站名与线路重和。请提供左上、左下、右上、右下四个方位。
另外观察JR东日本官方线路图，发现其中有大量使用倾斜站名。希望RMP能够支持。
![image](https://github.com/railmapgen/rmp/assets/79187160/d591343b-4b82-44ba-b54b-eb7e7d7867f1)

**Comment by harry-xi** [comment]
#571 抱歉未注意到该issues

**Comment by harry-xi** [comment]
#571
抱歉未注意到该已有issues

**Comment by thekingofcity** [comment]
嗨，第一个问题您已找到正确的议题，这确实重复了。关于第二个问题，您附上的图片并非实现时所参考的图片，所以不会提供仅有英语的车站版本。不过就实现所参考的图片来说，确实有英文名倾斜的情况。这是会实现的内容，不过目前优先级不高 :)

https://www.jreast.co.jp/map/pdf/map_tokyo.pdf
