### ISSUE TITLE
使用平板不能放置線

### ISSUE THREAD

**Issue by 22KaiYu** [railmapgen/rmp#608]
問題：使用地鐵路線圖繪製器，不能放置線，只能放置站

**Comment by langonginc** [comment]
您好，请问您使用的是什么设备、什么浏览器、哪个版本的rmp程序？

> 例如： `iPad Pro, Safari, 3.4.22`

**Comment by 22KaiYu** [comment]
iPad Pro,safari,3.4.24

**Comment by thekingofcity** [comment]
嗨，ipad os的版本是多少呢？
