### ISSUE TITLE
Sort all elements instead of groups

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#613]
在RMP中，任意文字默认浮于线段上方和车站下方。能否在任意文字的属性里开设一个选项允许它处于线段下方？

**Comment by CatAlan1028** [comment]
![屏幕截图 2024-01-23 184127](https://github.com/railmapgen/rmp/assets/146333201/196d80ca-c5f2-49ec-a06c-3029aab180bc)

**Comment by thekingofcity** [comment]
Also, support the hook before and after layers for some specific elements such as MRT out-of-station interchange line style.

**Comment by CatAlan1028** [comment]
也许可以弄个图层，图层的优先级高于深度。

**Comment by CatAlan1028** [comment]
然后相应地可以选择所有图层叠加的视角和仅当前图层的视角。但是只有被选中的当前1个图层可以被编辑。

**Comment by CatAlan1028** [comment]
这样也许可以解决这个问题。
