### ISSUE TITLE
RMP铁路线段的一个值得商榷的地方

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp#614]
![image](https://github.com/railmapgen/rmp/assets/146333201/c2354344-7261-4d30-92fb-31fdec38c0f9)
如下图，铁路线段正常情况应该是平头（即像北京有轨的标识），即使是端点也一样，但是软件（上面）里做的是圆头，是不是有点问题？
![屏幕截图 2024-01-23 18342522](https://github.com/railmapgen/rmp/assets/146333201/6c7b2be8-08f4-4266-83bd-7db03098ed65)

另外，#460 的高铁样式我又找到一个官方的，这个算不算？

**Comment by CatAlan1028** [comment]
高铁样式见#460

**Comment by 203IhzElttil** [comment]
可以拿一根白线给它盖起来（逃

**Comment by thekingofcity** [comment]
嗨，正如 @52PD 在 #460 的[回复](https://github.com/railmapgen/rmp/issues/460#issuecomment-1907190598)中所提到的，项目中的铁路样式为上海地铁官方线路图中的金山铁路样式。圆头是预期之中的情况，感谢您的理解与支持 :)
