### ISSUE TITLE
下载线路图的站点内容问题

### ISSUE THREAD

**Issue by sansheng12** [railmapgen/rmp#638]
比如下载成都地铁线路图，8号线由北向南第四站原名是“杉板桥”，“Shabanqiao”，但上面是“衫板桥”，“Shanbanqiao”

**Comment by langonginc** [comment]
这看起来是模版中存在错误导致的，您可以点击车站后修改车站名称再下载。

当然了，欢迎您修改并提交到 railmapgen/rmp-gallery 中！
