### ISSUE TITLE
想加个南京地铁的站点、站牌及线路标识

### ISSUE THREAD

**Issue by 3156940656** [railmapgen/rmp#640]
求博主帮忙加一下

**Comment by thekingofcity** [comment]
嗨，您可以打开一个新的议题，附上其所有可能的变化样式，以便在核心贡献者们有余力时进行实现。如果无论如何也想尽快看到它们的话，也欢迎捐赠来提升其优先级 :)

**Comment by 3156940656** [comment]
![南京地铁2024年线路图 webp](https://github.com/railmapgen/rmp/assets/159789737/0632deeb-2b4a-4af0-bb0d-ad1d5d04332e)
![屏幕截图 2024-03-03 140006](https://github.com/railmapgen/rmp/assets/159789737/cc7b45a9-6041-45e6-9525-4431ff16ad5b)
![屏幕截图 2024-03-03 140021](https://github.com/railmapgen/rmp/assets/159789737/b477b5d6-ae66-4df6-938d-fcc7c4b49094)

**Comment by 3156940656** [comment]
换乘站点的变形跟上海的差不多，就差文字线路标识、设施

**Comment by CatAlan1028** [comment]
See #670 .
本议题与#670重复。建议关闭此议题。 @thekingofcity @langonginc
