### ISSUE TITLE
导出的图片中部分文字字体失效

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#647]
当使用 杂项节点-任意文字 时，字体系列设置为港铁中文、港铁英文、柏林 S/U Bahn、新加坡地铁、JR东日本日语或JR东日本英语，导出png图片，**没有勾选**“使用系统字体而不是在画布上预览的字体”，下载下来的图片中，字体显示为系统字体
而当字体系列设置为中文或英文时，没有上述问题

![RMP-字体](https://github.com/railmapgen/rmp/assets/137034903/ffcb27d5-1e32-4f48-a4b2-edbf39efb3c0)
RMP编辑界面中输入的字体

![RMP_1707883016328](https://github.com/railmapgen/rmp/assets/137034903/d38da208-3f91-4eb5-806e-6508b07c9a1e)
RMP导出png图片后的字体

**Comment by wongchito** [comment]
Hi @Minwtraft ,

感謝閣下回報問題。經測試證實，當特定字型只在文字節點出現時，字型下載會失效；而若同時存在對應的車站節點，字型便能如常下載。我們將儘快修復該問題。

<img width="1215" alt="image" src="https://github.com/railmapgen/rmp/assets/9390786/22d0e3e8-ecb5-42f0-999c-8c33d35b940a">

**Comment by wongchito** [comment]
@thekingofcity -- `MiscNodeType.Text` 並未在 `FONT_CSS` 中指定字型

<img width="863" alt="image" src="https://github.com/railmapgen/rmp/assets/9390786/477ae38a-bba1-4aa6-b631-7416f9e13824">

**Comment by wongchito** [comment]
Refer to #601

**Comment by thekingofcity** [comment]
Fixed in #601
