### ISSUE TITLE
Qingdao Metro station

### ISSUE THREAD

**Issue by zzk-zswz** [railmapgen/rmp#649]
![image](https://github.com/railmapgen/rmp/assets/152062424/98d89017-f455-47a4-b359-5566738708d6)
线路标识
![image](https://github.com/railmapgen/rmp/assets/152062424/2e38bf6b-81e5-4bd5-a6b5-afb3bfcaf7b2)
普通站与换乘站
![image](https://github.com/railmapgen/rmp/assets/152062424/5b2de246-140c-4cf1-9b3f-ec1e650188f9)
![image](https://github.com/railmapgen/rmp/assets/152062424/51f962f5-64f4-4b61-9d07-0ad2476d1188)
设施
PS：有钱一定捐赠

**Comment by langonginc** [comment]
感谢您的建议，青岛地铁车站、青岛地铁数字线路标识正在开发。但由于开发团队精力有限，青岛地铁设施部分可能会被推迟，您可以通过绘制设施的 SVG 图像，来提高设施的优先级，希望您能理解～

**Comment by langonginc** [comment]
Separate facilities to #667

**Comment by zzk-zswz** [comment]
> 感谢您的建议，青岛地铁车站、青岛地铁数字线路标识正在开发。但由于开发团队精力有限，青岛地铁设施部分可能会被推迟，您可以通过绘制设施的 SVG 图像，来提高设施的优先级，希望您能理解～感谢您的建议，青岛地铁车站、青岛地铁数字线路标识正在开发。但由于开发团队精力有限，青岛地铁设施部分可能会被推迟，您可以通过绘制设施的 SVG 图像，来提高设施的优先级，希望您能理解～

谢谢增加，正在尝试绘制SVG

**Comment by zzk-zswz** [comment]
#667
已经提交Qingdao Airport和Qingdao MTR

**Comment by 3156940656** [comment]
一定要用青岛地铁线路标识的指定字体

**Comment by langonginc** [comment]
感谢您的贡献，青岛车站已经上线，版本号3.5.20，欢迎体验～

**Comment by zzk-zswz** [comment]
没想到速度这么快 😊👍

________________________________
发件人: 5+1 ***@***.***>
发送时间: 2024年3月9日 14:57
收件人: railmapgen/rmp ***@***.***>
抄送: zzk-zswz ***@***.***>; Author ***@***.***>
主题: Re: [railmapgen/rmp] Qingdao Metro station (Issue #649)


感谢您的贡献，青岛车站已经上线，版本号3.5.20，欢迎体验～

**Comment by zzk-zswz** [comment]
需要重启一下本帖，青岛地铁于近日更新了线路图，上新了文字线路标识，如图
![image](https://github.com/railmapgen/rmp/assets/152062424/7e3c9cb7-b8b4-4b8b-a786-1f246ee1306b)

**Comment by thekingofcity** [comment]
嗨，这种情况请在新议题中讨论，此议题已被解决 :)
