### ISSUE TITLE
London Underground stations

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmp#658]
https://content.tfl.gov.uk/standard-tube-map.pdf
https://content.tfl.gov.uk/tfl-line-diagram-standard.pdf

https://tfl.gov.uk/maps/track
https://content.tfl.gov.uk/standard-tube-map.pdf
https://tfl.gov.uk/cdn/static/cms/images/london-rail-and-tube-services-map.gif

**Comment by thekingofcity** [comment]
London Tube internal interchange line style requires #613

**Comment by aaronyz2007** [comment]
tube车站换乘标识有一点小问题，如下所示：
1）通道换乘标识与伦敦原版不同（见p1 p2）
2）原版出站换乘线条较细且两端均有空白（见p3 p4）
![image](https://github.com/railmapgen/rmp/assets/120014893/2d6a8772-adb4-44e3-8536-11ef1e91230c)
![image](https://github.com/railmapgen/rmp/assets/120014893/ce9ff9cb-83fb-4cd6-b638-664edee3e981)
![image](https://github.com/railmapgen/rmp/assets/120014893/d6b0a5ff-630c-4e4f-a46c-6d7016d41bee)
![image](https://github.com/railmapgen/rmp/assets/120014893/a4166c16-447b-4d37-bab0-8b2e8f20d25b)

**Comment by aaronyz2007** [comment]
![image](https://github.com/railmapgen/rmp/assets/120014893/47d00915-1da8-479b-bb71-a97903b0ba58)
![image](https://github.com/railmapgen/rmp/assets/120014893/dd951c53-5bd7-4ada-b862-fd961ced45e1)
有发现两个小问题
1. 有无障碍设施车站图标比原版略小，大小应与普通换乘站图标大小一致
2. 站名行间距比原版略小，如king's cross & st pancras intl站所示
btw有个小请求，能否允许中国铁路样式更改颜色，jr东日本新干线及伦敦thameslink、tfl rail均有类似表示方式，但后三者通常不是黑色（如图2中thameslink的灰粉色）
