### ISSUE TITLE
Other transport modes and landmark signs of Singapore MRT map

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmp#661]
![Singapore Flyer](https://github.com/railmapgen/rmp/assets/92020676/ed71e56c-53fb-4965-a0e2-ea59d41acaaa)
![airport](https://github.com/railmapgen/rmp/assets/92020676/afd78cb5-17ee-489d-8131-b12c85ad75f8)
![bus interchange](https://github.com/railmapgen/rmp/assets/92020676/66deda03-26b2-4588-86f2-ae8177a4992f)
![cable car](https://github.com/railmapgen/rmp/assets/92020676/869aa56d-3ba6-4855-ae0e-3fb7eef1c668)
![cruise centre](https://github.com/railmapgen/rmp/assets/92020676/2c53d648-fbcc-47d1-9ec6-aa57d1332d52)
![Esplanade](https://github.com/railmapgen/rmp/assets/92020676/6c4f983e-5433-4a35-8447-716802c3f841)
![Gardens by the Bay](https://github.com/railmapgen/rmp/assets/92020676/1625600b-c409-4113-97e5-4ea361279c8c)
![Marina Bay Sands](https://github.com/railmapgen/rmp/assets/92020676/56564257-07f7-465c-b8f5-4655ad006ddd)
![Merlion](https://github.com/railmapgen/rmp/assets/92020676/c9480611-00c8-4f21-a398-3f470a36b260)
![sentosa express](https://github.com/railmapgen/rmp/assets/92020676/eecbe3e1-bfe1-4d17-a981-3c6d4b89edaa)

**Comment by langonginc** [comment]
感谢您的贡献，已经合并上线3.5.25，欢迎体验～
