### ISSUE TITLE
建议添加東京メトロ的地铁标识

### ISSUE THREAD

**Issue by Ikun09042113** [railmapgen/rmp#666]
1 普通车站，无换乘：上方线路标识字母，下方站点标识数字
图片以京橋为例
![屏幕截图 2024-02-25 100729](https://github.com/railmapgen/rmp/assets/134774491/5be5d828-80b3-4680-b599-4fa4e09b6243)
2 普通车站，与其他铁路系统换乘/自己换自己的车站：同1，但周围有灰色框
图片以東京为例
![屏幕截图 2024-02-25 101000](https://github.com/railmapgen/rmp/assets/134774491/1f39502b-536a-4961-9f77-fc43b0f5a7ac)
3 换乘车站，同站换乘：横向/纵向排列的普通车站组合
图片以渋谷为例
![屏幕截图 2024-02-25 101143](https://github.com/railmapgen/rmp/assets/134774491/3c58782a-033f-4c21-aebb-346682e8f90a)
4 换乘车站，不同名站：两个车站间用灰色线条连接
图片以春日/後樂園为例
![屏幕截图 2024-02-25 101353](https://github.com/railmapgen/rmp/assets/134774491/4539ed46-8043-485f-86af-9c0444e12971)
5 重点车站，站名用大字号表示（参考渋谷　東京　新宿）

**Comment by 3156940656** [comment]
这个主意挺好的
建议博主把东京metro地铁的标识加到RMP上

**Comment by CatAlan1028** [comment]
https://www.tokyometro.jp/cn/subwaymap/index.html

**Comment by LittleLing03** [comment]
东京的样式不止一种吧

**Comment by Ikun09042113** [comment]
是的 这里主要搞的是地铁的 JR 小田急 京王等等还不算
________________________________
发件人: Little Ling ***@***.***>
发送时间: 2024年3月10日 13:02
收件人: railmapgen/rmp ***@***.***>
抄送: Ikun09042113 ***@***.***>; Author ***@***.***>
主题: Re: [railmapgen/rmp] 建议添加|京メトロ的地铁标识 (Issue #666)


东京的样式不止一种吧

―

**Comment by LittleLing03** [comment]
@Ikun09042113 是指这些：
https://www.[tokyometro.jp/lang_cn/station/202303_number_cn.pdf](https://www.tokyometro.jp/lang_cn/station/202303_number_cn.pdf)
https://www.[tokyometro.jp/station/202303_shisetsu_ja.pdf](https://www.tokyometro.jp/station/202303_shisetsu_ja.pdf)
https://www.tokyometro.jp/station/202303_kani_ja.pdf
等等

**Comment by LittleLing03** [comment]
https://www.tokyometro.jp/station/202303_kani_ja.pdf
https://www.kotsu.metro.tokyo.jp/subway/line.pdf

**Comment by Ikun09042113** [comment]
这个是日语版的吧 应该是只有站名标识
________________________________
发件人: Little Ling ***@***.***>
发送时间: 2024年3月22日 18:07
收件人: railmapgen/rmp ***@***.***>
抄送: Ikun09042113 ***@***.***>; Mention ***@***.***>
主题: Re: [railmapgen/rmp] 建议添加|京メトロ的地铁标识 (Issue #666)


https://www.tokyometro.jp/station/202303_kani_ja.pdf
https://www.kotsu.metro.tokyo.jp/subway/line.pdf

―

**Comment by thekingofcity** [comment]
https://www.tokyometro.jp/station/202303_number_ja.pdf

**Comment by thekingofcity** [comment]
普通车站，换乘车站 (不包括不同站名换乘车站和重点车站)
