### ISSUE TITLE
Qingdao Metro facilities

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp#667]
<img width="135" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/06946dab-00c9-440e-96fd-ed9148d4961d">

Refer to #649 , mentioned by @zzk-zswz .

Qingdao Metro route map: http://www.qd-metro.com/static/images/qddtxlt.png

**Comment by zzk-zswz** [comment]
![RMP杂项节点_设施_青岛_铁路 QD-MTR](https://github.com/railmapgen/rmp/assets/152062424/f73c8b2d-538a-4628-b911-6d71cdbfc1a8)

**Comment by zzk-zswz** [comment]
望审核

**Comment by zzk-zswz** [comment]
铁路已经做好了

**Comment by Minwtraft** [comment]
基本车站及补充 #669
望审核

**Comment by zzk-zswz** [comment]
> 基本车站及补充 [#669 #669](https://github.com/railmapgen/rmp/issues/669) 望审核 

你的应该在#649上发布

**Comment by Minwtraft** [comment]
2024线网图的铁路和机场设施（svg格式）
![Railway_Qingdao-24 5 5](https://github.com/railmapgen/rmp/assets/137034903/50fdbac9-a8c0-4b3f-b8c4-ede4d13838cb)
![Airport_Qingdao-24 5 5](https://github.com/railmapgen/rmp/assets/137034903/79d81cac-2942-43b7-92f0-b3a33938c16f)
因为官网线网图里青岛北站的火车站标识没有遮挡海域颜色，所以制作svg时均没有填充白色
其他的不会做……
原图在这里（把青岛地铁app上线网图放到最大后截的图）：
![设施2](https://github.com/railmapgen/rmp/assets/137034903/98df3752-e2f7-48ca-9709-ccb7c1788b44)

**制作方面的建议与注意事项**
我个人在制作前两种设施时是先将原图导入至Ai（导入后图片长宽应调整为与原有长宽一致），在原图上描线制作，通过更改透明度判断是否对齐，制作完成后再缩放至适合RMP的大小，这样比“临帖”式的制作更精准，并且可以保证大小与精度和上述设施一致
数据方面，圆角矩形边长10.47 px，描边0.35 px，弧线边角2.18 px
需要注意的是，原图作图不规范，存在颜色不统一以及线条不平行等问题，制作时应进行更正。
颜色不统一：出现了#000000（纯黑）和#342c2a（灰黑）两种，考虑到官网线网图使用的均为后者（#342c2a）（邮轮港标识内部仍使用#000000，制作时应予以修复），制作时应统一使用#342c2a
有轨电车（最右侧）标识比其他标识小（经证实不是放大倍数问题），不过不影响缩放，可以忽略这一问题

**Comment by langonginc** [comment]
Hi @Minwtraft , 我们已经收到了您前两种设施的 SVG 图像，想问您一下，其他三个您近期考虑继续制作吗？如果您近期一同完成的话我们考虑这五个设施一起汇入，或者也可以这两个先汇入，保留本议题，直到剩下的被完成。感谢您的贡献与支持

**Comment by Minwtraft** [comment]
@langonginc 您好！请先汇入这两个设施吧，其他三个我不知道怎么做，近期完不成了，抱歉

**Comment by zzk-zswz** [comment]
![MTRQDBUS](https://github.com/railmapgen/rmp/assets/152062424/d3af4944-5eaf-440e-a9e5-8743a4e9a259)
需要裁剪

**Comment by Minwtraft** [comment]
汽车站标识，缩放与修复：
![Coach_Qingdao-24 5 5](https://github.com/railmapgen/rmp/assets/137034903/f91aeda4-77f1-4489-8a6d-3f4631032bf0)

**Comment by langonginc** [comment]
感谢二位的努力，我们将会尽快加入到rmp中～

**Comment by Minwtraft** [comment]
自己重新做了一遍汽车站标识，以及邮轮港和有轨电车的，现在青岛的设施标识已经齐全了
均不填充白色背景
汽车站（Coach Station）：
![Coach_Qingdao-24 6 23](https://github.com/railmapgen/rmp/assets/137034903/a4bf9dfe-fe65-4029-b54b-822967cdd293)

邮轮港（Cruise Terminal）：
![Cruise_Terminal_Qingdao-24 6 23](https://github.com/railmapgen/rmp/assets/137034903/7a4378c2-5ed0-4ab3-a5c2-5398ea4c197a)

有轨电车（T
![Tram_Qingdao-24 6 23](https://github.com/railmapgen/rmp/assets/137034903/3c8d2437-beee-4f42-8bb8-0a4b534a41d6)
ram）：

**Comment by langonginc** [comment]
感谢各位的付出，青岛设施将加入到5.0版本，请您等待5.0版本的正式发布～
