### ISSUE TITLE
建议优化下移动端（手机,平板）地铁线路绘制

### ISSUE THREAD

**Issue by lingmofengling** [railmapgen/rmp#673]
https://github.com/railmapgen/rmp/assets/162086921/b3eea62c-2a6c-4ddf-ab66-07cc39801ab9

移动端制作线路图划屏幕滑不过来，点旁边的选项还会报错，建议优化一下

**Comment by 28yfang** [comment]
您好，请**使用正式环境**重新尝试一次：https://railmapgen.github.io/?app=rmp

**Comment by lingmofengling** [comment]
https://github.com/railmapgen/rmp/assets/162086921/7bbba8d1-b39f-48c0-8238-e7267b478eaa
> 您好，请**使用正式环境**重新尝试一次：https://railmapgen.github.io/?app=rmp
正式版也是一样，希望能优化一下移动端（手机，平板）的线路地铁线路绘制器功能，不然就电脑能用移动设备用不了

**Comment by 28yfang** [comment]
您好，我并不能复现您的问题？

**Comment by lingmofengling** [comment]
> 您好，我并不能复现您的问题。

It is recommended to optimize the metro line drawing of mobile terminal (mobile phone, tablet)

Uploading Screenrecording_20240306_100022.mp4…

**Comment by thekingofcity** [comment]
> > 您好，我并不能复现您的问题。
> 
> It is recommended to optimize the metro line drawing of mobile terminal (mobile phone, tablet)
> 
> Uploading Screenrecording_20240306_100022.mp4…

Hi, @lingmofengling Please wait until __Uploading__ disappeared and then comment :)

**Comment by langonginc** [comment]
我在我的iPhone上不能复现上面的问题。

**Comment by lingmofengling** [comment]
希望能尽快改进一下安卓移动端的地铁线路绘制，谢谢

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by langonginc** [comment]
**No move and up event**

`onPointerMove`, `onPointerUp` can only be called when running in desktop. We should listen `onTouchMove` and `onTouchEnd` to deal with the mobile.

**App crash**

`onPointerUp` cannot be called when running on a mobile phone, so the `active` is still set to `background`. When `mode` was set to `line_*`, `getNodeAttributes('background')` is called to drawthe line whose id=`create_in_progress___no_use`.

**Comment by lingmofengling** [comment]
话说安卓移动端画线还是画不了，能解决吗

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by langonginc** [comment]
我们正在处理这个问题，请您耐心等待～

**Comment by lingmofengling** [comment]
安卓移动端的线路图绘制优化还没弄好吗

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lingmofengling** [comment]
抱歉，我才发现已经优化完了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lingmofengling** [comment]
但是自己设的站点没办法画线了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lingmofengling** [comment]
以后会不会尝试给线路绘制器网站出个安卓会iOS端的移动应用程序呢？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lingmofengling** [comment]
地铁线路图绘制的时候只有北京地铁才能画线，想用别的车站，能不能处理一下

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by langonginc** [comment]
我们仍在处理这个问题，请您耐心等待～
