### ISSUE TITLE
简单线段解锁失败

### ISSUE THREAD

**Issue by GitLxsr** [railmapgen/rmp#675]
![image](https://github.com/railmapgen/rmp/assets/155955768/54c08eb6-42cd-414d-ab06-9babe1f98a65)
![image](https://github.com/railmapgen/rmp/assets/155955768/905e214d-f228-4e42-b5e9-eabbc6acec9d)
虽然完成了答题，但是简单线段仍不可用。
版本：Edge Version 122.0.2365.66 / Windows 11

**Comment by 3156940656** [comment]
求博主恢复简单线段，谢谢

**Comment by thekingofcity** [comment]
嗨，您可以尝试刷新页面并再次检查是否已经解锁。如仍未解锁，请再次截取第一张截图中的窗口 :)

**Comment by GitLxsr** [comment]
> 嗨，您可以尝试刷新页面并再次检查是否已经解锁。如仍未解锁，请再次截取第一张截图中的窗口 :)

![image](https://github.com/railmapgen/rmp/assets/155955768/be463852-a0c7-4536-9435-6aa8a4daea54)
您好。刷新页面后仍然未解锁，文章仍然可以查看，但无法查看问题，请看图。如果点击Already Unlocked，则会出现Fail的提示，和第一张截图的一样。

**Comment by thekingofcity** [comment]
嗨，抱歉，解锁后确实仍无法切换线段类型到简单线段上，您需要删除后重新从工具栏中选择并连接两个车站 :)

**Comment by Hutk2023** [comment]
我想请问：这是什么模式下可以打开这样的简单样式？麻烦回答下！谢谢开发者！

**Comment by Hutk2023** [comment]
@thekingofcity thekingofcity

**Comment by Hutk2023** [comment]
希望开发者能回复！
