### ISSUE TITLE
Guangdong Intercity line style

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/rmp#682]
### 广东城际属于广州地铁集团管辖，其线网属于广州地铁线网的一部分。广东城际有两个版本的线路图，均为官方线网图。
广东城际发布的线网图：[https://gdcj.gzmtr.com/wxMetro/ccyjxz/xltxz.html](url)
广州地铁发布的线网图：[https://appmsg.gzmtr.cn/DNSFile/Modules/gzmtrmapv241.jpg](url)
### **细节：**
**1.线路样式：深蓝描边，蓝白相间。（两个版本的样式有差别，其中广州地铁样式为等距蓝白相间，广东城际为蓝长白短）**
![image](https://github.com/railmapgen/rmp/assets/108232422/c3974e3b-5457-4bde-9aec-e2fda0f72d1d)
_广州地铁样式_
![image](https://github.com/railmapgen/rmp/assets/108232422/b648645a-5163-4044-ad34-4f2afe5fff57)
_广东城际样式_

**2.普通站点样式（两个版本有略微差别，其中广州地铁样式站点大小较大，描边较细）**
![image](https://github.com/railmapgen/rmp/assets/108232422/db8ab2c0-cf52-4b71-88f2-09d4c4eff4df)
_广州地铁样式_
![image](https://github.com/railmapgen/rmp/assets/108232422/1f94c602-ea69-47a9-98ac-e9b9b52c6c71)
_广东城际样式_

**3.出站换乘站点样式（其中广州地铁样式的与普通站点相同，广东城际站点比普通站点大，出站换乘线路模块的宽度固定，火车站模块单独画出）**
![image](https://github.com/railmapgen/rmp/assets/108232422/f436849d-b680-4455-8103-45b45b82601f)
_广州地铁样式_
![image](https://github.com/railmapgen/rmp/assets/108232422/a0d6f03b-1225-4b3f-9859-5b7c78f0c576)
_广东城际样式_
另外，广东城际样式的第二站名在站名下方。

**4.站内换乘站点样式（两种样式都在出站换乘站点的基础上在中间画一个小圈）**
![image](https://github.com/railmapgen/rmp/assets/108232422/367adf29-c7da-442b-a25a-dd5d057a9807)
_广州地铁样式_
![image](https://github.com/railmapgen/rmp/assets/108232422/af9ffbe3-b406-4806-b993-62abaaf6ae0c)
_广东城际样式_

**5.设施图案（两种样式一致）**
![image](https://github.com/railmapgen/rmp/assets/108232422/fab62f69-da3e-4165-a0bc-e6d194165d9b)
_广州地铁样式_
![image](https://github.com/railmapgen/rmp/assets/108232422/353bf4bc-fd96-4930-8a27-e324e8eba853)
_广东城际样式_

**6.线路标识（两种样式一致）**
![image](https://github.com/railmapgen/rmp/assets/108232422/04a25d89-8d09-4751-a04b-5cc69b4bcd40)
_广州地铁样式_
![image](https://github.com/railmapgen/rmp/assets/108232422/9990e672-866a-44f2-beed-7e6aabebbe29)
_广东城际样式_

**Comment by hackerfyl** [comment]
补充：两种风格的颜色有略微差别

**Comment by Minwtraft** [comment]
有一个问题：
图中广州地铁样式的颜色：RGB(66,84,146)不建议作为参考，因为广州地铁官网发布的线网图整体颜色均有误差（如下图。右上角为官方线网图，颜色整体偏红；其余部分为目前画廊中的广州模板，颜色正确）
![颜色差异](https://github.com/railmapgen/rmp/assets/137034903/5e1808f9-2f0e-4681-9aee-34fc73724fff)

**Comment by hackerfyl** [comment]
自动回复：已收到！

**Comment by thekingofcity** [comment]
![image](https://github.com/user-attachments/assets/da039d0c-ce3c-49ab-8839-ece803e63881)

开发中样式速览 :)

**Comment by hackerfyl** [comment]
自动回复：已收到！

**Comment by thekingofcity** [comment]
[测试环境](https://uat-railmapgen.github.io/?app=rmp)已上线这样的广东城际样式，欢迎体验 :)

![image](https://github.com/user-attachments/assets/f4cad5d0-5573-4657-ba51-d459c3e87640)

**Comment by Minwtraft** [comment]
颜色方面有一个问题：
广州地铁官网最新线网图的颜色存在误差，整体偏红，但其5月份的线网图没有此问题（如图）
![色差](https://github.com/user-attachments/assets/c45f3a95-08eb-4476-949d-46777cfc2cfa)
因此，请问可否以2024年5月的线网图为颜色标准？（此时城际铁路颜色应为：rgb(37, 90, 168) ）
链接：https://cs.gzmtr.com/ckfw/xlu_2020/202409/W020241002000760177182.png

**Comment by thekingofcity** [comment]
嗨，颜色已更新，欢迎继续体验并汇报除翻译之外的问题 :)

**Comment by thekingofcity** [comment]
嗨，还想一并确认广东城际线路标识的中英文字体大小。另外，关于字间距，请换算到svg text的[letter spacing](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing)单位下 :)

**Comment by thekingofcity** [comment]
@Minwtraft

**Comment by Minwtraft** [comment]
> 嗨，还想一并确认广东城际线路标识的中英文字体大小。另外，关于字间距，请换算到svg text的[letter spacing](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing)单位下 :)

您好！城际线路标识的字体大小测算如下：
中文：8.63 pt；
英文：3.54 pt，字间距 0.035em
另外，在测算时注意到四字线路名称（广清城际、广肇城际与广惠城际）有0.1em的字间距，但六字线路名称（广州东环城际）没有。由于六字名称再加上字间距会超出方框，因此个人建议统一不添加字间距

**Comment by thekingofcity** [comment]
嗨，感谢各位提供的详细信息，广东城际已在5.1.9的正式版中上线 :)]
