### ISSUE TITLE
There may be a problem with the answer

### ISSUE THREAD

**Issue by SHENJIE15** [railmapgen/rmp#688]
Unlock the simple path tool, is the answer check wrong? Obviously, the true answer is why it is displayed incorrectly. I believe chat GPT will not lie to me.

**Comment by thekingofcity** [comment]
Hi. It doesn't matter whether the answers are correct or wrong to the fact since what you select should correspond to the article and the question. Chat GPT might not lie to you but your prompt technique should be enhanced :)

**Comment by SHENJIE15** [comment]
Are you sure? If you don't want us to use the basic line segment tool, you can limit the number of uses or strengthen the screening system. I don't agree with what you The option to use a simple path is hidden because its deployment may violate established conventions. By default, this particular feature remains hidden. In addition, the works submitted to the gallery of subway route plotter will be strictly examined, and the viewpoint of using monochromatic simple path composition will be resolutely rejected.In my opinion, since you are trying to avoid what you say at home, you should keep an open mind, not just limit one tool.



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/16/2024 11:14 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [railmapgen/rmp] There may be a problem with the answer (Issue #688) |

Hi. It doesn't matter whether the answers are correct or wrong to the fact since what you select should correspond to the article and the question. Chat GPT might not lie to you but your prompt technique should be enhanced :)

**Comment by thekingofcity** [comment]
Hi, this is an open-source project released under the GPL v3 license. If you're not satisfied with the current implementation, you're free to build and release your Rail Map Painter.
