### ISSUE TITLE
希望可以像一开始那样能画基本线段

### ISSUE THREAD

**Issue by Hutk2023** [railmapgen/rmp#693]
我真的还是觉得那时候的感觉最好，最自由，希望可以考虑。谢谢开发者们！

**Comment by thekingofcity** [comment]
嗨，地铁线路图绘制器是针对制作由k=-1,0,1,∞这四种斜率直线组成的线路图，所以被禁用了。如果您有其他的需求，那地铁线路图绘制器可能不是适合您的工具，您可以尝试其他工具使用 :)

**Comment by Hutk2023** [comment]
好的，谢谢开发者的回复。
