### ISSUE TITLE
希望可以开发“暂缓开通”样式的荧光黄底色的text文本

### ISSUE THREAD

**Issue by Hutk2023** [railmapgen/rmp#698]
也许只需要加一个文本“底色”的功能就实现了呢？谢谢！希望开发者可以考虑！

**Comment by xiao-slm** [comment]
你好！感谢您提供的参考资料，这将有效地帮助核心贡献者创造这种都市风格。但是，由于时间和精力的限制，在核心贡献者接管并将问题的接收者更改为他/她之前，更新不会立即开始。感谢您的理解。无论如何，如果您想尽快见到它们，也欢迎您通过捐赠来优先考虑它们:)
你可以从这里找到它[这里（推荐）](https://afdian.net/a/rail-map-toolkit)或[这里](https://opencollective.com/rail-map-toolkit)捐赠

**Comment by CatAlan1028** [comment]
个人认为可以用文字线路标识来临时代替一下

**Comment by CatAlan1028** [comment]
不过文本添加底色的确十分重要。目前建议基于原有任意文字基础上添加：
1、背景色
2、背景圆角方形的圆滑度（0为直角，随着该值增大，角由尖锐变为圆滑）
或者，直接添加一种圆角方形贴图（包含：坐标、长宽、深度、圆滑度），个人认为可能更好，因为不同地区暂缓开通标识不同且有些时候会存在不同的字体大小，甚至包含线路标识，单纯用文字背景颜色去拟合可能无法达到要求

**Comment by thekingofcity** [comment]
嗨，此功能可以在大师节点中完美实现，欢迎使用 :)
