### ISSUE TITLE
Can the exported images be clearer?

### ISSUE THREAD

**Issue by NiuBoss123** [railmapgen/rmp#70]
Can the exported route map be clearer? Or can you provide svg images? After all, the exported line diagram is blurred after zooming in, and I wanted to see the line diagram by zooming in, but it's not a vector image.

**Comment by Dingdong2334** [comment]
You can try to change the "Scale" to "500%", and download the map, that maybe more clearer than before.

**Comment by NiuBoss123** [comment]
> 

Thank you very much, but I still suggest providing svg images for users like me who want to put the wiring diagram inside the site

**Comment by NiuBoss123** [comment]
> You can try to change the "Scale" to "500%", and download the map, that maybe more clearer than before.

Thank you very much, but I still suggest providing svg images for users like me who want to put the wiring diagram inside the site

**Comment by thekingofcity** [comment]
Hi, thanks for the suggestion. RMP is now able to export svg files. 🎉

![RMP_1664954301558](https://user-images.githubusercontent.com/3353040/194011707-2af9977a-c860-4ce0-bb4d-db366cc3f054.svg)
