### ISSUE TITLE
Xi'an Metro Station

### ISSUE THREAD

**Issue by 3156940656** [railmapgen/rmp#700]
求博主加一下西安地铁基本车站、换乘车站
西安地铁的线路图如下（以真实走向绘制）
![834adaa060f24ddba5d552bca422b480](https://github.com/railmapgen/rmp/assets/159789737/211e31d2-cd5e-49ce-8754-f55e9b99cbde)
不知道西安地铁线路图有没有直线线路绘制的

**Comment by thekingofcity** [comment]
嗨，我们暂时不考虑任何不以90°或135°弯折的线路图，感谢您的理解 :)
