### ISSUE TITLE
Add JR East Line styles, stations and facilities (All styles)

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmp#706]
Style 1 Link: https://www.jreast.co.jp/map/pdf/map_tokyo.pdf or https://www.jreast.co.jp/chiba/pdf/soubu.pdf (Finished)
Style 2 Link: https://www.jreast.co.jp/map/pdf/minamitohoku.pdf
Style 3 Link: https://www.jreast.co.jp/map/

**Comment by CatAlan1028** [comment]
似乎和之前的议题有重复了 
#695 
@thekingofcity

**Comment by thekingofcity** [comment]
Hi, you may find planning features in #695.

**Comment by DQB061204** [comment]
您好 该议题并不重复 只是添加了额外的两种风格 望该议题open 并且close其他重合的议题

**Comment by thekingofcity** [comment]
额外两种风格并不会在可见的未来被添加，我们目前仅能能确保至少一种同公司的风格
