### ISSUE TITLE
可否添加新建画布选项

### ISSUE THREAD

**Issue by Dingdong2334** [railmapgen/rmp#71]
您好！
请问可否添加"新建画布选项"在rmp？像在rmg一样，新建一个没有任何线路的新画布。
或者是否有其他的方法可以达到此目的？请问是什么方法？感激不尽！

**Comment by thekingofcity** [comment]
You may click the "New project". It is on the top right corner.

![image](https://user-images.githubusercontent.com/3353040/193847993-ae371c87-1d6a-4a7f-b573-19912a2431f1.jpeg)

**Comment by Dingdong2334** [comment]
你好！
感谢回复，谢谢。
