### ISSUE TITLE
Generic icons for railway/bus connection

### ISSUE THREAD

**Issue by merakiann** [railmapgen/rmp#711]
Currently, the "Facilities" icon only has railway icons specific to China. I hope generic icons representing railway connection can be added, so people from all over the world will be able to understand. The current bus interchange icon has an unchangeable green background color, it would be helpful if colors for these icons can be customized.

**Comment by thekingofcity** [comment]
Hi, thanks for your suggestion. We do want support facilities icons all over the world. This, by current expectation, will be done by manual svg upload and merge. Changing the background color or other attributes will be hard for users without any svg/css background and will be impossible to cover all the attributes. But stay tuned, we do have plan for master nodes where you can directly insert svg content in #580 :)
