### ISSUE TITLE
Donation: New stations/nodes request for London

### ISSUE THREAD

**Issue by CarolStott** [railmapgen/rmp#732]
Hi,

Thank you for creating such a useful program for making rail maps. I'd like to ask for London Underground-style station markers. The diagram standards for the regular and interchange stations are [here](https://content.tfl.gov.uk/tfl-line-diagram-standard.pdf), and the rest of the design standards are [here](https://tfl.gov.uk/info-for/suppliers-and-contractors/design-standards); the font you'll need is Johnston ITC Medium, a good version of which can be freely downloaded from [this site](https://fontsgeek.com/fonts/johnston-itc-regular) the last time I checked. If you can't access these sites, I have the PDF and font file attached.

My donation amount is $9.99, and I have attached the receipt.

**Attachments:**
[johnston-itc-regular_d57iO.zip](https://github.com/railmapgen/rmp/files/15000659/johnston-itc-regular_d57iO.zip)
[johnston-itc-std-medium_HU2xP.zip](https://github.com/railmapgen/rmp/files/15000660/johnston-itc-std-medium_HU2xP.zip)
[TfL Line Diagram Standard.pdf](https://github.com/railmapgen/rmp/files/15000666/TfL.Line.Diagram.Standard.pdf)
[TfL London Underground Station Idioms.pdf](https://github.com/railmapgen/rmp/files/15000667/TfL.London.Underground.Station.Idioms.pdf)
[TfL Pictogram Standards.pdf](https://github.com/railmapgen/rmp/files/15000668/TfL.Pictogram.Standards.pdf)
[transaction_rail-map-toolkit_2024-04-16_b82f9582-cff9-4f9f-a867-e569879c96ca.pdf](https://github.com/railmapgen/rmp/files/15000672/transaction_rail-map-toolkit_2024-04-16_b82f9582-cff9-4f9f-a867-e569879c96ca.pdf)

**Edit**: I have included the Idioms and Pictograms if you're curious; the Line Diagram Standards PDF is the one you'll need for the station design standards

Thanks again for this program,
Carol.

**Comment by thekingofcity** [comment]
Hi, 😊 It's seriously awesome to see your enthusiasm for our project, and a huge thanks for your donation and support!

London has been on our radar for a while now, especially with its iconic underground system and that cool map design by Harry Beck. We're gearing up to include it in our next big release, version 5.0.

Right now, we're putting the finishing touches on tube stations and related line styles, tweaking things here and there. We've got basic and interchange stations covered, along with internal interchange and the 10-minute walk line style. You can track the progress in issues #658 and #713.

But, just to be clear, we still have a bunch of stuff left to tackle—like overground line styles, national rail line styles, facility icons, and fare zones (including stations in both zones). So, while we'll have half of London's elements shown on [tube & overground map](https://content.tfl.gov.uk/standard-tube-map.pdf) and [tube & rail map](https://tfl.gov.uk/cdn/static/cms/images/london-rail-and-tube-services-map.gif) in the coming few months (without your donation of course!), the other half is still in the pipeline.

Your support will in turn help us getting the rest of London mapped out this year, and the donation is fare enough for them. But in case you're good with only tube stations and line styles, you're welcome to use this donation to support [other styles](https://github.com/railmapgen/rmp/issues?q=is%3Aopen+is%3Aissue+label%3Astyle) (maybe [Paris](#702) or [Madrid](#701) or create your issue with links to the official map). Note they may take more of the amount you donate but it's okay to just pick several stations/line styles from the official map. Feel free to close this and comment on other issues if you are interested.

Once again, massive thanks for having our backs! Let's keep pushing forward and make RMP the ultimate rail map painter for everyone's taste! 🚆✨
Cheers,
thekingofcity

**Comment by thekingofcity** [comment]
BTW, we use Railway font from https://www.fontspace.com/railway-font-f20426. This font uses a SIL Open Font License. I couldn't find a license with Johnston ITC Medium and a free download does not mean free use :(

**Comment by thekingofcity** [comment]
There is a technical preview on our test environment: https://uat-railmapgen.github.io/?app=rmp

Known issues: Internal interchange line style won't work on non-accessible stations.

**Comment by CarolStott** [comment]
Hi,

Thank you so much for this! The only nitpick that I have is there seems to be a small gap between lines when using the tick-mark station style !([Screenshot 2024-04-17 132455](https://github.com/railmapgen/rmp/assets/89662989/94b60167-6f76-49e3-ba0f-5464f2297bc7). )Also, I think the text for the stations is a bit small (which the line diagram standard should help with) - but as I said, they're just me nitpicking.

May I ask when this might come out on the RMG proper?

Kind regards,
Carol

**Comment by thekingofcity** [comment]
Hi,

Looks like we're delving into the intricate world of SVGs! 🎨 The gap you've spotted is a common occurrence in SVG rendering, mainly due to [anti-aliasing](https://stackoverflow.com/questions/73731114/removing-gap-between-two-svg-paths-without-removing-anti-aliasing). Unfortunately, there's no silver bullet fix for this issue, but there are a few workarounds to explore. The link suggests three options: disabling anti-aliasing (which isn't ideal, as seen in the preview), using the SVG `feMorphology` filter (which can impact performance and aesthetics), or incorporating a background concatenated path (a bit complex and computationally heavy).

Here's the suggested way in RMP: consider using the terminal line style solely on the terminal segment. This approach should alleviate the gap problem, especially in stations with inbound and outbound lines. Alternatively, we could explore adding a round [`stroke-linecap`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap) switch in the single-color style—though, it's worth debating whether this warrants a new terminal line style or just a tweak to the existing one.

Regarding the font issue, I've noticed it too. I'll adjust the font size slightly to ensure the x-height matches the line width for consistency.

As for RMG, it operates on a different drawing algorithm and currently doesn't support multiple branches. More discussions on this topic can be found in railmapgen/rmg#248. The only tube-related addition feasible in RMG might be the station name circle.

Best,
thekingofcity

**Comment by CarolStott** [comment]
Hi,

Sorry, I mixed the two programs up - I meant to ask when we can expect to see the London Tube style in the Rail Map _**Painter**_ outside of the testing environment. I'm finding these features incredibly useful!

Kind regards,
Carol

**Comment by thekingofcity** [comment]
Hi,

We're aiming to release the London Tube style in version 5.0, which is set to drop this summer.

Fonts issue should be fixed soon in the test environment. The internal interchange line style will require some technical enhancements, so it might take a bit longer.

Does this work for you? Let me know!

Best,
thekingofcity

**Comment by CarolStott** [comment]
Hi,

Thank you so much - this works perfectly.

Regards,
Carol

**Comment by thekingofcity** [comment]
Hi,

The issue of font size was fixed and released to the test environment :)

Bests,
thekingofcity

**Comment by CarolStott** [comment]
Hi,

Thank you again for making such a good program.
 
May I ask if there is a more specific date for when version 5 (the version with the London Underground features) will be released? It seems to have gone from the testing environment.

Regards,
Carol

**Comment by thekingofcity** [comment]
Hi,

V5 contains a lot of features and we're actively working on each of them. Currently the test environment (UAT) is deployed with the master node feature where you can upload your own svg and import it into the canvas. More details could be found in #580.

In the meantime, the schedule for V5 is still on track and we're looking forward to release it in late July or early August. Once the beta version is deployed on UAT, I'll let you know with further comments. Thanks for your patience :)

**Comment by thekingofcity** [comment]
Hi,

Thanks for your patience. V5 with the right internal interchange line style is available on [UAT](https://uat-railmapgen.github.io/) and [ORG](https://railmapgen.org/). Note they are both on tests and changes might happen. Feel free to give it a try and report any problems :)

![image](https://github.com/user-attachments/assets/acc7b8a6-6392-491d-a680-59dad7ac2ab0)

Best,
thekingofcity

**Comment by CarolStott** [comment]
Hi,

This looks like a great update, although the Johnston font has gone. When will this be released in the main environment?

Regards,
Carol

**Comment by thekingofcity** [comment]
Hi,

Thanks for pointing it out. The fonts as well as other fixes are updated. Feel free to report any problems :)

Bests,
thekingofcity

**Comment by thekingofcity** [comment]
Hi,

https://railmapgen.org/ is now generally available for production. This includes not only the London Underground but also a bunch of new features such as parallel lines and master nodes :)

This issue will still be left open as overground line styles, national rail line styles, facility icons, and fare zones (including stations in both zones) are not implemented yet. They are scheduled later this year :)

Bests,
thekingofcity

**Comment by thekingofcity** [comment]
Hi,

Thank you for your patience. All remaining items are now available in our [test environment](https://uat-railmapgen.github.io/?app=rmp). Feel free to give it a try and report any issues!

You can find the update details in #902 :)

Happy holidays,
thekingofcity

**Comment by thekingofcity** [comment]
Hi,

We released them in the production environment. Feel free to open a new issue if some elements are not matching with the original design :)

Best,
thekingofcity
