### ISSUE TITLE
Line spacing of London tube station

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmp#733]
The Line spacing of London tube station should be wider.
In the Tfl official map:
![9551CN$_ES%L N 6_DV$ Z7](https://github.com/railmapgen/rmp/assets/92020676/abc76232-27ea-4f0c-b318-f9b9c9e1722e)
In UAT:
![8GXHP)J5{QT5NND{X%5I(LN](https://github.com/railmapgen/rmp/assets/92020676/5d8e65e2-a92e-45c5-9303-5fbc8512c624)

**Comment by thekingofcity** [comment]
Should be fixed in UAT. Close this if it is good now :)
