### ISSUE TITLE
大哥们，救救孩子吧，根本导出不了哇

### ISSUE THREAD

**Issue by Kimq0521** [railmapgen/rmp#734]
一导出就给我蹦出来这个，根本看不懂，求求各位大哥，怎么解决这种问题
![Uploading 截屏2024-04-20 上午10.48.41.png…]()

**Comment by 28yfang** [comment]
您好，请等待文件上传完成之后再开启议题 :)

**Comment by Kimq0521** [comment]
啊？我纯萌新，啥也不懂啊，就是单纯的导出不了，来问问而已

**Comment by langonginc** [comment]
截图没有成功上传，请您重新上传一次，并等待上传提示信息消失后再发表评论。

**Comment by LittleLing03** [comment]
请您先冷静下下……

**Comment by Kimq0521** [comment]
![Uploading 截屏2024-04-20 上午10.48.41.png…]()

**Comment by Kimq0521** [comment]
<img width="830" alt="截屏2024-04-21 下午12 48 43" src="https://github.com/railmapgen/rmp/assets/167595437/cf209bf4-1a39-46f1-ae70-a13093d049ed">

**Comment by thekingofcity** [comment]
嗨，感谢报告问题。请一并附上此环境信息：镜像的地址或离线版本。

并请您注意Mac/Safari环境需要特殊的设备，我们并没有这样的环境来复现并修复问题 :) 您或许可以安装windows或linux的虚拟机来解决

**Comment by Kimq0521** [comment]
大哥你好，什么环境信息之类我真不明白是什么TT，虚拟机也不会搞。所以大哥，给我个小白也能明白的解决方法吧（一开始还正常，但当天晚上就不能导出了

**Comment by Kimq0521** [comment]
大哥你好，什么环境信息之类我真不明白是什么TT，虚拟机也不会搞。所以大哥，给我个小白也能明白的解决方法吧（一开始还正常，但当天晚上就不能导出了

**Comment by 28yfang** [comment]
您好，请问您用的是什么版本的macOS？（点击mac屏幕左上角的苹果图标>关于本机 就可以看到）我在macOS14.4.1中并没有此问题

**Comment by 28yfang** [comment]
如果实在不行的话，试试重启电脑或者下载其他的浏览器（我也不清楚是什么问题）

**Comment by Kimq0521** [comment]
大哥们，刚更新了。还不行，甚至蹦出来这个
<img width="1280" alt="截屏2024-04-22 下午9 30 05" src="https://github.com/railmapgen/rmp/assets/167595437/18bbfa30-4d5f-497a-9bca-7d16a0eb3a76">

**Comment by Kimq0521** [comment]
> > 大哥们，刚更新了。还不行，甚至蹦出来这个
> > <img alt="截屏2024-04-22 下午9 30 05" width="1280" src="https://private-user-images.githubusercontent.com/167595437/324479130-18bbfa30-4d5f-497a-9bca-7d16a0eb3a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjI5ODcsIm5iZiI6MTcxMzkyMjY4NywicGF0aCI6Ii8xNjc1OTU0MzcvMzI0NDc5MTMwLTE4YmJmYTMwLTRkNWYtNDk3YS05YmNhLTdkMTZhMGViM2E3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwMTM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2M4NWNjOTEwMGY1MmIwMDRmMDZiYWU5NjEwNWQ2OTM4NmRhOTdkNGI3MmNjNzFmYmU3NWMzODk0N2IxZTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rQfHrptPlN5iexgqr839s6ZfIOjvXRsjGEnjna6UH_o">
> 
> 这看起来是正常情况，这是您作品的配置文件，您可以保存这个文件以便以后修改。如果您需要图片，应点击导出图片。

也就蹦出来一次这个，不管是点导出项目还是图片，都是蹦错误出来，导出不了一点
