### ISSUE TITLE
Font offset issue with shmetro text line badge

### ISSUE THREAD

**Issue by 662926** [railmapgen/rmp#737]
导出图片北京文字标识字体向上漂移
![1](https://github.com/railmapgen/railmapgen.github.io/assets/128211210/8daa16c5-cbfb-4d32-84d3-d3a1fd3b776f)

![2](https://github.com/railmapgen/railmapgen.github.io/assets/128211210/32559a6d-fccf-4b62-be6a-71d6b53101b3)

**Comment by thekingofcity** [comment]
嗨，方便再检查一下这个杂项节点是 北京地铁文字线路标识 吗？根据直角矩形判断这个更像是 上海地铁文字线路标识 :)

**Comment by 662926** [comment]
是的，是上海地铁文字线路标识 ，是我看错了。

**Comment by thekingofcity** [comment]
![image](https://github.com/user-attachments/assets/ffe3ec82-ee13-4f0c-a6a4-33b93c401c25)
