### ISSUE TITLE
彩色车站方面的问题

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#742]
问题1：如视频所示，含颜色信息的车站样式在互相转换时无法保留其颜色信息（即使手动输入了也不行）。故在此希望可以加入保留颜色信息的功能（尤其是在需要统一大量替换的时候，这个功能会很重要）

问题2：目前调色板中青岛的颜色已被更新（其中1号线为#f7b000），但青岛地铁车站在被放置时的默认颜色仍为旧的1号线颜色（#eaaa00）（此问题在青岛地铁线路标识上也有）
之前苏州样式也出现过这一问题，但现已被修复
在此希望能修正青岛地铁车站和青岛地铁线路标识的默认颜色，如果可以的话希望能更进一步解决站点和标识默认颜色无法同步更新的问题

视频：
https://github.com/railmapgen/rmp/assets/137034903/2b14aef2-edef-48c7-ac98-80c870d90714

**Comment by langonginc** [comment]
感谢您的建议，我们已经添加到 3.5.39，欢迎体验～
