### ISSUE TITLE
突然就这个样子了 刷新 重新进入也没用

### ISSUE THREAD

**Issue by jklyyy** [railmapgen/rmp#749]
<img width="1228" alt="屏幕截图 2024-05-09 105719" src="https://github.com/railmapgen/rmp/assets/169325130/1481a57f-b8d6-4b0e-a67c-7c6beec62b5b">

**Comment by thekingofcity** [comment]
嗨，方便打开浏览器开发者工具后获取名为rmp__param的本地存储数据再将结果粘贴在此处吗？这将帮助我们找到问题并尝试修复您的存档 :)

获取过程可参考：https://learn.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/storage/localstorage
