### ISSUE TITLE
how do i have 2 lines next to each other like this?

### ISSUE THREAD

**Issue by Enderman2452633YT** [railmapgen/rmp#751]
![image](https://github.com/railmapgen/rmp/assets/103882226/bb9f1fe0-3d84-4fd6-9bc3-4b719950b3a9)

whenever i try to the lines just overlap, am i missing something?

**Comment by Enderman2452633YT** [comment]
so how do i make it look like in the pic

**Comment by 28yfang** [comment]
Hi, to offset the lines you need to change the offset From and offset To of the lines. In this case, the line 3 line needs to have -2.5 offset, and the line 4 line needs to have a 2.5 offset.

**Comment by 28yfang** [comment]
![Screenshot 2024-05-17 at 14 08 14](https://github.com/railmapgen/rmp/assets/123239445/f5786784-e510-487f-9351-cb05bc96ec2f)
![Screenshot 2024-05-17 at 14 08 19](https://github.com/railmapgen/rmp/assets/123239445/b2024ead-e826-480e-abd0-4ed9e0941d79)

**Comment by Enderman2452633YT** [comment]
thanks!

**Comment by Enderman2452633YT** [comment]
but how would i do it for a mtr station?

**Comment by 28yfang** [comment]
Hi, in this case the offset from and to needs to be 0, 5, 10, etc.
