### ISSUE TITLE
广州地铁2024新换乘站 Guangzhou Metro interchange 2024 station

### ISSUE THREAD

**Issue by zyx19851218** [railmapgen/rmp#757]
前十几天不是那个广交展会吗，然后很多就看到了那个新版的线网图
主要更新了广肇和广惠城际，还有车站的样式和线路的大致走向好像也有变（见下图）
并且最近一些车站已经开始挂新版的线路图了
![下载](https://github.com/railmapgen/rmp/assets/130904466/0d5289fb-bd33-4259-9036-75f97327282c)
图不是很清晰，就大概变了这些
1.城际线的样式，好像之前的就已经有了，新版的只是加了广肇广惠城际线
2.换乘站的样式有变，具体的样式大概是几个普通车站加上灰色描边
（注：1.广州地铁换乘站老版样式我觉得可以保留一下
           2.其他改变了样式的节点我都在图里做了标记的）
见下图
![下载 (1)](https://github.com/railmapgen/rmp/assets/130904466/85d24682-99ad-40c0-a760-2eaea7745442)

**Comment by thekingofcity** [comment]
嗨，感谢您的建议，我们已经注意到这些变化，并感谢 @chitowong 的贡献可以帮助我们更快地添加新换乘车站到项目中 :)

附高清原图，来自广州地铁官网：
![](https://cs.gzmtr.com/ckfw/xlu_2020/202405/W020240524846059965254.png)

**Comment by thekingofcity** [comment]
城际线相关变动请见 #682
