### ISSUE TITLE
想新加一个功能

### ISSUE THREAD

**Issue by Xiaoguogai2023** [railmapgen/rmp#767]
想新加一个功能，就是在需要把那个海洋部分填上蓝色的时候，只能一条线一条线的拉那个河流线段，比较麻烦
能不能直接新出一个填色功能，打比方说你把那个边框标出来之后用这个新功能去给里面填色，这样就好用很多

by一名初中牲

**Comment by thekingofcity** [comment]
嗨，感谢建议，自定义实现海洋的功能我们将会在 #580 中实现。在大师节点中，您可以直接导入其他程序如Adobe Illustrator中生成的svg以快速生成自定义图案元素 :)
