### ISSUE TITLE
批量修改颜色时的问题

### ISSUE THREAD

**Issue by OIer-Tan** [railmapgen/rmp#769]
你好，开发者，当我使用“批量修改颜色”功能时，我发现线路的“从这里开始”属性被恢复为默认（即`from`）。

希望能修改一下这个问题，谢谢。

**Comment by langonginc** [comment]
修改时您是否打开了修改线路类型的面板，如下图。

<img width="450" alt="image" src="https://github.com/railmapgen/rmp/assets/59787082/4041ce5e-14b2-4208-9f56-48d7f070a7fa">
