### ISSUE TITLE
阿弥诺斯

### ISSUE THREAD

**Issue by amsr-ing** [railmapgen/rmp#772]
无法将地铁线路图导入到地铁线路图绘制器

**Comment by thekingofcity** [comment]
嗨，非常抱歉发生这样的事情，方便详细描述下步骤并上传导入的作品到这里吗？

**Comment by amsr-ing** [comment]
> 嗨，非常抱歉发生这样的事情，方便详细描述下步骤并上传导入的作品到这里
[RMG_广安1号线_Guang'an Line 1.json](https://github.com/user-attachments/files/16084786/RMG_.1._Guang.an.Line.1.json)
[RMG_1号线_Line1 2.json](https://github.com/user-attachments/files/16084787/RMG_1._Line1.2.json)
[RMG_2号线_Line2.json](https://github.com/user-attachments/files/16084788/RMG_2._Line2.json)
![RMP_1719997956885](https://github.com/railmapgen/rmp/assets/174607290/58cb71f7-9b1b-47aa-9dec-240d3c105534)
[RMG_广安机场线_Guang'an Airport.json](https://github.com/user-attachments/files/16084790/RMG_._Guang.an.Airport.json)
[RMG_机场快线_Airport Express.json](https://github.com/user-attachments/files/16084784/RMG_._Airport.Express.json)

**Comment by thekingofcity** [comment]
嗨，我尝试按照此顺序一个个导入，但并未发现问题。

全部导入后对应的项目存档附在这里：
[RMP_1720167913932.json](https://github.com/user-attachments/files/16107155/RMP_1720167913932.json)

**Comment by thekingofcity** [comment]
欢迎重新打开此议题或评论，如果您有更多问题的话 :)
