### ISSUE TITLE
[Feature Request] Background Support

### ISSUE THREAD

**Issue by HornCopper** [railmapgen/rmp#777]
是否可以支持使用自定义背景图，方便直接在背景图上绘制地铁图？

**Comment by thekingofcity** [comment]
嗨，感谢建议，不过地铁线路图绘制器所针对的线路图与实际地图并非同一比例尺，以地图做背景会导致线路图很难符合贝克的经典设计，所以暂时并没有这方面的打算 :)

**Comment by thekingofcity** [comment]
当然，也欢迎捐赠后定制此功能 :)
