### ISSUE TITLE
目前RMP的一些建议

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmp#78]
之前在RMG的Slack讨论群里提到过一些，这次干脆就放到这边来了
目前就上海风格有以下几点建议：

**1. 虚拟换乘***
@thekingofcity 提到过上海地铁风格的虚拟换乘还没做，我看了一下上海地铁官方的线路图（渣画质警告），上海地铁的虚拟换乘是几个圈（数量对应可换乘线路量）之间用黑边白线（类似于浦江线屏蔽门贴纸上已驶过车站的线条）连起来的：
![SHMETRO_OOS](https://user-images.githubusercontent.com/98044618/195646684-b4671b08-1906-402f-b400-bf52fe2c31bb.jpg)

至于出站转乘（换磁浮线和金山铁路这两种），虽然跟上面的类似，但两个圈之间并没连起来，这个我觉得可以不用考虑制作了（这个其实可以直接拿两个现有的换乘胶囊改一下参数来实现）

**2. 特殊线路颜色**
由于特殊线路（金山铁路和磁浮线）并不是用纯色线条来画线路图的（比如金山铁路用的是地图上铁路线条（黑白轮流的线），而磁浮线则是两种颜色的线条拼起来的），我就不清楚这种特殊线路的线条有没有可能实现🤔
![SHML](https://user-images.githubusercontent.com/98044618/195647875-399c419c-d82f-41ce-9c5b-5a8bf9540645.jpg)
（p.s. 其他铁路系统风格的特殊线路线条还包括港铁轻轨线的细线条（下面两图图1）和北京有轨电车的“两面包夹芝士”风线条（下面两图图2），这两个也可以参考一下）
![MTR](https://user-images.githubusercontent.com/98044618/195649454-67828a9b-f32e-4dfe-b759-dad153a2302c.jpg)
![BJSubway](https://user-images.githubusercontent.com/98044618/195649471-85d4fe7b-bdc3-469f-912a-918ea5b127fb.jpg)

**3. 图例**
其实这个确实期望好久了，毕竟各家地铁系统线路图都会放个图例上去，我觉得咱们这边也加上会不会好一些？🤔
（放张上海地铁官方线路图的图例，这张也能看到虚拟换乘的设计风格。左边的备注区其实不一定要有）
![SHMetro_Legend](https://user-images.githubusercontent.com/98044618/195650176-787d5110-7e04-4031-8497-993445206122.jpg)
（虽说也可以手动制作，但感觉确实会麻烦很多）

**4. 车站设施**
目前RMP是没法给车站添加设施图标（机场、火车站什么的）的（具体风格见特殊线路颜色那里磁浮线下面浦东国际机场站），不知道后面能不能加上.

**5. 数字线路标识的线路编号矩形宽度问题**
目前RMP中数字线路标识是这样的：
![Screen Shot 2022-10-13 at 12 21 58 PM](https://user-images.githubusercontent.com/98044618/195653861-0a119e13-bcf6-4f4d-983b-8c3a26d3cbeb.png)
说实话，这种线路编号矩形宽度不统一一个是看起来不好看，另一个是也不太符合上海地铁官方线路图的样式（单数字线路的矩形宽度是一样的）
以目前上海官方的矩形宽高比来讲应该像下面这种会更合适一些（下图是我自己用开发者模式在RMP中改的）：
![Screen Shot 2022-10-13 at 12 30 47 PM](https://user-images.githubusercontent.com/98044618/195654188-776f124f-4979-4477-8689-ed8d021a3e68.png)
就不知道以后的更新能不能统一一下这个矩形宽度的问题（参照了一下官方的，考虑到RMP里面的矩形高度为16的话，那一位数线路的矩形宽度应统一为14.5，两位数线路的矩形宽度应统一为17.5）

**Comment by XHG78999** [comment]
（诈尸
按照官方的设计标准，矩形的宽高比事统一的10:9
不过图标什么的可以考虑
另外大家急需羊角风的连通车站（来源某Minecraft服务器群）
双线条应该还好，但是高总风格基本无望

**Comment by 52PD** [comment]
> 按照官方的设计标准，矩形的宽高比事统一的10:9

额。。。官方线路图其实并不完全遵照这个标准😂（因为线路图上字号要大一些，如果全都统一用10:9的矩形那二位数的线路号就溢出去了），所以只有一位数线路号的矩形才是10:9，二位数的话要稍微宽一些

**Comment by XHG78999** [comment]
> > 按照官方的设计标准，矩形的宽高比事统一的10:9
> 
> 额。。。官方线路图其实并不完全遵照这个标准😂（因为线路图上字号要大一些，如果全都统一用10:9的矩形那二位数的线路号就溢出去了），所以只有一位数线路号的矩形才是10:9，二位数的话要稍微宽一些

官方透露的好像就是10:9，但是由于外包厂商等诸多原因至今没有完成统一标准。目测至少12/13用的是10:9压字宽

**Comment by XHG78999** [comment]
而且很多导向标识会缩小数字大小，比如最近部分换装的LED出入口牌坊

**Comment by 52PD** [comment]
> 官方透露的好像就是10:9，但是由于外包厂商等诸多原因至今没有完成统一标准。目测至少12/13用的是10:9压字宽

是10:9，但只针对于灯箱和屏蔽门盖板贴纸
而官方线路图上10-18号线的矩形是明显比1-9号线要宽的
![sn](https://user-images.githubusercontent.com/98044618/195970030-67c81012-59d6-4171-97fc-cbe8d330a6c1.jpg)
上面那张图是从官方线路图上截下来的，你量一下的话会发现这上面10号线的矩形是要比7号线宽一点的

**Comment by Harrislin22915** [comment]
线路编号的风格只有一种吗？能不能加上别的风格？

**Comment by Harrislin22915** [comment]
比如说这个风格
![IMG_20220924_125549678](https://user-images.githubusercontent.com/111274295/195975823-ab05a13a-b395-4bb5-85b4-3ccc29d49ae8.jpg)

**Comment by thekingofcity** [comment]
> 另外大家急需羊角风的连通车站（来源某Minecraft服务器群）

什么是连通车站？虚拟换乘车站？

> 双线条应该还好，但是高总风格基本无望

高总风格指的是？有关线条样式的讨论我会但开一个issue。

**Comment by thekingofcity** [comment]
> 线路编号的风格只有一种吗？能不能加上别的风格？

嗨感谢关注，其他城市车站和线路样式会陆续加入项目中，敬请期待。有关某一特定城市的样式欢迎新开issue讨论。

**Comment by 52PD** [comment]
> 线路编号的风格只有一种吗？能不能加上别的风格？

楼歪了哎，亲🌝

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与建议。To focus on points you mentioned, I created sub issues for each of them. I’ll also close this issue to limit discussion.

- [ ] 1. 虚拟换乘 #80 
- [ ] 2. 特殊线路颜色 #84 
- [ ] 3. 图例 #85 
- [ ] 4. 车站设施 #82 
- [ ] 5. 数字线路标识的线路编号矩形宽度问题 #83
