### ISSUE TITLE
上海地铁添加共线段出错

### ISSUE THREAD

**Issue by AugerBeryl** [railmapgen/rmp#781]
按网站教程添加T1和T2两站间共线段：先添加了外部路线，再返回主线添加共线段，结果显示无法添加该共线段。
<img width="964" alt="image" src="https://github.com/user-attachments/assets/6573449a-f188-41c4-ad5b-1e302fdcd44d">
<img width="964" alt="image" src="https://github.com/user-attachments/assets/15f42684-0e8d-4a42-8f68-a5130f4d31aa">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/f774548f-0832-488e-816b-a3f8db60d9dc">
这是bug吗？还是说要用新方法添加？如果是新方法该怎么添加？

**Comment by thekingofcity** [comment]
> <img width="964" alt="image" src="https://github.com/user-attachments/assets/15f42684-0e8d-4a42-8f68-a5130f4d31aa">

嗨，为外部线路的支线，其左端或右端至少有一端为LEFT END或RIGHT END，不支持支线两端都为在主线上车站，感谢您的理解。

更多信息您可参考模板中上海地铁的34号线(共线) :)
