### ISSUE TITLE
北京地铁换乘站描述需更新

### ISSUE THREAD

**Issue by winicu** [railmapgen/rmp#782]
目前的“出站换乘”在北京地铁线路图中被应用为“站内换乘暂缓开通”（木樨地站）

**Comment by langonginc** [comment]
我们似乎并没有将 “出站换乘” 或 “站内换乘暂缓开通” 相关字样体现到线路图中，它仅仅是作为功能按钮的标题（如图），我认为并没有必要去更新。

<img width="296" alt="image" src="https://github.com/user-attachments/assets/fa3b5f35-5487-421d-b530-c92cc3b18ed2">

如您仍认为其具有必要性，不妨在下面论证。感谢您的支持～
