### ISSUE TITLE
Changsha Station

### ISSUE THREAD

**Issue by 3156940656** [railmapgen/rmp#784]
希望导入长沙地铁的基本站点和换乘站点
![长沙地铁20240628线路图](https://github.com/user-attachments/assets/a906f67e-3320-4513-8661-171c5605836a)
![Changsha Station](https://github.com/user-attachments/assets/d32c7f89-1c4a-42e8-ba70-0157eced86ec)
![Changsha Transfer](https://github.com/user-attachments/assets/f2e8f7d4-32e6-48bc-a45e-a42d22b6937b)

**Comment by Minwtraft** [comment]
已有议题#771 存在，没有必要再发一遍。

**Comment by Minwtraft** [comment]
已有议题#771 存在，没有必要再发一遍。
