### ISSUE TITLE
当地图太大时无法以高分辨率导出

### ISSUE THREAD

**Issue by Caicy2024** [railmapgen/rmp#789]
当线路图变大，可以导出的分辨率越来越小，请问是否有可能以app或其他形式解决呢？SVG图像并不方便，谢谢！

**Comment by thekingofcity** [comment]
嗨，您可以参考[此回复](https://github.com/railmapgen/rmp/issues/301#issuecomment-1611085648)检查现有的解决方法，也欢迎期待之后的服务器导出方案 :)
