### ISSUE TITLE
目前使用中广州地铁风的问题与建议

### ISSUE THREAD

**Issue by Dingdong2334** [railmapgen/rmp#79]
正在制作广州地铁风格的线路地图
发现了如下的问题
*胶囊为站（椭圆）

### **1. 线路名、站序号越出胶囊界**
![屏幕截图 2022-10-15 214952](https://user-images.githubusercontent.com/79365860/195990426-4089b982-686a-4e7b-a77d-a45f19e89a51.png)
图1

如图1所示，若站序号数字超过三个，则会越界；线路编号超过2个字母，则会越界

### **2.换乘标识的一些小细节**
![itgs](https://user-images.githubusercontent.com/79365860/195990686-730c72b4-2324-45e3-8e96-046f186b5890.png)
图2-1
![屏幕截图 2022-10-15 213544](https://user-images.githubusercontent.com/79365860/195990694-52e85bb2-dfe0-4265-83a4-63fd9b01c22e.png)
图2-2

如图2-1所示，比照官方的线路换乘（图2-3），箭头的两端是贴近胶囊的
如图2-2所示，比照官方的线路换乘，三线换乘中，可以在箭头外面加一层细细的白色边（箭头靠近线路线的一边不用白边），还有胶囊也是

![屏幕截图 2022-10-15 213605](https://user-images.githubusercontent.com/79365860/195990667-de476533-fcf4-40f2-9165-d3af34d3e788.png)
图2-3

### **3.广州地铁风格的终点线路标识**
![屏幕截图 2022-10-15 213621](https://user-images.githubusercontent.com/79365860/195990777-f864b441-31cb-47ed-883a-7caaead8857d.png)
图3

虽然说有正方形的，但如图3，官方的是四角圆形的

### **4.支线怎么在图中标识？**
![屏幕截图 2022-10-15 214744](https://user-images.githubusercontent.com/79365860/195990861-4e012bb2-e732-4253-9946-731e76876efe.png)
图4

如图4，支线如何在线路图中标识？我用了一个类似与×的圆形组件，虽然我不知道他的真实用途是什么，但支线显示我目前只能想到这一个办法，希望添加

### **5.车站第二名称**
![屏幕截图 2022-10-15 214454](https://user-images.githubusercontent.com/79365860/195991062-507eff12-e64f-4022-8324-de34c3a962c2.png)
图5

如图5，未开通的车站如何标识？还有机场的车站

### **6.出站换乘问题**

![屏幕截图 2022-10-15 212856](https://user-images.githubusercontent.com/79365860/195991045-f255e42e-8da5-488e-b63b-3005e7289d19.png)
图6

APM与3号线的换乘，虽然车站内设置有出站换乘选项，但是并没有什么用，实际的还有虚线指向，还有两个换乘站来突出指示

### **7.如何换行？**
![屏幕截图 2022-10-15 223342](https://user-images.githubusercontent.com/79365860/195992083-27ef3234-0ad4-4d0e-af2d-b6842bed415b.png)
图7

如图7所示，请问如何换行，反斜杠或斜杠都不起作用，请问有没有方法换行？

### **可以在主界面中添加一个默认线路色来源选项**
![屏幕截图 2022-10-15 214024](https://user-images.githubusercontent.com/79365860/195991185-7f1ec51b-d81a-493b-861b-93eb668b3bc9.png)
图7

如图7，新的换乘站一直默认是上海地铁的线路色，可以在主界面设置一个默认线路色来源的这个选项，可能会有更好的名称

### **添加保持连接选项**
如果要一直不断连线，则每次连完一个站以后又要重新点连线选项去连线。可以添加一个“是否保持连线状态”的选项，开启后，点击连线选项后每次都默认连线，不会拖动站，直到再次点击连线选项取消连线。可能会有更好的名称

**感谢您看完，以上建议望采纳，感谢！**

**Comment by Dingdong2334** [comment]
> ### **2.换乘标识的一些小细节**
**### 指正错误**

>如图2-2所示，比照官方的线路换乘，三线换乘中，可以在箭头外面加一层细细的白色边，还有胶囊也是
错误：胶囊不用白边，箭头靠近线路线的一边不用白边

**Comment by Dingdong2334** [comment]
### **补充**

### **7.如何换行？**
![屏幕截图 2022-10-15 223342](https://user-images.githubusercontent.com/79365860/195992083-27ef3234-0ad4-4d0e-af2d-b6842bed415b.png)
图7

如图7所示，请问如何换行，反斜杠或斜杠都不起作用，请问有没有方法换行？

**Comment by thekingofcity** [comment]
您好，感谢对项目的支持与反馈。您可以直接在1楼右上角设置处编辑原帖而无需回复新的修正内容贴。

关于3456这几个点，欢迎附上实际图片或预期图片来说明想要实现的样式，谢谢。

**Comment by Dingdong2334** [comment]
感谢回复

> 关于3456这几个点，欢迎附上实际图片或预期图片来说明想要实现的样式，谢谢。

### **3.广州地铁风格的终点线路标识**
如图3所示，预期效果即为此

### **4.支线怎么在图中标识？**
可能是我的表达有失误，其实我更想表达的是有两条线贴近（共线）的情况，如何在线路图上实现？
![屏幕截图 2022-10-16 163329](https://user-images.githubusercontent.com/79365860/196026327-75f60a9f-247e-4f36-a177-a2cfd2a069dd.png)

### **5.车站第二名称**
预期效果如下：
![屏幕截图 2022-10-16 163356](https://user-images.githubusercontent.com/79365860/196026377-e8ddc396-d0a6-4288-9450-0c60412ffe10.png)

![屏幕截图 2022-10-16 163807](https://user-images.githubusercontent.com/79365860/196026408-c512df99-b254-4779-988c-db2682a01121.png)

可以像rmg一样加入“车站第二名称选项”，并且加入标红车站名选项

### **6.出站换乘问题**
预期效果：
![屏幕截图 2022-10-16 163430](https://user-images.githubusercontent.com/79365860/196026440-3c238449-77ad-4d1a-913a-cd3b7e8a7a2c.png)

您可以如此实现，在面板中添加一个“出站换乘连接”的项，只适用于广州地铁风的换乘站，点击两个换乘站或两个换乘线即可连接两个组件，用三个点来连接（只有三个点），可在面板中设置三点间距

### **7.如何换行？**

请问如何换行？😂

**Comment by thekingofcity** [comment]
嗨，非常感谢追加的内容，由于本issue内容较多，现将所有点列出，请点开对应的issue查看各个的进度。

1. [ ] 线路名、站序号越出胶囊界 #101 
2. [ ] 换乘标识的一些小细节 #92
3. [ ] 广州地铁风格的终点线路标识
4. [x] 支线怎么在图中标识？ -> 可以参考上海模板的34号线共线部分，简单来说设置线段的起始点结束点偏移即可
5. [ ] 车站第二名称
6. [x] 出站换乘问题 #81 
7. [ ] 如何换行？
8. [ ] 可以在主界面中添加一个默认线路色来源选项 -> 默认线路色已存在，在左侧工具栏最下，目前还没有实现的是带有颜色的车站自动载入当前设置的颜色
9. [ ] 添加保持连接选项

尚未有issue后缀的点会在之后陆续开issue实现，欢迎经常检查此回复。

**Comment by Dingdong2334** [comment]
您好!谢谢您,非常感谢您!
