### ISSUE TITLE
Better station name offset in JR East basic station vertical

### ISSUE THREAD

**Issue by M-ult** [railmapgen/rmp#795]
Dear Developers,

Thank you very much for your tireless work in building this platform for creating roadmaps. As a roadmap enthusiast, I still remember the joy I felt when I first discovered and used this platform. Over time, I've encountered a few issues that have arisen along with version changes, probably starting with version 3.5.38(If I remember correctly the version was updated during the May Day Labor Day Holiday).

1. JR东日本基本车站下，“名称偏移”选择底部，打开“垂直名称”--站名文字与路线贴的过近以至于会覆盖到路线上；在这种情况下再打开“重要车站”，站名明显不居中于黑框而是向上偏移（详见下图所示）
![Q1](https://github.com/user-attachments/assets/44d6dc05-35fa-4f57-b017-62398f61e205)

2. JR东日本基本车站下，打开“重要车站”，“名称偏移”选择左或右--黑框内的文字并没有居中显示而是向下微偏移（详见下图所示）
![Q2](https://github.com/user-attachments/assets/9f1abb01-8c1c-43e8-bd2a-932fd8d09b8f)

3. JR东日本重要车站以及其“最重要车站”的黑框大小。窃以为3.5.38版本之前的两者黑框大小显示是合理的，也正基于此开始着手构建JR东日本样式的路线图。但从3.5.38开始：原本的“JR东日本重要车站”黑框变为原本其“最重要车站”的黑框大小；而原本的其“最重要车站”的黑框大小也比原先大了一倍。（也就是两者的黑框都大了一倍）。从之前构建的路线图角度以及参考现实中官方pdf版本来看，鄙人认为是不合理的，望能将两者调整回原先的黑框大小。

4. 路线在虚拟节点的连接下，导出图片（无论PNG还是SVG）后会产生细黑线，该问题从JR东日本样式上线开始存在至今。虽不是什么大问题，但窃以为难免影响美观（详见下图所示）
![Q4](https://github.com/user-attachments/assets/e029a217-60cf-4340-b16e-904ce093a887)

These are the bug issues I'm having. I look forward to your valuable comments and hope RMP will become more and more powerful.

**Comment by thekingofcity** [comment]
Hi, thanks for sharing the problems and details.

We're currently under the v5 development but I'm pretty sure that this will be the first bug fix after the v5 release.

**Comment by thekingofcity** [comment]
Hi, thanks for your patience. I go through your questions and either fix or explain them below. For testing them before final release, head to https://uat-railmapgen.github.io/?app=rmp

1. fixed.
  ![image](https://github.com/user-attachments/assets/43297adb-9357-47d6-b798-dd45894fae29)

2. I'm wondering if you are not loading the correct "M PLUS 2" font correctly.
  ![image](https://github.com/user-attachments/assets/4352b941-a3ba-4c25-9f59-9b9512a2cf32)

3. The font size of JR East important station is enlarged from 10 to 15 in 3.5.37. From the [official map](https://www.jreast.co.jp/map/pdf/map_tokyo.pdf), I would argue that the font size of 東京 and 上野 is different from 神田 and 御茶ノ水. The only question here is how large it will be, 12, 13, 14, or 15?
  ![image](https://github.com/user-attachments/assets/a74d7364-0e11-4d97-b84b-194e52620030)

4. This is a known issue and the technical reason could be explained [here](https://github.com/railmapgen/rmp/issues/732#issuecomment-2062928165). [Line stop style](#695) could eliminate this problem by having all the lines `strokeLinecap=round`.

Bests,
thekingofcity

**Comment by thekingofcity** [comment]
Yes, you're right. I missed those and thanks for pointing them out.

Font size is changed back to 10 and try it at https://uat-railmapgen.github.io/?app=rmp

**Comment by thekingofcity** [comment]
Hi @M-ult, if everything goes well, can we merge those fixes? Or is there anything unresolved?

**Comment by thekingofcity** [comment]
Hi, this fix is available on version 5.0.34 :)
