### ISSUE TITLE
地铁线路图绘制器（RMP）无法导出图片

### ISSUE THREAD

**Issue by RedLeaf007** [railmapgen/rmp#808]
在 Chrome 128.0.6613.85 以及  Windows 版 Railmapgen 应用里，即便已经勾选“同意条款”和“会附上链接”，也无法导出图片，无论是 png 还是 svg 
![屏幕截图(3194)](https://github.com/user-attachments/assets/54da5866-d608-43ba-8be4-e4e8bbdd3f15)
![屏幕截图(3193)](https://github.com/user-attachments/assets/d2d9e1a1-faf0-4742-8a29-d7d55892fe04)
![屏幕截图(3192)](https://github.com/user-attachments/assets/208289c3-6b77-4ee9-bbf6-9ae04a92c08f)
![屏幕截图(3191)](https://github.com/user-attachments/assets/ddfb90f1-90b2-4fd2-8be7-f72ec47fc090)

**Comment by thekingofcity** [comment]
嗨，刷新可以解决吗？方便分享一下存档到这里吗？请等待上传完成后再发送 :)

**Comment by RedLeaf007** [comment]
我尝试过刷新，甚至重启浏览器、电脑，但都没有什么用。
目前在忙，晚些时间再发存档。
________________________________

**Comment by RedLeaf007** [comment]
[RMP_1724917293341.json](https://github.com/user-attachments/files/16795511/RMP_1724917293341.json)
这个是存档

**Comment by thekingofcity** [comment]
![RMP_1724944850549](https://github.com/user-attachments/assets/8598c3e4-039f-41c0-9fba-e6850f51aaa0)

嗨，我尝试了一下，导出没有遇到任何问题，或者再试试隐身模式？

**Comment by RedLeaf007** [comment]
> ![RMP_1724944850549](https://github.com/user-attachments/assets/8598c3e4-039f-41c0-9fba-e6850f51aaa0)
> 
> 嗨，我尝试了一下，导出没有遇到任何问题，或者再试试隐身模式？
> 

也尝试了隐身模式，但还是不行。

**Comment by thekingofcity** [comment]
从画廊中导入一些存档可以导出成图片吗？还是说都不行？
