### ISSUE TITLE
Guangzhou Metro Facilities 2024

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#809]
广州地铁更新线网图风格后，其设施标识也得到更新。
因此本人根据官方线网图制作了新的设施标识。

由于最新版线网图的线路颜色有偏差，故在此参考了2024年5月的线网图。链接如下：
https://cs.gzmtr.com/ckfw/xlu_2020/202405/W020240527599125758205.png
建议在后续更新样式时也以该图为准。

svg文件（大小均适用于RMP的线路宽度，即5px）：
机场（2024）：
![Airport_Guangzhou_2024](https://github.com/user-attachments/assets/58f52fa4-70c1-4463-a888-4d70f6f45f45)

城际（2024）：
![Intercity_Guangzhou_2024](https://github.com/user-attachments/assets/920e69f5-79d2-4dc6-a53a-96380a49a408)

火车站（2024）：
![Railway_Guangzhou_2024](https://github.com/user-attachments/assets/e9e0cb70-1ad8-4d95-b711-4522b80ff04b)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. They are added in 5.1.2 :)
