### ISSUE TITLE
广州地铁换乘车站（2024）站名位置未实时计算

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#810]
1. 若放置广州地铁换乘车站（2024）或将车站类型修改为此，然后关闭“垂直布局（Vertical layout）”，车站的站名会覆盖站点。
只有重复或复制站点、更改Anchor at选项、更换佛山样式、刷新或导入json文件才能解决。如图：
![image](https://github.com/user-attachments/assets/39b2295c-3493-4c8d-8771-6aec1fabab8b)

2. 正常情况下，后绘制的线段会覆盖先绘制的线段。
但我有一个项目文件，导入到RMP 5.0后，如果先绘制的线段显示为折线线段，那么先绘制的线段总会覆盖后绘制的线段。只有修改深度才能解决。
而且关键的是，该问题在旧版RMP中并没有出现。
以下为仅保留有用信息的存档文件：
[线段bug.json](https://github.com/user-attachments/files/16782501/bug.json)

**Comment by thekingofcity** [comment]
嗨，感谢汇报问题。

关于第二点，预期之中的正确流程和结果是什么？

以上。

**Comment by thekingofcity** [comment]
嗨，第一个问题已在5.0.33中修复，感谢报告问题。

第二个问题应该是缘由简单线段由于其特殊逻辑会提前生成，以避免后续的复杂计算。虽然不是无法保持同一深度时，根据添加的先后顺序显示，但这会极大地增加代码复杂度。所以暂不打算保持之前版本中的特性，即同一深度时，前后顺序可以是任意的，也请理解深度就是为了在此种情况时进行额外手动更改而存在的。

感谢理解 :)
