### ISSUE TITLE
香港MTR车站于RMP出现的问题

### ISSUE THREAD

**Issue by K3N807** [railmapgen/rmp#821]
您好，我想提出一个RMP里出现的问题。
今天我在进入RMP时，发现文件的香港MTR车站字体和前几天不一样，没了原先的粗体。我本以为是MTR官方改了字体，但我发现，官方并没有把字体改变，和平时一样。
官方字体是像这样的：
![image](https://github.com/user-attachments/assets/dc9c219b-8afd-4b8e-8edf-290182304954)

但RMP出现的字体是这样的：
![image](https://github.com/user-attachments/assets/68926b1a-c19d-4923-83e6-3a427baaa360)

而且，当我下载图片时，在没有点选「使用系统字体而不是在画布上预览的字体」的情况下（如图：）
![image](https://github.com/user-attachments/assets/abe2f08e-ab5e-41ad-a5c9-838ab5936fa5)

下载的图片更是完全偏离了「香港MTR车站字体」的样式：
![Weird](https://github.com/user-attachments/assets/22b53e8c-72eb-42b8-a124-5cb0b363811d)

希望可以恢复港铁字体，谢谢。

**Comment by thekingofcity** [comment]
嗨，我们确认了这个问题，正在尝试修复，如果您有急迫的需求，欢迎下在离线程序降级使用 :)

**Comment by K3N807** [comment]
谢谢！

**Comment by thekingofcity** [comment]
嗨，感谢等待，已在版本5.0.28中修复此问题 :)

**Comment by thekingofcity** [comment]
This is a follow up of #759
