### ISSUE TITLE
打开保存的项目时出错

### ISSUE THREAD

**Issue by nsddzl** [railmapgen/rmp#822]
在RMP中，打开2024年9月8日后保存的项目，显示 Something went wrong!以下是操作视频和原文件。

https://github.com/user-attachments/assets/07f11411-2b3d-4278-8aba-4c997c9786c4

[RMP_1726234292953.json](https://github.com/user-attachments/files/17005629/RMP_1726234292953.json)

**Comment by nsddzl** [comment]
本地存储rmp_param太长了，有二十多万字符，github只能输入65536个字符的评论，复制不过来

**Comment by nsddzl** [comment]
所以能修复吗？

**Comment by thekingofcity** [comment]
[RMP_1726234292953.json](https://github.com/user-attachments/files/17052341/RMP_1726234292953.json)

嗨，存档已被修复，见上。此存档的版本应该不会出现超过-5或5的深度，不知为何出现了并在现在的版本中影响了代码的正常运行 :)

**Comment by nsddzl** [comment]
谢谢
