### ISSUE TITLE
Remove double quotes around font names with spaces due to Chrome

### ISSUE THREAD

**Issue by GitLxsr** [railmapgen/rmp#837]
![image](https://github.com/user-attachments/assets/c9906bea-04d3-4fd0-b437-fd68ce496519)
这在空白页面上创建JR东日本的三个图标（线路号，一般站点，重要站点），使用的不是日语字体而是电脑默认字体，甚至在文本框内选择JR东日本日文也不调用

![image](https://github.com/user-attachments/assets/9ad7a0b9-2eec-4c92-b087-c8d5043a8679)
添加了东京地铁的标识后，立马就可以调用日文字体了。但删除东京地铁后刷新，就不会显示日文字体。

**Comment by thekingofcity** [comment]
嗨，JR东日本基本和重要车站都会加载名为`M PLUS 2`的字体，请确认您有正确加载字体后再讨论 :)

https://www.supermonitoring.com/blog/check-browser-http-headers/

There should be a request looking for `rmp/fonts/Mplus2-Medium.otf`

**Comment by GitLxsr** [comment]
请问我要怎么检测字体是否加载？
Host : www.supermonitoring.com
Cf-Connecting-Ip : 103.151.172.94
Cookie : stg_traffic_source_priority=2; stg_externalReferrer=https://github.com/railmapgen/rmp/issues/837; _ga_KLCW8G3CY6=GS1.1.1727178752.1.0.1727178752.0.0.0; _ga=GA1.1.773550705.1727178753; stg_last_interaction=Tue%2C%2024%20Sep%202024%2011:52:33%20GMT; stg_returning_visitor=Tue%2C%2024%20Sep%202024%2011:52:33%20GMT
Priority : u=0, i
Accept-Language : zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6
Referer : https://www.supermonitoring.com/mini-tools/browse/
Sec-Fetch-Dest : iframe
Sec-Fetch-User : ?1
Sec-Fetch-Mode : navigate
Sec-Fetch-Site : same-origin
Accept : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Upgrade-Insecure-Requests : 1
Content-Type : application/x-www-form-urlencoded
Origin : https://www.supermonitoring.com
Sec-Ch-Ua-Platform : "Windows"
Sec-Ch-Ua-Mobile : ?0
Sec-Ch-Ua : "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
Cache-Control : max-age=0
Cf-Visitor : {"scheme":"https"}
X-Forwarded-Proto : https
Content-Length : 931
Cf-Ray : 8c8291b92c50860d-HKG
X-Forwarded-For : 103.151.172.94
Accept-Encoding : gzip, br
Cf-Ipcountry : HK
Cdn-Loop : cloudflare; loops=1

**Comment by GitLxsr** [comment]
另外，这个问题是新版本更新时出现的，之前的版本并没有这个bug

**Comment by thekingofcity** [comment]
嗨，就如同前面回复的链接中提到的，您需要打开开发者工具，切换到网络选项卡，再刷新页面以检查是否有 `.../rmp/fonts/Mplus2-Medium.otf` 请求。

https://www.supermonitoring.com/blog/check-browser-http-headers/

**Comment by GitLxsr** [comment]
嗨，经检查貌似没有。
![image](https://github.com/user-attachments/assets/6c94c2e8-05a7-4e34-bb58-fceca081f1f1)

**Comment by thekingofcity** [comment]
嗨，方便分享并上传这一个存档json吗？

**Comment by GitLxsr** [comment]
您好，已上传：https://share.weiyun.com/treU1Ljl

**Comment by thekingofcity** [comment]
嗨，我们注意到了一个Firefox和Chrome实现差异的问题，现已修复，感谢汇报 :)

**Comment by thekingofcity** [comment]
This is a follow-up of #821

**Comment by thekingofcity** [comment]
The following is not useful after correcting `rmgRuntime.loadFont`.

NOTE: If the font name contains spaces, double quotes should be added.
e.g., cssFont: { 'M PLUS 2': MPLUS2 }, -> cssFont: { '"M PLUS 2"': MPLUS2 },
https://bugzilla.mozilla.org/show_bug.cgi?id=1706648
