### ISSUE TITLE
Color override after new SVG import

### ISSUE THREAD

**Issue by M-ult** [railmapgen/rmp#843]
Dear developer,

I would like to report an issue that occurs after using the Master Node feature: when importing SVGs in RMP using the Master Node, the color of the 2nd SVG overrides the 1st SVG thus making both of them the same.

See the images below for details:
Before:
![before](https://github.com/user-attachments/assets/d2d9d327-2f04-43cb-a511-fa05bcacd464)
After:
![after](https://github.com/user-attachments/assets/7ca08f93-4a0f-4393-af00-df0d233fe360)

I will provide JSON if needed.

**Comment by langonginc** [comment]
Dear friend,

Thank you for reporting this, we are looking into it.

**Comment by langonginc** [comment]
@M-ult , can you provide a more detailed description of how you came to have this problem? I'm not sure about this.

**Comment by M-ult** [comment]
Sorry for the confusion.
The situation is as follows: I have created two icons using the Master node, the first one with a green background and the second one with a blue background. When I import these two icons sequentially in RMP, the green background of the first icon changes to a blue background.

**Comment by langonginc** [comment]
Can you upload the rmp save? (After importing the 2nd icon)

**Comment by M-ult** [comment]
Sure.
[RMP_1727931601087.json](https://github.com/user-attachments/files/17239717/RMP_1727931601087.json)

**Comment by langonginc** [comment]
Thank you for reporting the bug. We will fix it as soon as possible. 

Here are the Designer saves for you. You can use it in place of your master node until we fix the issue.

[designer-1.json](https://github.com/user-attachments/files/17257852/Railmapgen.Designer.json)

[designer-2.json](https://github.com/user-attachments/files/17257854/RMP.Designer.json)
