### ISSUE TITLE
railmapgen导出图片存在问题

### ISSUE THREAD

**Issue by Wong-yu-cheung** [railmapgen/rmp#858]
railmapgen导出图片存在问题，导不出

**Comment by langonginc** [comment]
hi 麻烦提供一下系统信息和浏览器信息，（如 Windows 10 + Edge）

**Comment by Wong-yu-cheung** [comment]
> hi 麻烦提供一下系统信息和浏览器信息，（如 Windows 10 + Edge）

Windows 11+Edge

**Comment by thekingofcity** [comment]
嗨，可以导出json吗？导入画廊中的作品可以导出图片吗？还是都不可以？

**Comment by Wong-yu-cheung** [comment]
可以导出json，画廊中不可导出图片

**Comment by huaiqiu617** [comment]
我也遇到同样的问题，之前都可以导出，昨天开始只能导出json文件不能导出图片了，求解决方法

**Comment by Wong-yu-cheung** [comment]
能尽快解决吗
谢谢

**Comment by thekingofcity** [comment]
嗨，我尝试在不同操作系统和浏览器上均为成功复现此问题，方便分享您的存档吗？请确保上传完成，即Uploading xxx字样小时候再回复 :)

**Comment by thekingofcity** [comment]
嗨，一个可能的问题已被修复，欢迎在5.1.4下重试并分享问题是否已被解决 :)
