### ISSUE TITLE
railmap painter导出图片存在问题

### ISSUE THREAD

**Issue by huaiqiu617** [railmapgen/rmp#859]
之前画线路图都可以导出文件，现在只能导出json文件，但是图片点击导出没有反应，刚试了一下从画廊中导出图片是可以导出的，但自己做的不行，试了几个浏览器都无法导出图片

**Comment by thekingofcity** [comment]
嗨，我尝试在不同操作系统和浏览器上均为成功复现此问题，方便分享您的存档吗？请确保上传完成，即Uploading xxx字样小时候再回复 :)

**Comment by thekingofcity** [comment]
嗨，一个可能的问题已被修复，欢迎在5.1.4下重试并分享问题是否已被解决 :)
