### ISSUE TITLE
Fix guangzhou 2024 facilities size

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp#861]
如图，新增的广州2024设施标识过于大了。
![广州设施2024-bug](https://github.com/user-attachments/assets/7573a6de-1b77-49ab-b224-11b7524b8a08)
下载svg图像并打开，显示边长为80px
但在#809 中上传的svg文件里，边长只有16.667px

**Comment by thekingofcity** [comment]
嗨，您上传的svg中，仅指定了viewbox的长宽而非图片的长宽。除此之外，5月份的途中，标志目测与中文+英文的高度总和一致，设置成16.67的话，将仅与中文高度一致，故最后修复为25的长宽 :)

**Comment by thekingofcity** [comment]
感谢分享准确的字号大小。想一并确认，所有的广州车站，普通站换乘站2024换乘站都是中文14+英文7吗？以及第二名称的中英文字号和未开通的中英文字号大小。这将帮我们准确地更新所有车站到官方样式 :)

**Comment by Minwtraft** [comment]
根据本人再次测算，广州样式字体大小如下：
基本车站与换乘车站字体相同，中文13.13 pt；英文6.56 pt
第二名称：中文10 pt；英文5.42 pt，字间距40；括号13.13 pt
城际铁路车站：中文13.13 pt，字间距75；英文5.83 pt，字间距55
有轨电车：中文7.29 pt；英文5.08 pt
未开通标识：中文6.04 pt；英文3.6 pt
旧版线路图的字体仅有轨电车与2024版线路图不同，中文6.25 pt；英文4.38 pt
如下图：
![广州地铁文字大小](https://github.com/user-attachments/assets/9d564eb6-fe62-4ff3-a0ce-8474c6902eb4)

**Comment by Minwtraft** [comment]
您好！根据本人再次测算，广州样式字体大小如下：
基本车站与换乘车站字体相同，中文13.13 pt；英文6.56 pt
第二名称：中文10 pt；英文5.42 pt，字间距40；括号13.13 pt
城际铁路车站：中文13.13 pt，字间距75；英文5.83 pt，字间距55
有轨电车：中文7.29 pt；英文5.08 pt
未开通标识：中文6.04 pt；英文3.6 pt
旧版线路图的字体仅有轨电车与2024版线路图不同，中文6.25 pt；英文4.38 pt
如下图：
![广州地铁文字大小](https://github.com/user-attachments/assets/9d564eb6-fe62-4ff3-a0ce-8474c6902eb4)

**Comment by thekingofcity** [comment]
感谢分享，我们将在近期调整这些字号，如果您有更多关于广州地铁细节的调整及修改建议，欢迎回复，我们将提及您为广州地铁的样式维护者 :)

**Comment by thekingofcity** [comment]
嗨，有轨电车的车站标识(药丸)是标准车站在缩放多少后的样子？

**Comment by Minwtraft** [comment]
感谢认可！

关于有轨电车的车站标识，经测算应为标准车站大小的0.729倍
以及RMP中的**标准车站**大小似乎不太标准，下载的svg中宽为20.72 px，高为10.36 px；我个人测算出更精确的应为**宽20 px，高10 px**；此时，**有轨电车车站**应为**宽14.583 px，高7.291 px**

**Comment by thekingofcity** [comment]
See #871
