### ISSUE TITLE
无法导出png且导出svg文件为空白画布

### ISSUE THREAD

**Issue by Milarodvia** [railmapgen/rmp#869]
使用Windows10操作系统，使用edge浏览器或chrom浏览器均会发生此问题。
若选择导出png文件选项，无论选取何种缩放尺寸，均会产生报错信息：“图像太大，无法在您的浏览器中生成！”
若选择导出svg文件选项，可以正常生成并下载。但使用软件打开预览时显示为白色画布，无任何内容。
示例工程文件与有关图片如下。

[RMP_1730251272632.json](https://github.com/user-attachments/files/17564890/RMP_1730251272632.json)
![RMP_1730252677646](https://github.com/user-attachments/assets/b5525495-1910-433c-bb4c-dbbc53996089)

![1](https://github.com/user-attachments/assets/2c38b8cb-0cc1-4f98-8470-a3afe23f67e4)
![QQ截图20241030094434](https://github.com/user-attachments/assets/562787a9-b36d-4f66-9b55-569d2cc51f6c)
![QQ截图20241030094510](https://github.com/user-attachments/assets/1d3f91f4-ae9b-4fe9-9aa2-79610ee25224)

**Comment by Milarodvia** [comment]
我们注意到文件在浏览器中可以被正常浏览。请问如何选择选项使得可在ai软件中编辑与浏览？

**Comment by thekingofcity** [comment]
嗨，在浏览器中能正确浏览即表明生成的svg资源符合浏览器标准，但仍有可能不满足svg 1.1的标准。我们对ai做了尽可能的兼容，但看起来仍有部分尚未正确兼容。目前我们无更多精力一一确认是何种标签或属性导致的问题，如果您能二分删除并找出最小可复现的有问题的节点或线段，我们会尽可能去修复并兼容 :)
