### ISSUE TITLE
广州之地铁线路图模板，其换乘站图标准确度仍稍低，请根据本文之 SVG 修正。

### ISSUE THREAD

**Issue by deepinclub** [railmapgen/rmp#87]
![interchange](https://user-images.githubusercontent.com/98749433/196445455-e2e5c93d-300b-46e1-9626-7238e885fb99.svg)

**Comment by deepinclub** [comment]
建议添加三线换乘。

**Comment by 52PD** [comment]
> 建议添加三线换乘。

明明支持三线换乘的为啥还要“建议添加”呢？😓
![RMP_1666147912792](https://user-images.githubusercontent.com/98044618/196586096-92ea2eb8-cd2e-42e9-a226-ab6ebec5095a.png)

**Comment by deepinclub** [comment]
The map will be like this.
![image](https://user-images.githubusercontent.com/98749433/196715994-1fc29909-7f83-4442-8faa-2122ab33d10b.png)

**Comment by deepinclub** [comment]
![interchange](https://user-images.githubusercontent.com/98749433/196716193-0b757f6f-3861-48a6-be45-ad4a48eeaf79.svg)
![interchange3l](https://user-images.githubusercontent.com/98749433/196716197-7c94a365-422d-4184-a1e6-6f153dcce2bf.svg)
![linar](https://user-images.githubusercontent.com/98749433/196716203-f12dff24-6f89-4527-89f0-3308eb728817.svg)

**Comment by deepinclub** [comment]
Drew with Inkscape

**Comment by 52PD** [comment]
![gzmtr_2l_int](https://user-images.githubusercontent.com/98044618/196737484-4173fca0-1edd-4ad5-a1ac-5a2769dda908.svg)
补一个出站换乘的（给予你的那个两线换乘的改的）
下次如果要提交换乘图标麻烦交齐，不要只交一半

**Comment by thekingofcity** [comment]
嗨，感谢对项目的关注与支持。但您的语气让我感到很不爽，在您理解如何与人合作并改正之前，我不会处理此issue中的任何内容，谢谢。
