### ISSUE TITLE
Fix tune stations of Guangzhou Metro

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/rmp#885]
![image](https://github.com/user-attachments/assets/e1b0ddc3-e785-4408-a602-c692a23ce166)
如图，在广州地铁样式字体大小问题未完善，仅更改了广州地铁基本车站和广州地铁换乘站（2024），广州地铁换乘车站、佛山地铁基本车站字体大小未更改。

**Comment by hackerfyl** [comment]
补充：字体大小改变后，有轨电车样式的文字偏移过大
![image](https://github.com/user-attachments/assets/55211414-3881-46ca-a2b6-dfc6edb3de71)

**Comment by thekingofcity** [comment]
Hi, thanks for reporting the problem.

We fixed them and are available at [UAT](https://uat-railmapgen.github.io/?app=rmp) for testing. Feel free to have a try and comment if they are expected :)

Bests,
thekingofcity

**Comment by thekingofcity** [comment]
This is a follow-up of #871

**Comment by hackerfyl** [comment]
此次更新后出现了新的问题：
1.广州地铁换乘车站偏小
![image](https://github.com/user-attachments/assets/d796424f-d916-43e7-ae16-fdafc590dda5)
2.无论是普通车站还是有轨车站，当文字偏移为正上，英文多于一行时，文字覆盖站点
![image](https://github.com/user-attachments/assets/55a019c9-dd4c-449c-bc71-c19f5eefbd47)
![image](https://github.com/user-attachments/assets/4da2acf4-7a5c-40c2-8b84-f070a4f1f5eb)
