### ISSUE TITLE
Designing gzmtr-basic and gzmtr-int

### ISSUE THREAD

**Issue by picencrypt** [railmapgen/rmp#92]
![gzmtr-int](https://user-images.githubusercontent.com/98749433/196934017-fb58470a-56bb-4836-a3ea-e0293dca02cc.svg)
![gzmtr-int](https://user-images.githubusercontent.com/98749433/196934022-95a4923a-7955-4cd6-b629-8b30b5ad98dd.svg)
![gzmtr-int3](https://user-images.githubusercontent.com/98749433/196934024-90a33936-ab8d-4576-a6b8-941432511660.svg)
![gzmtr-basic](https://user-images.githubusercontent.com/98749433/196934029-8b983e81-1bdb-481e-80d0-50ade2ce7115.svg)

**Comment by deepinclub** [comment]
#87

**Comment by deepinclub** [comment]
@wongchito We found some vector icons for these. It looks like the official one.

**Comment by thekingofcity** [comment]
Great to see you learned how to collaborate with others.

For gzmtr-basic station, I believe there is no need for any updates as the current icon is copied from RMG and passed thousands of RMG users' tests.

For gzmtr-int station, I appreciate your detailed SVG project. But there are some gaps between your work and actual implementation in RMP.

## Transfer stations with one or two lines

1. Duplicate arrows: the bottom arrow could be simplified with `translate` and `rotate`.
2. Possible `<marker>`: is it possible to use a marker to draw the triangle at the end of the arrow?

## Transfer stations with three or more lines

1. General arrows: Currently, arrows are generated with algorithms to comply with possible future 4+ transfer lines. How can we achieve this by using your work? I would consider drawing icons for every possible transfer station as an unwise decision.

If we manage to draw arrows with [simple arc](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#elliptical_arc_curve) and [marker-end](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-end), I would like to update gzmtr-int station icon.

**Comment by thekingofcity** [comment]
Hi, there is a small update that adds a white mask under the gzmtr-int with 2 transfers. However, this does not mean the issue discussed here is fixed. Best Regards.

![image](https://user-images.githubusercontent.com/3353040/211156642-cae1bffc-491d-498a-a60b-2ccc0332e673.png)
> Before

![image](https://user-images.githubusercontent.com/3353040/211156632-6ae087bd-0177-4eff-809d-be985e2dab78.png)
> After

**Comment by picencrypt** [comment]
In the official version, the arrow end is horizontal.

**Comment by thekingofcity** [comment]
> In the official version, the arrow end is horizontal.

Hi, which arrow are you referring to? And what does horizontal mean?

**Comment by picencrypt** [comment]
![196934017-fb58470a-56bb-4836-a3ea-e0293dca02cc](https://user-images.githubusercontent.com/98749433/214912051-a40fe0cd-193b-4dca-9f33-5ce8e51063dd.svg)
![196934024-90a33936-ab8d-4576-a6b8-941432511660](https://user-images.githubusercontent.com/98749433/214912069-c5833afd-c90c-459b-95bd-75ed512c1a23.svg)
![196934022-95a4923a-7955-4cd6-b629-8b30b5ad98dd](https://user-images.githubusercontent.com/98749433/214912147-379df9c6-dcec-446e-9bb8-6869e3972762.svg)
This is the official map design. And the transfer, aka, interchange stations look like these.

**Comment by picencrypt** [comment]
Arrow is circled red and lines
![Uploading Screenshot_20230127_020747.jpg…]()

**Comment by picencrypt** [comment]
![Screenshot_20230127_020747](https://user-images.githubusercontent.com/98749433/214915865-57cca07d-6c3a-45ca-b137-df85a3e67644.jpg)

**Comment by thekingofcity** [comment]
Yeah, I'm aware of the imperfection of the current icons. If you have any ideas for solving the problems in this [comments](https://github.com/railmapgen/rmp/issues/92#issuecomment-1301679071), I'll be willing to work on this ASAP.

**Comment by thekingofcity** [comment]
Hi, are you still willing to make the updated 4-line interchange station? Though it is not a good idea to use static SVG files, it is the simplest and easiest way to add support for this scenario. Looks like we don't have any other options here :(

**Comment by picencrypt** [comment]
Hello. I hope that gzmtr-int could be like this, the arrow in RMP is different from the official style. Here is Kecun Officially and below is Nanzhou in RMP.[cid:5e2afac3-edb1-484d-a6cb-b04188105968][image]
________________________________
发件人: ***@***.*** ***@***.***> 代表 thekingofcity ***@***.***>
发送时间: 2024年1月5日 05:17
收件人: railmapgen/rmp ***@***.***>
抄送: PicEncrypt Project ***@***.***>; Author ***@***.***>
主题: Re: [railmapgen/rmp] Designing gzmtr-basic and gzmtr-int (Issue #92)


Hi, are you still willing to make the updated 4-line interchange station? Though it is not a good idea to use static SVG files, it is the simplest and easiest way to add support for this scenario. Looks like we don't have any other options here :(

―

**Comment by thekingofcity** [comment]
Hi, images are not uploaded successfully. If possible, a 4-line interchange station could be online as soon as the svg file is uploaded :)

**Comment by thekingofcity** [comment]
See #544 and #544 for the new gzmtr-basic and gzmtr-int :)
