### ISSUE TITLE
Failed to duplicate misc node

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [railmapgen/rmp#93]
在使用RMG主页 0.2.12版本情况下（图示使用RMG主页 UAT版本，并未使用UAT版本进行测试），点击如图所示的“复制”按键造成RMP应用崩溃。
![捕获](https://user-images.githubusercontent.com/89013535/197384042-6b04f335-f65b-40ca-8000-c7708cc9c854.PNG)

**Comment by thekingofcity** [comment]
嗨，感谢报告问题。我已确认问题存在并考虑今晚上线紧急修复。

线上版本更新后可能需要您清空当前网站的所有数据，如果您有恢复当前存档的要求，欢迎加入slack获得一对一指导。

**Comment by thekingofcity** [comment]
嗨这个问题已被修复于RMP 0.1.38，感谢您的汇报。
